### ISSUE TITLE
Add support for EventChannel

### ISSUE THREAD

**Issue by Drakirus** [go-flutter-desktop/go-flutter#103]
https://docs.flutter.io/flutter/services/EventChannel-class.html

**Comment by Drakirus** [comment]
C++ implementation: https://github.com/cloudwebrtc/flutter-engine/commit/a2fb127e4d984c08cac5871cc687301d0d140457#diff-412ef158a1f525f3234237794a50dd0c

**Comment by zephylac** [comment]
I've looked into it, but since I'm not an expert in golang, I don't know how to implement stream-a-like in Go.
