### ISSUE TITLE
Support ctrl-delete

### ISSUE THREAD

**Issue by GeertJohan** [go-flutter-desktop/go-flutter#104]
`ctrl-delete` doesn't work as epxected on most desktop systems. Support should be added to the builtin textinput plugin.

**Comment by zephylac** [comment]
I could try to implement it. It seems to be relatively similar to what I've done in the past.

**Comment by zephylac** [comment]
I can not get a working test platform. I can still try to do it but I won't be able to test it.

**Comment by GeertJohan** [comment]
@zephylac Can you create an issue about the issues you're experiencing? If possible with screencast/screenshots to desmonstrate the issues and information about your MacOS version.

**Comment by GeertJohan** [comment]
Work being done in #153

**Comment by Drakirus** [comment]
Merged
