### ISSUE TITLE
Hover: windows

### ISSUE THREAD

**Issue by ghost** [go-flutter-desktop/go-flutter#106]
Can we add the dependencies for Windows in the Readme.
https://github.com/go-flutter-desktop/hover/blob/master/README.md#install

Also for Windows it makes sense for Hover to build this way?
```
go build -ldflags -H=windowsgui
```
There is still other things to get working for windows, but adding this will allow lots of devs on windows to easily help dogfood and improve go-flutter.
Many devs i know are now using go-flutter and some are on windows.

**Comment by gedw99** [comment]
also found this helpful - 

Windows dev env setup and build instructions:
Setup choco package manager https://chocolatey.org/docs/installation

Use choco to install golang and mingw 
```choco install golang mingw```

**Comment by GeertJohan** [comment]
This issue is related to #156

**Comment by Sach97** [comment]
Hi guys I never packaged an app before but I thought I would share my findings here : [msix-packaging](https://github.com/microsoft/msix-packaging) it is written in C and works on mac, linux and windows.

**Comment by Drakirus** [comment]
Moved to #207.
