### ISSUE TITLE
hover run gives error 

### ISSUE THREAD

**Issue by maheshbhattaraai** [go-flutter-desktop/go-flutter#107]
Example name: 
Examples repository version: 

## Flutter version

```
Flutter 1.1.2 • channel dev • https://github.com/flutter/flutter.git
Framework • revision xxxxxxxxxx (x weeks ago) • xxxxxxxxxxxxxxxxxxxxxxxx
Engine • revision xxxxxxxxxx
Tools • Dart 2.2.1 (build xxxxxxxxxx)
```

## Golang errors (Optional)

```
Golang's compiling errors
```

## Steps to Reproduce

1. xxx
![Screenshot_1](https://user-images.githubusercontent.com/34735076/55497166-79185e00-5660-11e9-94f0-e14bd59096f3.jpg)

2. xxx
3. xxx

**Comment by GeertJohan** [comment]
It looks like some install depdendencies steps for windows are still missing.. I'm not using windows daily, but will walk through the instructions on a fresh windows VM to see what's missing.

For now, looking at the error, it seems that gcc needs to be installed.

**Comment by GeertJohan** [comment]
I'm reading installing mingw should fix the issue. https://mingw-w64.org/doku.php

**Comment by maheshbhattaraai** [comment]
This Issue had resolved may be due to  slow internet connection.
How can i navigate into text field through tab or how can i handle short cut keys

**Comment by GeertJohan** [comment]
@maheshbhattaraai tabnavigation is not yet supported. Shortcut keys are implemented by default.
