### ISSUE TITLE
Go install error in windows 10

### ISSUE THREAD

**Issue by maheshbhattaraai** [go-flutter-desktop/go-flutter#108]
## Flutter version

```
Flutter 1.2.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision xxxxxxxxxx (x weeks ago) • xxxxxxxxxxxxxxxxxxxxxxxx
Engine • revision xxxxxxxxxx
Tools • Dart 2.1.1 (build xxxxxxxxxx)
```

## Golang errors (Optional)

```
Golang's compiling errors
```

## Steps to Reproduce

1. xxx
2. xxx
3. xxx
![Screenshot_2](https://user-images.githubusercontent.com/34735076/55612029-f948db80-57a6-11e9-9089-e7cb1cad2cec.jpg)

**Comment by Drakirus** [comment]
You are using the deprecated source code.
https://github.com/go-flutter-desktop/go-flutter/wiki/Package-has-moved-to-an-organization
https://github.com/go-flutter-desktop/go-flutter#getting-started

**Comment by maheshbhattaraai** [comment]
So how can i convert flutter completed app into desktop app?

**Comment by Drakirus** [comment]
https://github.com/go-flutter-desktop/hover

**Comment by maheshbhattaraai** [comment]
i had already run example app using hover run . What is next step. I created flutter app first or i need to clone go flutter desktop then create flutter project.

**Comment by GeertJohan** [comment]
Create a normal flutter project, then use hover in that project. 
Follow these instructions: https://github.com/go-flutter-desktop/hover#init-project-for-hover

**Comment by maheshbhattaraai** [comment]
The project must be uploaded into github  to initialize hover.

**Comment by maheshbhattaraai** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/34735076/55640387-31720d80-57eb-11e9-9837-97ebc2d5dc6f.jpg)

**Comment by maheshbhattaraai** [comment]
> #Solved
