### ISSUE TITLE
Can't install hover on OSX 10.14

### ISSUE THREAD

**Issue by marquesinijatinha** [go-flutter-desktop/go-flutter#111]
## Flutter version
```
Flutter 1.3.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e5b1ed7a7f (4 weeks ago) • 2019-03-06 14:23:37 -0800
Engine • revision f4951df193
Tools • Dart 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)
```

## Golang errors (Optional)
```
../../../go/src/github.com/go-flutter-desktop/hover/cmd/run.go:48:31: cmdApp.ProcessState.ExitCode undefined (type *os.ProcessState has no field or method ExitCode)
```

## Golang version
``` go version go1.10.8 darwin/amd64```

## Steps to Reproduce
tried to run
```go get -u github.com/go-flutter-desktop/hover```

**Comment by GeertJohan** [comment]
Please update your version of Go. Version 1.10.8 is quite old and doesn't support that field.

**Comment by marquesinijatinha** [comment]
thanks for the heads up.
For future reference, I think the current version of go on homebrew is outdated.
uninstalling it and installing from the official site fixed the problem.

**Comment by elbashery** [comment]
Yes it succeeded
thank you very mutch
