### ISSUE TITLE
hover run error

### ISSUE THREAD

**Issue by maheshbhattaraai** [go-flutter-desktop/go-flutter#112]
## Flutter version

```
Flutter x.xx.x • channel beta • https://github.com/flutter/flutter.git
Framework • revision xxxxxxxxxx (x weeks ago) • xxxxxxxxxxxxxxxxxxxxxxxx
Engine • revision xxxxxxxxxx
Tools • Dart x.x.x (build xxxxxxxxxx)
```

## Golang errors (Optional)

```
Golang's compiling errors
```

## Steps to Reproduce

1. xxx
2. xxx
3. xxx
![Screenshot_4](https://user-images.githubusercontent.com/34735076/55664715-ae849d80-5852-11e9-9f7b-efae3e9ccf3b.jpg)

**Comment by GeertJohan** [comment]
@maheshbhattaraai Please add all the required information. What version of flutter and go are you using, what steps can we take to reproduce the issue?

**Comment by GeertJohan** [comment]
It looks like this error occurs when an older version of flutter is installed. Please upgrade to 1.3.8 which is on the beta channel.

```bash
flutter channel beta
flutter upgrade
```
