### ISSUE TITLE
Let hover check flutter version

### ISSUE THREAD

**Issue by GeertJohan** [go-flutter-desktop/go-flutter#114]
A lot of support questions are due to old versions of flutter. Perhaps we should let hover check the flutter version and display and quit with an error when it is not compatible.

**Comment by Drakirus** [comment]
Flutter version is checked by the flutter toolkit.
What's is missing IMO is a check on the flutter channel (as the README says `go-flutter project tries to stay compatible with the beta channel `)
I created https://github.com/go-flutter-desktop/hover/pull/10, in this PR hover checks the channel of flutter and print an warning if the channel isn't `beta`
