### ISSUE TITLE
I can't get hover installed, I think.

### ISSUE THREAD

**Issue by ogierm** [go-flutter-desktop/go-flutter#118]
Hey, I'm on Manjaro Linux and I'm trying to get the whole thing running. I was following your guide, but I can't get hover started over the comand line because it is not found.

Do I have to add it to PATH? I tried running hover from it's directory but it wasn't found their either. I also tried `go run github.com/go-flutter-desktop/hover` which didn't result in an error, but also didn't do anything.

**Comment by GeertJohan** [comment]
`go get` probably installed it to ~/go/bin. Please check ifits there, thenadd thatfolder to your PATAH

**Comment by ogierm** [comment]
Go get just downloaded the files to `~/go/src/github.com/go-flutter-desktop/hover`. However I also tried installing it and then it was installed to bin.
