### ISSUE TITLE
Multiple root windows support

### ISSUE THREAD

**Issue by ghost** [go-flutter-desktop/go-flutter#123]
Support an app opening multiple windows from the same app.

For example I'm an email app you may want to see 2 emails at the same time so you can compare them.

Or for a painting app, I might want to have the tools floating in another window.

Stuart added this to flutter engine :

https://github.com/flutter/flutter/issues/30701

Strategy still being discussed it seems.

Regarding synchronisation, we could use an event bus at the golang level as a stop gap for now. But first need to be able to spawn new windows from the one app first

**Comment by etx** [comment]
Was there any movement on this? Looks like the flutter team is still working on it. 

I'm trying to figure out how to pop another window with go-flutter right now using different root app. It doesn't even need to talk to the main process for my use.

**Comment by pchampio** [comment]
Once the feature is available in the flutter engine, we will implement it.
Any other work-around will end-up in a waste of time.

**Comment by pchampio** [comment]
Tracked by: https://github.com/flutter/flutter/issues/30701
