### ISSUE TITLE
Provide easy way to bootstrap roboto fonts in

### ISSUE THREAD

**Issue by ghost** [go-flutter-desktop/go-flutter#124]
For each OS users need to install the Roboto fonts.

https://www.fontsquirrel.com/fonts/roboto

A user can elect to install them via hover. It knows where to put them.

**Comment by GeertJohan** [comment]
I would say fonts should be included using the flutter assets/fonts system, so that it works the same on all platforms. We should write documentation on this.

**Comment by Drakirus** [comment]
documentation has been written in the https://github.com/go-flutter-desktop/hover readme and on the website.
