### ISSUE TITLE
 I have an error when I execute the command hover run

### ISSUE THREAD

**Issue by OrionWambert** [go-flutter-desktop/go-flutter#125]
Example name: simple_demo
Examples repository version: 53bbca4daca9b927177c09be9df22c0679b60d24

## Flutter version

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [version 10.0.10240], locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.3)
[!] Connected device
    ! No devices available

```

## Golang errors

```
Golang's compiling errors
hover run
Using engine from cache
Running "flutter packages get" in simple_demo...                    6,6s
go: finding github.com/go-gl/glfw latest
# runtime/cgo
gcc: error: WAMBERT\AppData\Local\hover\engine\windows: No such file or director                        y
Go get -u github.com/go-flutter-desktop/go-flutter failed: exit status 2

```

## Steps to Reproduce
1. git clone https://github.com/go-flutter-desktop/examples.git
2. cd examples/simple_demo # or examples/stocks
3. hover run

I think it's because it does not support spaces at the system path

runtime / cgo
gcc: error: WAMBERT \AppData\Local\hover\ engine\windows: No such file or directory

it tries to find the folder windowns in WAMBERT \AppData\Local\hover\ engine\windows

while normally it's in C:\Users\ Orion WAMBERT\AppData\Local\hover\engine\windows

**Comment by GeertJohan** [comment]
Duplicated by #184, closing this one.
