### ISSUE TITLE
How to make the length and width of the window fixed ？

### ISSUE THREAD

**Issue by wupeaking** [go-flutter-desktop/go-flutter#126]
## Flutter version

```
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (10 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

I want to know how to set the length and width fixed.  It seems flutter have no such api. (；′⌒`)

**Comment by Drakirus** [comment]
For this and similar requests read: [GLFW Plugin example](https://github.com/go-flutter-desktop/go-flutter/wiki/GLFW-Plugin-example)

**Comment by GeertJohan** [comment]
After consideration, @Drakirus and I have decided to indeed implement this feature in the go-flutter package as Option. PR comming soon :tm:

**Comment by maheshbhattaraai** [comment]
Please add min width and min height bound only .Not bound for Max height and width in flutter.WindowInitialDimensions() function. Which must be optional parameter for minium bounded height and width.

**Comment by Drakirus** [comment]
Glfw uses 4 parameters in SetSizeLimits https://www.glfw.org/docs/latest/group__window.html#gac314fa6cec7d2d307be9963e2709cc90
Use glfw.DontCare as the glfw says
