### ISSUE TITLE
Exception when launching on Windows 10

### ISSUE THREAD

**Issue by atresnjo** [go-flutter-desktop/go-flutter#131]
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (3 months ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
go1.12.4 windows/amd64

Created default flutter app, executed hover init, created main_desktop.dart same as in the provided samples, executed hover run. The app launches but keeps throwing the unhandled exception and the UI freezes then. Thanks for the project! 👍 

result:

![grafik](https://user-images.githubusercontent.com/41112852/57222582-65676b00-7003-11e9-9d31-f42c0018d46e.png)

**Comment by Drakirus** [comment]
You are using the stable channel, after switching to the beta channel does the errors persist?
> [The go-flutter project tries to stay compatible with the beta channel of Flutter.](https://github.com/go-flutter-desktop/go-flutter#flutter-version)

**Comment by atresnjo** [comment]
> 
> 
> You are using the stable channel, after switching to the beta channel does the errors persist?
> 
> > [The go-flutter project tries to stay compatible with the beta channel of Flutter.](https://github.com/go-flutter-desktop/go-flutter#flutter-version)

That worked. My bad for missing that one. Thanks. 👍
