### ISSUE TITLE
error when installing hover

### ISSUE THREAD

**Issue by elbashery** [go-flutter-desktop/go-flutter#139]

**Comment by elbashery** [comment]
when i install hover with : 
### go get -u github.com/go-flutter-desktop/hover
it show is error : 
### gowork/src/github.com/go-flutter-desktop/hover/cmd/run.go:78:30: cmdApp.ProcessState.ExitCode **_undefined (type *os.ProcessState has no field or method ExitCode)_**

**Comment by Drakirus** [comment]
#111

**Comment by elbashery** [comment]
Yes it succeeded
thank you very mutch
