### ISSUE TITLE
failed to decode envelope: unexpected end of JSON input

### ISSUE THREAD

**Issue by GeertJohan** [go-flutter-desktop/go-flutter#141]
Errors like these may occur in the standard output:

```go-flutter: failed to pop route after escape key press: failed to decode envelope: unexpected end of JSON input```

This is the case because InvokeMethod always expects a response which it wants to decode, but we don't always get a response. Currently responses are not implemented (https://github.com/flutter/flutter/issues/18852), and even when they are, some methods don't return a response.

Java has `InvokeMethod` vs `InvokeMethod with callback`. Perhaps we should also provide two methods, one which doesn't expect a response and therefore doesn't try to decode it (resulting in decode error)

**Comment by Drakirus** [comment]
fix taged in tag: [v0.29.0](https://github.com/go-flutter-desktop/go-flutter/releases/tag/v0.29.0)
