### ISSUE TITLE
Hide "no handler for method" errors when they are no-op on desktop

### ISSUE THREAD

**Issue by GeertJohan** [go-flutter-desktop/go-flutter#149]
Some of these errors are annoying, and are not really an error on desktop.

- 'TextInput.show' on channel 'flutter/textinput'
- 'SystemChrome.setSystemUIOverlayStyle' on channel 'flutter/platform

These don't need to do anything on desktop.

For a list of possible options to silence, see https://api.flutter.dev/flutter/services/SystemChannels/platform-constant.html (and sibling pages)

**Comment by zephylac** [comment]
I found a way to deal with this problem:

 We could implement this method 
 ```
 func (p *textinputPlugin) handleHide(arguments interface{}) (reply interface{}, err error) {
	return nil, nil
 }
 ```
 and then add this inside [here](https://github.com/go-flutter-desktop/go-flutter/blob/master/textinput.go#L48-L56):
 ```
 p.channel.HandleFunc("TextInput.show", p.handleHide)
 ```

**OR**

Create constant with all method handler we want to hide and add a check inside [here](https://github.com/go-flutter-desktop/go-flutter/blob/master/plugin/method-channel.go#L128-L150)

**Comment by GeertJohan** [comment]
I prefer the first method. Name `handleIgnore` would be more descriptive.
Each registration of handleHide should be acompanied with a comment explaining why the message / method call is ignored: e.g.: Desktop

**Comment by Drakirus** [comment]
The PR  #168 fixed haft of the issue.
Missing `TextInput.hide`, `HapticFeedback.vibrate`, `SystemSound.play`, `SystemChrome.setApplicationSwitcherDescription`, `SystemChrome.setEnabledSystemUIOverlays`, `SystemChrome.setPreferredOrientations`.
