### ISSUE TITLE
Documentation/Instructions request: Guide to writing plugins

### ISSUE THREAD

**Issue by radzish** [go-flutter-desktop/go-flutter#150]
Hello,

It would be very helpful to have some simple instructions on how to write own plugins for not go lang users. I have seen examples and I feel like I can do my own, but it would be nice to know how can I compile them, where should I put them in my app, etc..

**Comment by Drakirus** [comment]
I have written in a [wiki](https://github.com/go-flutter-desktop/go-flutter/wiki) a [tips](https://github.com/go-flutter-desktop/go-flutter/wiki/Plugin-info#tips) where I go in further details on how to compile/build Plugins.
It's not the most exhaustive guide, is the wiki page is sufficient enough?

**Comment by radzish** [comment]
@Drakirus thanks a lot for prompt response. Tips section of wiki helped a lot and now I have one of my plugins working!

I would suggest few fixes to Tips section though:
1. rename github.com/go-flutter-desktop/plugins/not-on-remote to github.com/go-flutter-desktop/plugins/not_on_remote, as "not-on-remote" seems to be not valid identifier
2. change line
```
replace github.com/go-flutter-desktop/plugins/not-exist => /home/drakirus/lab/go/src/github.com/go-flutter-desktop/plugins/not-on-remote 
```
to 
```
replace github.com/go-flutter-desktop/plugins/not_on_remote => /home/drakirus/lab/go/src/github.com/go-flutter-desktop/plugins/not_on_remote
```

**Comment by Drakirus** [comment]
I've updated the https://github.com/go-flutter-desktop/go-flutter/wiki with a more exhaustive guide (https://github.com/go-flutter-desktop/go-flutter/wiki/Implement-a-plugin).
Closing the issue.
