### ISSUE TITLE
Add mouse button support

### ISSUE THREAD

**Issue by Drakirus** [go-flutter-desktop/go-flutter#151]
The embedding API now support device type and different buttons, allowing for right click, middle click, etc.
Some reading:
 - flutter/engine [PR](https://github.com/flutter/engine/pull/9034/files), updated field: `FlutterPointerEvent`
 - go-gl/glfw [MouseButton doc](https://godoc.org/github.com/go-gl/glfw/v3.2/glfw#MouseButton)
 - go-flutter [code to change](https://github.com/go-flutter-desktop/go-flutter/blob/master/glfw.go#L100)

**Comment by Drakirus** [comment]
The embedding API now support for device type and different buttons, allowing for right click, middle click,etc.
Some reading:
 - flutter/engine [PR](https://github.com/flutter/engine/pull/9034/files)
 - go-gl/glfw [MouseButton doc](https://godoc.org/github.com/go-gl/glfw/v3.2/glfw#MouseButton)
 - go-flutter [code to change](https://github.com/go-flutter-desktop/go-flutter/blob/master/glfw.go#L100)

**Comment by zephylac** [comment]
I'll do it.
Just some question :
Do we want it to handle like keyboard and have separated files for each platform ?
Do we want to enable user customisation like keyboard where they can customise the callback ?

**Comment by GeertJohan** [comment]
I think left/right/middle-click is fairly equal cross-platform. It doesn't feel like it needs separate implementation for win/mac/linux.
I don't think we need customization. This is quite straightforward: mapping GLFW mouse buttons to the embedder PointerEvent.

**Comment by GeertJohan** [comment]
Closed by #159
