### ISSUE TITLE
hover run failed

### ISSUE THREAD

**Issue by huang-weilong** [go-flutter-desktop/go-flutter#152]
When I execute `hover run`, I get this message:
```
D:\flutter\temporary\examples\simple_demo>hover run
Using engine from cache
go: finding github.com/go-flutter-desktop/go-flutter master
go get github.com/go-flutter-desktop/go-flutter@master: unknown revision master
Go get -u github.com/go-flutter-desktop/go-flutter failed: exit status 1
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.765], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)
```

**Comment by Drakirus** [comment]
What is your go version?
Is upgrading go fixes the issue?

**Comment by huang-weilong** [comment]
my go version is `go version go1.12.5 windows/amd64`
I thought it was the reason for the flutter version, so I just upgraded the flutter version, but it still is the same failure.
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale zh-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)
```

**Comment by Drakirus** [comment]
Can you try `hover run - b ''`

**Comment by iambudi** [comment]
MacOS 10.14.5
Go 1.12.5
Flutter 1.5.4-hotfix.2
Dart 2.3.0
`hover run` or `hover run -b ''` shows black screen.

> Using engine from cache
> go: finding github.com/go-flutter-desktop/go-flutter master
> go: finding github.com/go-gl/glfw latest
> [ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
> [ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
> [ERROR:flutter/shell/common/engine.cc(175)] Could not prepare to run the isolate.
> [ERROR:flutter/shell/common/engine.cc(122)] Engine not prepare and launch isolate.
> [ERROR:flutter/shell/platform/embedder/embedder_engine.cc(69)] Could not launch the engine with configuration.
> flutter: Observatory listening on http://127.0.0.1:50300/nvW_T9NeREQ=/
> Syncing files to device Flutter test device...                     335ms

**Comment by zephylac** [comment]
@iambudi Try to resize the window. It usually fix the problem.

**Comment by Drakirus** [comment]
The issue related by @iambudi is not the same as the one described by @huang-weilong, please open a new issue.  
<details>
<summary></summary>

> [ERROR:flutter/shell/common/engine.cc(175)] Could not prepare to run the isolate.
[ERROR:flutter/shell/common/engine.cc(122)] Engine not prepare and launch isolate.
[ERROR:flutter/shell/platform/embedder/embedder_engine.cc(69)] Could not launch the engine with configuration

Humm, There seems to be a problem with the flutter bundle. (created with `flutter build bundle`)

@iambudi Can you share the content of `desktop/build/outputs/`
-  `ls desktop/build/outputs/ -R`

</details>

**Comment by Drakirus** [comment]
@huang-weilong does the error still occurs?

**Comment by iambudi** [comment]
> @iambudi Try to resize the window. It usually fix the problem.

I tried again today, it works now. Tho when resizing the window it gives a lot of flicker.

**Comment by huang-weilong** [comment]
@Drakirus Successfully run after reinstalling hover

**Comment by Drakirus** [comment]
@huang-weilong OK thanks, closing the issue.
@iambudi the resizing flicker comes from the engine it's a won't fix for go-flutter-desktop. issues/30671 on the flutter tracker
