### ISSUE TITLE
Take screenshot of the OpenGL window

### ISSUE THREAD

**Issue by gedw99** [go-flutter-desktop/go-flutter#16]
Just raising this as a placeholder as we will need printing.
DO you want to add this to the readme TODO list ?

https://github.com/alexbrainman/printer
- Windows Printing. Works well.

The big question is how to get Print a Flutter Page. I see two approaches
1. Use PDF, and so you need to write code ( in golang) to output a PDF
- Good:
      - Nice for Report generation where whats on the Flutter Page is different than whats on.
- Bad:
      - Requires writing PDF code for every screen. Tedious 

2. Use Flutter to take a screenshot of the Flutter Page or Widget
- Then just embed it into a PDF and send it off to the Printer

**Comment by Drakirus** [comment]
I guess we could try `glReadPixels` which captures the OpenGL window into a memory buffer. (Need to format the data to jpg manually).

This is the role of the embedder to perform those low-level tasks. I am not against having this by default into the embedder.

**Comment by Drakirus** [comment]
What about https://stackoverflow.com/questions/51117958/how-to-take-a-screenshot-of-the-current-widget-flutter/51118088 ?

**Comment by Drakirus** [comment]
> "Hopefully your thinking about reuse of golang code across both mobile and desktop ?"
If you want to reuse golang's code across both mobile and desktop, you will have to write a *go-flutter-desktop-embedder*'s plugin which will proxy your plugin's request/response to something like https://github.com/adieu/flutter_go.

**Comment by gedw99** [comment]
Thanks for the heads up

I think I can easily deal with that.

This project is awesome

**Comment by Drakirus** [comment]
There is even a [pub plugin](https://pub.dev/packages/screenshot) for screenshot (no platform message needed)
Closing for cleanup.
