### ISSUE TITLE
Add codeblock colors to hover.build

### ISSUE THREAD

**Issue by GeertJohan** [go-flutter-desktop/go-flutter#165]
The hover.build website shows multiple code blocks, these are not colored right now, but should be. Investigate a good codeblock color plugin for hugo, or client-side. Copy button would be nice to have as well.

**Comment by Drakirus** [comment]
I took the liberty to push changes to the website repo.

Duplicating wikis isn't maintainable, I prefer to have everything on github. That why my changes are include redirecting the user the the github wiki.

About the blog, with medium I really thing that having personal hugo blog aren't made for massive sharing, deleted the hover.build link to the empty hover.build/blog site.

Overall, maintaining this site can be a lot of work, that why I prefer to keep it simple & minimal.

**Comment by pchampio** [comment]
I want to clean the issue backlog.
Since there isn't much content on hover.build, I guess it's not our top priority.
