### ISSUE TITLE
Surport FLUTTER_STORAGE_BASE_URL

### ISSUE THREAD

**Issue by leedstyh** [go-flutter-desktop/go-flutter#167]
Hi, 

Developers in China facing issue when downloading flutter related files, and flutter team has a solution [here](https://flutter.dev/community/china). 

Now I get error message when running `hover run` like this:

```
Downloading engine for platform windows-x64 at version 2589785b5c...
Failed to download engine: Get https://storage.googleapis.com/flutter_infra/flutter/2589785b5c5eaad64d1da3403048e61d8f230c48/windows-x64/windows-x64-embedder.zip: dial tcp 172.217.161.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

I changed URL `https://storage.googleapis.com/flutter_infra/flutter/2589785b5c5eaad64d1da3403048e61d8f230c48/windows-x64/windows-x64-embedder.zip` to `https://mirrors.sjtug.sjtu.edu.cn/flutter_infra/flutter/2589785b5c5eaad64d1da3403048e61d8f230c48/windows-x64/windows-x64-embedder.zip`, and opening it in browser can download this `.zip` file.

So any chance supporting `FLUTTER_STORAGE_BASE_URL` in go-flutter-desktop/go-flutter?

**Comment by Drakirus** [comment]
I've updated hover to support `FLUTTER_STORAGE_BASE_URL`
To update hover run: `go get -u github.com/go-flutter-desktop/hover`

Does the new version of hover fixes the isses?

**Comment by leedstyh** [comment]
Yeah, thank you for the quick fix
