### ISSUE TITLE
Hover: offline building

### ISSUE THREAD

**Issue by chengxuncc** [go-flutter-desktop/go-flutter#169]
## Flutter version

```
Flutter 1.7.10-pre.18 • channel master • https://github.com/flutter/flutter.git
Framework • revision 577c2fc48c (20 hours ago) • 2019-06-26 05:40:55 +1200
Engine • revision ae8e6d9f46
Tools • Dart 2.4.0
```

## Advise
It can be slow when using `hover run` to debug golang code, which usually need to reboot many times. Especially when my network become bad or going down, it keep killing my time. I think `hover run` shouldn't execute `go: finding github.com/go-gl/glfw latest` every time, it wastes time.

## Steps to Reproduce
```
hover run
```

**Comment by Drakirus** [comment]
`flutter build bundle` is also executed every time (about a second). 
Having a `--cached` flag to `hover run` sound a good fix to me.

**Comment by Drakirus** [comment]
I take back what I said about `--cached`.

Having a periodic `go get - u` (one a week for example) is the best way to resolve this issue.
Plus we could use the same trigger to check any updates on hover itself.

**Comment by GeertJohan** [comment]
Agreed, perhaps the `go get` should be less aggressive. Although a weekly `go get` will result in unexpected behavior. Either we should run it, or we don't and leave `go get` to the user.
