### ISSUE TITLE
How to set DPI for hover run and/or build

### ISSUE THREAD

**Issue by alexelisenko** [go-flutter-desktop/go-flutter#171]
I am running on Windows 10, and everything works, however, the DPI/PixelRatio is too low. When building manually I can set the pixelratio, but how does one do this when using hover run/build?

**Comment by Drakirus** [comment]
Using hover you have to edit the file `./desktop/cmd/options.go ` to change the PixelRatio.
[wiki](https://github.com/go-flutter-desktop/go-flutter/wiki/Options)

Is that information what you were looking for?

**Comment by Drakirus** [comment]
#84

**Comment by alexelisenko** [comment]
@Drakirus Adding it to the options.go works, but on both Mac and Windows, whenever I set the pixelRatio, it does indeed change, but the UI becomes unresponsive.

This error appears in log, but this error is there even when not setting the pixel ratio:

```
[ERROR:c:\b\s\w\ir\k\src\flutter\shell\platform\embedder\embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
```
There is also this curious error:

```
flutter: ΓòÉΓòÉΓòí EXCEPTION CAUGHT BY RENDERING LIBRARY Γò₧ΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉ
```

**Comment by Drakirus** [comment]
@alexelisenko, this issue is in the process of been resolved. Please read : https://github.com/go-flutter-desktop/go-flutter/issues/84#issuecomment-506721457

**Comment by alexelisenko** [comment]
@Drakirus Just tested with the hotfix branch, it is working! Thanks you.

**Comment by Drakirus** [comment]
If I get the same positive feedback from @b0o, I'll merge the hotfix.
Closing the issue, follow the progress on #84

**Comment by Drakirus** [comment]
If I get the same positive feedback from @b0o, I'll merge the hotfix.
Closing the issue, follow the progress on #84
