### ISSUE TITLE
Wire up custom event loop interop

### ISSUE THREAD

**Issue by Drakirus** [go-flutter-desktop/go-flutter#175]
The flutter/engine GLFW implementation makes use of the [` custom_task_runners`](https://github.com/flutter/engine/blob/e7f8ca1de9f714596a17fa953fad6e1791c8ce38/shell/platform/embedder/embedder.h#L678-L681).  
The implementation is available here: https://github.com/flutter/engine/commit/4e344e6cd23b2195c544d53cbad410c71534704c  , it is just a matter of porting it to go-flutter.

The use of a custom event loop interop will resolve some delay experienced by plugin author https://github.com/go-flutter-desktop/go-flutter/issues/132#issuecomment-507070367 , and it will able us to have 'true' passive sleep. (instead of fetching platform message every 0.016 seconds even when there is no message available)

**Comment by davidmartos96** [comment]
Using PollEvents did the trick. Thanks for the information! Not quite a problem for the sqlite plugin at least, because it provides a way to execute operations in batches, without going back and forth from Dart and native. Useful to know none the less.

**Comment by Drakirus** [comment]
wip in: #215.
Try it out with `hover run -b "@feature/event-loop-interop"`

**Comment by Drakirus** [comment]
fix taged in tag: [v0.29.0](https://github.com/go-flutter-desktop/go-flutter/releases/tag/v0.29.0).

The delay of 30ms still occurs, there is currently no solution.
