### ISSUE TITLE
How to develop plugin.

### ISSUE THREAD

**Issue by CaiJingLong** [go-flutter-desktop/go-flutter#182]
For example, if I want to develop a plug-in locally, how should I do it?

If I developed a plug-in, such as returning a string in go language and displaying it in flutter, how should I import this plug-in?

----
Do you have any documents?

**Comment by CaiJingLong** [comment]
I find it in [website](https://hover.build/docs/create-a-plugin/).
I think should write the url in the README, because it's hard for me to find this.

I'll close the issue.

**Comment by Drakirus** [comment]
There is also a wiki page: https://github.com/go-flutter-desktop/go-flutter/wiki
