### ISSUE TITLE
Support system tray?

### ISSUE THREAD

**Issue by monkeyWie** [go-flutter-desktop/go-flutter#185]
For desktop applications, the system tray is very important.

**Comment by Drakirus** [comment]
go-flutter supports plugin [wiki how to make a plugin](https://github.com/go-flutter-desktop/go-flutter/wiki/Implement-a-plugin). 
To place an icon and menu in the notification area, the library [systray](https://github.com/getlantern/systray/) exist.

I'm not planing to support system tray plugin. 
But we will be pleased to get some help.
If you have implemented a plugin that you would like to share, feel free to open a PR on the [plugins](https://github.com/go-flutter-desktop/plugins) repository!

**Comment by monkeyWie** [comment]
Thank you, I will try to write this plugin.

**Comment by NetFly-VPN** [comment]
> Thank you, I will try to write this plugin.
hi, monkeyWie, 关于tray的插件怎么样啦, 我的项目中也需要一个这样的东东, 方便交流一下吗

**Comment by monkeyWie** [comment]
@NetFly-VPN 目前只写了个demo，功能是实现了，不过插件还不够成熟。

**Comment by Drakirus** [comment]
I've found this half done go-flutter implementation: https://github.com/firstmeetgames/go-flutter/blob/e7e447f8ee41a3571b171dc5ab6be75afc964037/systray.go
It's a good starting point if you want to make systray plugin.

**Comment by JanezStupar** [comment]
@monkeyWie how did it go for you? Have you made any progress?

**Comment by JanezStupar** [comment]
I made my own plugin: https://github.com/JanezStupar/flutter_systray
