### ISSUE TITLE
Have trouble to register plugin method handler with uncertain string, example is file_picker plugin use __CUSTOM_x

### ISSUE THREAD

**Issue by chunhunghan** [go-flutter-desktop/go-flutter#196]
Function Custom Format of Plugin file_picker https://github.com/miguelpruivo/plugins_flutter_file_picker
 pass a uncertain string and I have trouble to register method handler in InitPlugin
x is file type, such as txt, svg, doc, xls

    channel.HandleFunc("__CUSTOM_x", p.custom) 

File_Picker Dart

	static Future<dynamic> _getPath(String type, bool multipleSelection) async {
		try {
		  dynamic result = await _channel.invokeMethod(type, multipleSelection);
	...

	static String _handleType(FileType type, String fileExtension) {
		switch (type) {
		 ...
		  case FileType.CUSTOM:
			return '__CUSTOM_' + (fileExtension ?? '');
		  default:

File_Picker resolve file type in Android with string.split

	private String resolveType(String type) {

		final boolean isCustom = type.contains("__CUSTOM_");

		if(isCustom) {
		  final String extension = type.split("__CUSTOM_")[1].toLowerCase();
		  String mime = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension);
		  mime = mime == null ? "unsupported" : mime;
		  Log.i(TAG, "Custom file type: " + mime);
		  return mime;
		}

method-channel.go line 77,78

    // When no handler is registered for a method, it will be handled silently by
    // sending a nil reply which triggers the dart MissingPluginException exception.

Error Message

	go-flutter: no method handler registered for method '__CUSTOM_svg' on channel 'file_picker'
	flutter: [FilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method __CUSTOM_svg on channel file_picker)
	[ERROR:c:\b\s\w\ir\k\src\flutter\lib\ui\ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method __CUSTOM_svg on channel file_picker)

Thanks

**Comment by GeertJohan** [comment]
Having variables in a method name doesn't make sense. I have never seen it in another plugin. I think the file type should've been an argument. I don't feel like we should add much complexity to go-flutter, but a simple catch-all handler could let you implement the matching manually.

**Comment by Drakirus** [comment]
@chunhunghan, you can use:
```Golang
p.channel.CatchAllHandleFunc(fallBack)

func fallBack(methodCall interface{}) (reply interface{}, err error) {
	method := methodCall.(plugin.MethodCall)
	// return the randomized Method Name
	return method.Method, nil
}
```

The `CatchAllHandleFunc` functionality will be added to the next release of go-flutter.
If you want to try it out use: `hover run -b '@master'`.
