### ISSUE TITLE
Encounter error "interface {} is map[interface {}]interface {}, not map[string]interface {}" when develop Image_Picker for windows "pickVideo" 

### ISSUE THREAD

**Issue by chunhunghan** [go-flutter-desktop/go-flutter#204]
When develop Image_Picker Plugin for Windows.
pickImage work fine but pickVideo has the following error message
	
	go-flutter: recovered from panic while handling call for method 'pickVideo' on channel 'plugins.flutter.io/image_picker': interface conversion: interface {} is map[interface {}]interface {}, not map[string]interface {}
	goroutine 57 [running]:

Modify func handlePickVideo of plugin.go

    argsMap := arguments.(map[string]interface{})

to 

    argsMap := arguments.(map[interface{}]interface{})

can fix problem 

Thanks.

**Comment by Drakirus** [comment]
Thanks for the bug-report!
Fix available in `image_picker/v0.1.1`
