### ISSUE TITLE
plugin: SQLCool uses the current SQL plugin but adds change feed

### ISSUE THREAD

**Issue by joeblew99** [go-flutter-desktop/go-flutter#206]
https://github.com/synw/sqlcool

I think we can get this working on Desktop and mobiles.
It uses the existing go-flutter plugin called https://github.com/nealwon/go-flutter-plugin-sqlite, but adds Change Feeds

Why Change feed is a useful pattern ?
I use it to essentially hold all the Materialised Views for the Flutter GUI.
From the Server, events come in and the business logic then updates the database to the current materialised views and so the Views update automatically.

I think its worth trying to get it into an example. 

what do we think ?

**Comment by Drakirus** [comment]
From [what I can tell](https://github.com/synw/sqlcool/search?q=invokeMethod&type=Code), `synw/sqlcool` is a Dart only plugin wrapping [`tekartik/sqflite`](https://github.com/tekartik/sqflite).

We already have a desktop implementation of [`tekartik/sqflite`](https://github.com/tekartik/sqflite) => [`nealwon/go-flutter-plugin-sqlite`](https://github.com/nealwon/go-flutter-plugin-sqlite).

 The platform message between [`tekartik/sqflite`](https://github.com/tekartik/sqflite) and go-flutter are made.  
 The dart code of [`synw/sqlcool`](https://github.com/synw/sqlcool) can call [`tekartik/sqflite`](https://github.com/tekartik/sqflite) which will get response from [`nealwon/go-flutter-plugin-sqlite`](https://github.com/nealwon/go-flutter-plugin-sqlite), the dependency cycle is complete!

go-flutter already supports https://github.com/synw/sqlcool, all of the dependency (1) are available
