### ISSUE TITLE
Initial window location

### ISSUE THREAD

**Issue by jascodes** [go-flutter-desktop/go-flutter#211]
How do I set initial windows location?

**Comment by Drakirus** [comment]
Similar to https://github.com/go-flutter-desktop/go-flutter/issues/126, you can 'hack' a [GLFW-plugin](https://github.com/go-flutter-desktop/go-flutter/wiki/GLFW-Plugin-example).
But what would be better is a custom [`Option`](https://github.com/go-flutter-desktop/go-flutter/wiki/Options).

Can you submit a quick PR addressing the changes, it is very similar to: [#145](https://github.com/go-flutter-desktop/go-flutter/pull/145/files)

**Comment by Drakirus** [comment]
This might also help you: [Work on 'go-flutter' source code](https://github.com/go-flutter-desktop/go-flutter/wiki/Setting-up-hover-to-use-a-home-made-version-of-'go-flutter')

**Comment by Drakirus** [comment]
Fixed by https://github.com/go-flutter-desktop/go-flutter/commit/0a081107c1d7102e2311e75e6b90b7b941db615e
