### ISSUE TITLE
Possible to use webview in a go-flutter app?

### ISSUE THREAD

**Issue by MostHated** [go-flutter-desktop/go-flutter#212]
I was wondering if it's possible to use webview in a go-flutter app? I had tried but I was getting the following error:

```
flutter: Another exception was thrown: Unsupported operation: Trying to use the default webview implementation for TargetPlatform.fuchsia but there isn't a default one
```

I looked around and was able to technically find a [fuchsia_webview_plugin](https://github.com/fuchsia-rs/topaz-rs/tree/master/public/dart/fuchsia_webview_flutter), but I have yet to be able to get it to work because it required fidl_fuchsia_io and that starts getting into real fuchsia stuff, so I don't know if it's technically even possible to use that, or actually even necessary. Is there something else I am supposed to do that I am just not aware of to use webview? I figured that error came up because of having to use the below line in the main_desktop.dart.

```
debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;
```

Does anyone have any suggestions or recommendations?
Thanks,
-MH

**Comment by Drakirus** [comment]
>  it's possible to use webview in a go-flutter app?

There is no support of webview in go-flutter. And I don't think it's possible to implement such features without a major work-account. 

> Is there something else I am supposed to do that I am just not aware of to use webview?

https://github.com/go-flutter-desktop/plugins/tree/master/url_launcher


>  Does anyone have any suggestions or recommendations?

Use the plug-in mentioned above. To me, a full-fledged browser is far superior than a webview.

**Comment by MostHated** [comment]
I appreciate the reply. That url_launcher just opens an external browser, doesn't it? It doesn't allow you to display something within the actual application? Displaying a full browser is great for some things, but unfortunately, it is pretty much the opposite of what I was hoping to achieve. I was just wanting a few inline areas of my applications interface to be able to display a view of a page that is using apexcharts js plugins for different types of data without having to leave the application's interface, to start out.

I realize it would probably be more work than it would be worth, but purely out of interest, could there be any sort of way to perhaps incorporate something like this into a flutter application as perhaps some sort of overlay or just a blank area in which this gets displayed?
https://github.com/zserge/webview

I realize what I am hoping for just isn't really something that is possible currently, but I appreciate you taking the time to have replied.

Thanks,
-MH

**Comment by Drakirus** [comment]
> That url_launcher just opens an external browser, doesn't it?

Yes. 

> It doesn't allow you to display something within the actual application?

No. 

> I realize it would probably be more work than it would be worth, but purely out of interest, could there be any sort of way to perhaps incorporate something like this as perhaps some sort of overlay or just a blank area in which this gets displayed?

Well there is the texture plug-in, but that's not the intended use. https://github.com/go-flutter-desktop/examples/tree/feature/gl_texture/texture_tutorial

I honestly think that implementing a webview in go-flutter core or in a go-flutter plug-in is a Very bad idea for maintenance purposes.

Closing this issue because it's more a question than a request. (reopen if needed) 
The flutter embedding API is just not specific enough for such uses cases.
