### ISSUE TITLE
Chinese random code

### ISSUE THREAD

**Issue by aixi2494** [go-flutter-desktop/go-flutter#223]
![image](https://user-images.githubusercontent.com/15819365/62423704-79039a00-b6f6-11e9-90df-c6296354dade.png)

**Comment by Drakirus** [comment]
The default Roboto font doesn't seem to support chine alphabet.

Please switch to a font that supports Chinese characters.

**Comment by aixi2494** [comment]
Thank you
Changing Fonts is effective

**Comment by yougg** [comment]
hi @aixi2494 i have the same problem but change font was not working, can you share your font setting please, thanks.

![image](https://user-images.githubusercontent.com/1641020/73729628-59fec700-4770-11ea-9e65-6a6885ca1a23.png)
如图上的使用Ubuntu系统中的字体没有效果，只有使用资源中自定义的字体放才有效。
尝试了多个系统中的字体都不行。

**Comment by aixi2494** [comment]
可能你那个字体不支持中文,,你下载一个中文字体试着设置一下



在 2020-02-04 17:05:49，"yougg" <notifications@github.com> 写道：

hi @aixi2494 i have the same problem but change font was not working, can you share your font setting please, thanks.


如图上的使用Ubuntu系统中的字体没有效果，只有使用资源中自定义的字体放才有效。
尝试了多个系统中的字体都不行。

**Comment by yougg** [comment]
字体是支持中文的，我又试了几次找到问题了。
我的中文字体都是安装在用户目录中的，把字体复制到系统目录中就可以了

@pchampio my chinese fonts were installed into user path $HOME/.local/share/fonts/ not system font path /usr/share/fonts/, this is my record:

1. copy font to system path

```bash
sudo mkdir -p /usr/share/fonts/truetype/youyuan
sudo cp $HOME/.local/share/fonts/SIMYOU.TTF /usr/share/fonts/truetype/youyuan/
sudo chmod 644 /usr/share/fonts/truetype/youyuan/SIMYOU.TTF
```

2. change font setting in the code, it's not working
```
fontFamily: "YouYuan" // also SIMYOU was not working too
```

3. rename font file to `YouYuan.ttf`, also not working

4. link `YouYuan.ttf` to `youyuan.ttf` in the same dir, i don't know why but finally it is working.
![image](https://user-images.githubusercontent.com/1641020/74086062-3f06bc80-4aba-11ea-91e3-4d6aeee999e9.png)

tested with `ttc` and `otf` font file， both fonts were not working.
