### ISSUE TITLE
Any Future support for printer

### ISSUE THREAD

**Issue by maheshbhattaraai** [go-flutter-desktop/go-flutter#224]
This is not about any issue. 

> Any future support for thermal printer or there may any printer support with go flutter desktop.

If it support with printer and Excel file export import then it will be great resource for flutter desktop.
Thank You

**Comment by Drakirus** [comment]
As always.. You just have to write a plugin!
For more information about plugins, read our [wiki](https://github.com/go-flutter-desktop/go-flutter/wiki)

Golang supports ESC-POS thermal printer via [this library](https://github.com/seer-robotics/escpos).  
Golang supports Excel file export import  via [this library](https://github.com/360EntSecGroup-Skylar/excelize)

**Comment by 926** [comment]
I am curious to know if this plugin works on desktop :
https://pub.dev/packages/blue_thermal_printer

Never tried to bluetooth connect PC and thermal print, but it seems feasible :
https://printerssetup.org/how-to-configure-a-windows-7-pc-for-bluetooth-printing/

**Comment by pchampio** [comment]
Since it's the host that connects itself to the thermal printer, the golang code can fake been connection in Bluetooth to a TCP thermal printer.

> Golang supports ESC-POS thermal printer via this library.

**Comment by 926** [comment]
Hi @pchampio,
Thanks for making this clearer,
Please forgive my newbie question, but why not start with Dart plugin ?

**Comment by pchampio** [comment]
Since Dart as access to TCP sockets, it is actually better to do everything in Dart if your printer supports TCP printing.
