### ISSUE TITLE
TextInput error

### ISSUE THREAD

**Issue by zephylac** [go-flutter-desktop/go-flutter#225]
## Flutter version

```
Flutter 1.7.8+hotfix.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (2 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```

## Steps to Reproduce
Using MacOS I tried to delete input text using `cmd ⌘` + `backspace``

go-flutter: handler for method 'TextInput.setEditingState' on channel 'flutter/textinput' returned an error: text editing state BUG, text selection isn't possible: selectionBase:-1, selectionExtent:-1. Please open a issue on flutter/flutter

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, text editing state BUG, text selection isn't possible: selectionBase:-1, selectionExtent:-1. Please open a issue on flutter/flutter
, null)

**Comment by Drakirus** [comment]
I 'fixed' the issue yesterday: https://github.com/go-flutter-desktop/go-flutter/issues/221
