### ISSUE TITLE
Remove main_desktop.dart

### ISSUE THREAD

**Issue by jld3103** [go-flutter-desktop/go-flutter#229]
The main_desktop.dart is not really needed.
I do the debug default target platform override also on mobile and it doesn't do anything bad or unexpected.

# Proposal
If no main_desktop.dart file is found, use the main.dart file as target.

**Comment by jld3103** [comment]
The main problem I have is, that Flutter for web compiles all main*.dart files. As the main_desktop.dart file is not necessary for go-flutter, we could just remove it.

**Comment by Drakirus** [comment]
You can use the `--target` if you want to have a single entry-point (main.dart).
```logs
Flags:
-t, --target string:  The main entry-point file of the application. (default "lib/main_desktop.dart")
```
`hover build --target=lib/main.dart` - `hover run --target=lib/main.dart`

As to remove the `main_desktop.dart` file, we might remove it in once desktops are 'official' target platform. 
At the moment, having different entry-points for desktop and mobile is the best way to keep a consistent experience, without involving too much overhead.   

I've heard peoples liking the separation, your the first one to complain about having 2 entry-points.
Closing the issue as `--target=lib/main.dart` fixes your problem.

**Comment by jld3103** [comment]
No I think main_desktop.dart can stay, but we could just use main.dart if no main_desktop.dart is provided.

**Comment by Drakirus** [comment]
> No I think main_desktop.dart can stay, but we could just use main.dart if no main_desktop.dart is provided.

After giving this a quick though, I don't like to add 'magic'. There is a flag to change the entry-point, adding another way to change it could be possible, but it should say consistent.
What you are proposing is to change the entry-point through a `Convention` knowing that
there is already a `Configuration` that do the change.
The existing `Convention` ("lib/main_desktop.dart") should stay simple, adding complexity here isn't needed.

**Comment by jld3103** [comment]
That would be great!
