### ISSUE TITLE
Blank Screen When Executing Async Method at Startup

### ISSUE THREAD

**Issue by ekasetiawans** [go-flutter-desktop/go-flutter#230]
how to reproduce,
change main method on main_desktop.dart with async
call an async method using await before runApp() , for exampe load SharedPreference.

run application using hover run and dont touch mouse or keyboard anymore, the application show blank screen until you move mouse inside application window or typing button on keyboard.

**Comment by Drakirus** [comment]
can you try `hover run -b 'beta'`. (You might need to be on `flutter channel master`)

**Comment by ekasetiawans** [comment]
There is no -b flags on my hover.

Here is my flutter doctor :

poetra@warmachine:/media/poetra/SSD/Project/Mobile/TSPMProduction/tspm_production$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.8.5-pre.130, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!
poetra@warmachine:/media/poetra/SSD/Project/Mobile/TSPMProduction/tspm_production$ hover run -b
Error: flag needs an argument: 'b' in -b
Usage:
  hover run [flags]

Flags:
      --cache-path string   The path that hover uses to cache dependencies such as the Flutter engine .so/.dll (defaults to the standard user cache directory)
  -h, --help                help for run
  -m, --manifest string     Flutter manifest file of the application. (default "pubspec.yaml")
  -t, --target string       The main entry-point file of the application. (default "lib/main_desktop.dart")

hover: command failed: flag needs an argument: 'b' in -b
poetra@warmachine:/media/poetra/SSD/Project/Mobile/TSPMProduction/tspm_production$

**Comment by ekasetiawans** [comment]
oh I forgot to add '@beta' on hover run -b command

**Comment by ekasetiawans** [comment]
UPDATE. Running with beta branch solve this issue. Thanks @Drakirus

**Comment by Drakirus** [comment]
fix taged in tag: [v0.29.0](https://github.com/go-flutter-desktop/go-flutter/releases/tag/v0.29.0)
