### ISSUE TITLE
[Windows] Error on minimization

### ISSUE THREAD

**Issue by Tokenyet** [go-flutter-desktop/go-flutter#234]
```
Flutter 1.7.4 • channel unknown • unknown source
Framework • revision dfecafa4ab (9 weeks ago) • 2019-06-14 09:46:23 -0700
Engine • revision 2589785b5c
Tools • Dart 2.4.0
```

## Golang errors (Optional)
```
go-flutter: Cannot calculate pixelsPerScreenCoordinate for zero-width window.
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: Leading widget consumes entire tile width. Please use a sized widget.
flutter: 'package:flutter/src/material/list_tile.dart':
flutter: Failed assertion: line 1334 pos 7: 'tileWidth != leadingSize.width'
flutter:
```

## Steps to Reproduce
1. Add a list tile in any flutter example.
2. Minimize window
3. Look the logging, must show an errors as above.

I used `pointer_demo`, I only added one line in the bottom of Column.
```
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Text('You have pointed at this box this many times:'),
                  Text(
                    '$_enterCounter Entries\n$_exitCounter Exits',
                    style: Theme.of(context).textTheme.display1,
                  ),
                  Text(
                    'The cursor is here: (${x.toStringAsFixed(2)}, ${y.toStringAsFixed(2)})',
                  ),
                  ListTile( // Here!
                    title: Text("hi"),
                  )
                ],
              ),
```

It looks no problem when there isn't enough complicated. But in my other app, this cause refresh on homepage, and let `PageView` always go to the first page.

```
                        child: PageView(
                          physics:new NeverScrollableScrollPhysics(),
                          controller: _pageController,
                          children: <Widget>[
                            APage(),
                            Container(),
                            BPage),
                            Container(),
                            Container(),
                          ],
                        )
```

But all the logs showed about `ListTile` (as above), so I think It's not directly relative to `PageView`.

**Edit:**
`PageView` is still a problem on Minimization, I test It by replacing code in _app.dart_, still using the same project `pointer_demo`.

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Hover Example'),
      ),
      body: PageView(
        controller: controller,
        children: <Widget>[
          Container(color: Colors.red,),
          Container(color: Colors.blue,),
          Container(color: Colors.green,),
        ],
      ),
    );
  }
```

Scroll to Blue page and minimize, and the page go back to Red page when recovering windows. There is only one line errors:

`go-flutter: Cannot calculate pixelsPerScreenCoordinate for zero-width window.`

By the way, I'm not sure If this is hard to fix, but maybe we could have a *window mode* without *minimize* button to be a quick workaround?

**Comment by Drakirus** [comment]
> By the way, I'm not sure If this is hard to fix, but maybe we could have a window mode without minimize button to be a quick workaround?

This isn't possible using glfw, we cannot add such option.

---

About your main issue, I think it appears because we are notifying the engine of an very small screen size.

@Tokenyet can you reproduce following error by resizing down the window ? 
```log
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: Leading widget consumes entire tile width. Please use a sized widget.
flutter: 'package:flutter/src/material/list_tile.dart':
flutter: Failed assertion: line 1334 pos 7: 'tileWidth != leadingSize.width'
flutter:
```

About 
```log
go-flutter: Cannot calculate pixelsPerScreenCoordinate for zero-width window.
[above flutter exception......]
```

@GeertJohan When [this](https://github.com/go-flutter-desktop/go-flutter/blob/19ec300ac7e16fc0e4b0bc4d976a646136c5f404/glfw.go#L195) line gets called, should we still send a [`WindowMetricsEvent`](https://github.com/go-flutter-desktop/go-flutter/blob/19ec300ac7e16fc0e4b0bc4d976a646136c5f404/glfw.go#L268)?

**Comment by Tokenyet** [comment]
Thanks for quick reqsponse! I cannot reproduce the issue when resizing down, only minimize would cause the issue. Currently, I'm using my tricky solution to solve these problems, share here, but don't be serious to this workaround.

To listen on **resume**, I use `SystemChannels.lifecycle` and `addPostFrameCallback` to tricky update when resuming. To prevent widget(PageView) in `Build` function from lossing state, and I checked `widget != null` to stop `setState` to refresh, but using `StreamController` to update If there is actual needed. But this is too tricky, so just take a quick glance 😓

**Comment by Drakirus** [comment]
Does `hover run -b '@fix/flutter-error-on-minimization'` fixes the issue?

**Comment by Tokenyet** [comment]
This solved my minimal test project! I think this is fixed. If I found out more complex case that would certainly break on minimization, could I reply here? or I make a new issue? 

Thanks for sloving this issue 😆

**Comment by Drakirus** [comment]
tagged into: [`v0.28.0`](https://github.com/go-flutter-desktop/go-flutter/commit/4bb040b53aa1ba6b4e50943193af93ea8f9f524f).

>  If I found out more complex case that would certainly break on minimization, could I reply here? or I make a new issue?

Please open, it's better!
