### ISSUE TITLE
Can we close app manually??

### ISSUE THREAD

**Issue by maheshbhattaraai** [go-flutter-desktop/go-flutter#236]
## Flutter version

```
Flutter 1.8.2 • channel master • https://github.com/flutter/flutter.git
Framework • revision xxxxxxxxxx (x weeks ago) • xxxxxxxxxxxxxxxxxxxxxxxx
Engine • revision xxxxxxxxxx
Tools • Dart 2.x.x (build xxxxxxxxxx)
```
It is not an issue. If we want to close app manually in flutter like navigator.pop how can we achieve in go flutter. Thanks Regards.

**Comment by Drakirus** [comment]
[`flutter.PopBehavior(flutter.PopBehaviorClose)`](https://github.com/go-flutter-desktop/go-flutter/wiki/Options)
