### ISSUE TITLE
How can we find specific applications sqlite file. 

### ISSUE THREAD

**Issue by maheshbhattaraai** [go-flutter-desktop/go-flutter#237]
`If we want to remigrate then how can we do that. How Can we find this database?`

**Comment by Drakirus** [comment]
I'm sorry, I don't understand your issue. Can you please add some additional info/context?

**Comment by Drakirus** [comment]
Closing since it's a cross-post of https://github.com/nealwon/go-flutter-plugin-sqlite/issues/5.
Please use the plugin issue tracker!
