### ISSUE TITLE
released software not run in windows

### ISSUE THREAD

**Issue by maheshbhattaraai** [go-flutter-desktop/go-flutter#249]
> After run hover build software not run in PC. Only run in those machine  in which flutter is installed.

**Comment by Drakirus** [comment]
@maheshbhattaraai I'm not understanding your issue.

From what I understood:
You have 2 PC. 
On one of them you are building the flutter app using: `hover build`.
You ship the content of `go/build/outputs/...` to the second PC.  
On the second PC you run compiled desktop app.
You get an error on the second PC.

Could you please share with us the content of the terminal output?
Could you share the OSs on which you have compiled and have run your app?
Could you assert that the second PC can run OpenGL application?
Please share with us any more information!

**Comment by maheshbhattaraai** [comment]
There is no any specific issue showing in machine. It perfectly works in flutter installed machine . But not running on the PC which does not have flutter and go. Basically i want to release the desktop app for production environment.

**Comment by Drakirus** [comment]
Please tell me the production environment OS and architecture.

**Comment by maheshbhattaraai** [comment]
windows OS with 64 bit operating system and x64-based processor.

**Comment by Drakirus** [comment]
ok, good, go-flutter is only compatible with 64bit.
Can you share the content of the terminal output of the production PC?
