### ISSUE TITLE
undefined reference to `FlutterPlatformMessageReleaseResponseHandle'

### ISSUE THREAD

**Issue by ccforgit** [go-flutter-desktop/go-flutter#250]
## Flutter version

```
Flutter x.xx.x • channel beta • https://github.com/flutter/flutter.git
Framework • revision xxxxxxxxxx (x weeks ago) • xxxxxxxxxxxxxxxxxxxxxxxx
Engine • revision xxxxxxxxxx
Tools • Dart x.x.x (build xxxxxxxxxx)
```

## Golang errors (Optional)

```
Golang's compiling errors
```

## Steps to Reproduce

1. xxx
2. xxx
3. xxx

**Comment by ccforgit** [comment]
hover: Using engine from cache
hover: Cleaning the build directory
hover: ⚠⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠⚠     It's advised to use the beta channel. ($ flutter channel beta)
hover: Bundling flutter app
hover: Checking available release on Github
hover: Compiling 'go-flutter' and plugins
# github.com/go-flutter-desktop/go-flutter/embedder
C:\Users\chencai.cc\AppData\Local\Temp\go-build163909302\b040\_x003.o: In function `_cgo_84ad20d147fe_Cfunc_FlutterPlatformMessageReleaseResponseHandle':
/tmp/go-build/cgo-gcc-prolog:252: undefined reference to `FlutterPlatformMessageReleaseResponseHandle'
C:\Users\chencai.cc\AppData\Local\Temp\go-build163909302\b040\_x005.o: In function `createMessageResponseHandle':
D:\gopath\go\pkg\mod\github.com\go-flutter-desktop\go-flutter@v0.29.0\embedder/embedder_helper.c:72: undefined reference to `FlutterPlatformMessageCreateRespon
seHandle'
collect2.exe: error: ld returned 1 exit status
hover: Go build failed: exit status 2

**Comment by ccforgit** [comment]
hover: Using engine from cache
hover: Cleaning the build directory
hover: ⚠⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠⚠     It's advised to use the beta channel. ($ flutter channel beta)
hover: Bundling flutter app
hover: Checking available release on Github
hover: Compiling 'go-flutter' and plugins
# github.com/go-flutter-desktop/go-flutter/embedder
C:\Users\xxxx\AppData\Local\Temp\go-build163909302\b040\_x003.o: In function `_cgo_84ad20d147fe_Cfunc_FlutterPlatformMessageReleaseResponseHandle':
/tmp/go-build/cgo-gcc-prolog:252: undefined reference to `FlutterPlatformMessageReleaseResponseHandle'
C:\Users\xxxx\AppData\Local\Temp\go-build163909302\b040\_x005.o: In function `createMessageResponseHandle':
D:\gopath\go\pkg\mod\github.com\go-flutter-desktop\go-flutter@v0.29.0\embedder/embedder_helper.c:72: undefined reference to `FlutterPlatformMessageCreateRespon
seHandle'
collect2.exe: error: ld returned 1 exit status
hover: Go build failed: exit status 2

**Comment by Drakirus** [comment]
FYI: Updating the beta channel the the latest version solved this issue.

**Comment by Drakirus** [comment]
duplicate of  #247
