### ISSUE TITLE
hover run go-gl/glfw invalid pseudo-version

### ISSUE THREAD

**Issue by ykmnkmi** [go-flutter-desktop/go-flutter#251]
windows 10 x64, go1.13, fluter beta v1.9.1+hotfix.1
gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0

hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
hover: Compiling 'go-flutter' and plugins
go: github.com/go-flutter-desktop/go-flutter@v0.29.0 requires
  github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1: invalid pseudo-version: does not match version-control timestamp (2019-04-09T00:40:39Z)
hover: Go build failed: exit status 1

**Comment by ykmnkmi** [comment]
ubuntu 19.04 go1.13 too

**Comment by thebf** [comment]
Windows 10 with all the latest updates and go 1.13 here as well.

**Comment by Drakirus** [comment]
see: https://tip.golang.org/doc/go1.13#version-validation

> The date string must match the UTC timestamp of the revision.

I'm updating go-flutter to be compatible with go1.13.

**Comment by Drakirus** [comment]
@ykmnkmi, @thebf the issue should be fixed in `'v0.29.2'` can you `hover update` and check if the issue is really resolved?

**Comment by thebf** [comment]
Remoting into my work desktop right now to check

**Comment by thebf** [comment]
Seems like it worked. I got to the point of getting a new type of error when bootstrapping.

The Url launcher plugin likely needs the same treatment as adding that plugin produced the same error again.

**Comment by ykmnkmi** [comment]
Gets #248 
When try with hover run -b '@gl-3.3' throws this error (texture-example too)

**Comment by Drakirus** [comment]
branch `gl-3.3` was rebased with master
