### ISSUE TITLE
Flutter AOT

### ISSUE THREAD

**Issue by pchampio** [go-flutter-desktop/go-flutter#259]
The current `hover build XX` produce a JIT flutter application (with `disable-dart-asserts` and `disable-observatory`).

Flutter Desktop (from Google) has support for AOT on MacOS https://github.com/flutter/flutter/pull/38909, the others platforms will follow https://github.com/flutter/flutter/issues/38477, and https://github.com/flutter/flutter/issues/38478. 

From a go-flutter point of view, adding support for AOT requires:
 - compiling the flutter application to AOT, ([`AOTSnapshotter`](https://github.com/flutter/flutter/blob/1bb8468a31b2b5ba579ab143ea3f5ed5f9464d9a/packages/flutter_tools/lib/src/build_system/targets/macos.dart#L251-L259) & [WIKI: building-the-aot-snapshot](https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedding-in-AOT-Mode#building-the-aot-snapshot))
- getting a engine shared lib for AOT. We are currently downloading a JIT engine from the Google's build-bot [source](https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders), IFAIK they aren't providing pre-compiled AOT engines. (possible to build it by ourselves) 
- Change the engine start function to provide AOT blobs instead of the JIT ones ([go-flutter `FlutterProjectArgs`](https://github.com/go-flutter-desktop/go-flutter/blob/14d711486e19be6f7995cba56bd301e1db6a4840/embedder/embedder.go#L133-L136) & [embedder.h](https://github.com/go-flutter-desktop/go-flutter/blob/14d711486e19be6f7995cba56bd301e1db6a4840/embedder/embedder.h#L612-L639)). 

### AOT Status:
 - [x] Linux (Tested #331 and go-flutter-desktop/hover#77)
 - [ ] Windows
 - [ ] Mac

**Comment by jld3103** [comment]
Does this improve startup times?

**Comment by Drakirus** [comment]
It Will improve startup time and memory consumption.

Regarding app's speed and responsiveness, desktop are powerful enough to run the JIT app, only small improvement is to be expected in that domain.

**Comment by jld3103** [comment]
I experimented a lot with AOT today and this is what I came up with:
1. Compile the engine for linux, darwin and windows using CI
2. Download the necessary files from the CI artifacts using hover (`dart, frontend_server.dart.snapshot, flutter_patched_sdk, gen_snapshot`)
3. Build the AOT snapshot using the CI generated binaries
4. Wrap go-flutter around

Have you any other ideas? @pchampio @GeertJohan

**Comment by pchampio** [comment]
Before going down the CI route, I would like to ask the flutter team if they are willing to add the AOT engine to their build-bot.

From the user perspective, I personally always look the source of pre-build software I install on my machine.
In this context, having the source of the engine build by the official flutter team instead of some 'random' dudes is much more robust.

From point 2, are the `gen_snapshot` and co not already available?

Point 3 and 4 are spot on.

**Comment by jld3103** [comment]
I don't think gen_snapshot available

**Comment by jld3103** [comment]
Just for reference: Work is going on at https://github.com/go-flutter-desktop/go-flutter/pull/331 and https://github.com/go-flutter-desktop/hover/pull/77
@pchampio Could you update the list of platforms that work to state linux as working?
FYI Windows and Mac should work, but haven't been tested yet.

**Comment by pchampio** [comment]
Please read https://github.com/flutter/flutter/issues/50778

**Comment by pchampio** [comment]
As described by chinmaygarde
> As mentioned in the documentation, the command line args are meant to only access [unstable features](https://github.com/flutter/engine/blob/2b07b71ad01456308e152d19121c024e6aef97fe/shell/platform/embedder/embedder.h#L847) and the flags themselves are not guaranteed to stay consistent. The [4 pointers to the isolate and instructions](https://github.com/flutter/engine/blob/2b07b71ad01456308e152d19121c024e6aef97fe/shell/platform/embedder/embedder.h#L1469) mappings on the other hand are stable. You may dlopen and dlsym the same from this `libapp.so`.
> 
> It is entirely reasonable that you think that this is too complicated in lieu of just accessing features via a unstable interface. In that case, we can expose another field in the `FlutterProjectArgs` that exposes a placeholder for callers to specify a library containing the 4 asset blobs.

While we could wait for #50778 in golang we can already leverage this:

[ELF.zip](https://github.com/go-flutter-desktop/hover/files/4579860/ELF.zip)

First draft of ELF loading in Golang
```
❯ go run test
vmSnapshotData: size: 23672, pointer: 2285568
vmSnapshotInstructions: size: 12912, pointer: 8192
isolateSnapshotData: size: 1433288, pointer: 2310144
isolateSnapshotInstructions: size: 2258448, pointer: 24576
```

Golang version of:
https://github.com/jwinarske/flutter_wayland/pull/1/files
https://github.com/flutter-rs/flutter-rs/commit/307bf7824bcdbc694de08d0b53db344e19cea1a5

We need to revert #331

**Comment by pchampio** [comment]
https://flutter-review.googlesource.com/c/recipes/+/2901
https://flutter-review.googlesource.com/c/recipes/+/2901

**Comment by jld3103** [comment]
Great. I've been waiting for it

**Comment by pchampio** [comment]
This isn't the AOT compiled engine that we are needing, this is the GLFW shell proposed by flutter.
I just wanted to post this here because we might be able to send a PR in this repo. The goal would to upload an AOT compiled engine.
