### ISSUE TITLE
hover: init-plugin scaffolding

### ISSUE THREAD

**Issue by joeblew99** [go-flutter-desktop/go-flutter#260]
I was thinking about the idea of generating the code for golang plugins.

I see 2 use cases:

1. Your making plugins that use golang on mobile and Flutter.
- this is common where your building a large application and need to use lots of golang libs and treat the Dart layer as just a GUI layer. 
- Also common when your using a custom network transport or something.
- Could actually use protobufs as the IDL.

2. You are using a plugin for Mobile, and want to code gen the scaffolding code for the go-flutter plugin.

**Comment by Drakirus** [comment]
Relatedly, there have been general conversations several times in the past about a `hover init-plugin` command that will generate the go-flutter plugin scaffolding. Such enhancement are usually discuss in your [gitter channel](https://gitter.im/go-flutter-desktop/go-flutter).

Regarding `plugins that use golang on mobile and Flutter` let me be real clear here: Even tho through dart:ffi, go-flutter plugin could get ported to mobile, **we aren't planing on working on that feature**. Please stop been pushy about this, there is already #58.

**Comment by joeblew99** [comment]
hey @Drakirus 

Maybe there is a misunderstanding here or maybe yes i am just being pushy :)

I am suggesting that since plugins are being written in golang for go-flutter then we can also gen the same plugin code for IOS and Android that supports running the same golang plugin code.

This is being used quite a bit.
https://github.com/vocdoni/go-dvote is just one example.

dvote is a pretty good example where they have a ton of golang code that they need runnung underneath flutter because they are doing something innovative in that they use a different network transport that is not supported in flutter.
There are many other examples of this going on.

About Dart FFI. That is something that i only suggested as a thing that could be looked at later as an optimisation.  For most users that are using golang in the way dvote uses it having the inefficiency of passing through java and swift layers is fine because its network calls mostly.
