### ISSUE TITLE
Can't run on Windows 7

### ISSUE THREAD

**Issue by ertugazi91** [go-flutter-desktop/go-flutter#262]
Which dependencies should I install to run Windows build on Windows 7 or does it even supported? Kinda beginner here so some advice would be really helpful

**Comment by Drakirus** [comment]
Please read: https://github.com/go-flutter-desktop/hover/blob/master/README.md#install

**Comment by Drakirus** [comment]
Windows is supported. As the go-flutter says:
> using a single code base that runs on Windows, MacOS, and Linux..

**Comment by Drakirus** [comment]
Closing this issue, RTFM.

If you ran into errors when installing hover (which can happen) please open an issue. 

If you need advice, use our gitter.im chat, https://gitter.im/go-flutter-desktop/go-flutter
I like to keep only keep issues in the github.com issue tracker. Others proposition/advice/helps can be exposed in the chat.
