### ISSUE TITLE
Add color and more formatting to log ouput

### ISSUE THREAD

**Issue by jld3103** [go-flutter-desktop/go-flutter#263]
The log output from hover is somewhat unstructured and doesn't highlight the important information at all.

**Comment by Drakirus** [comment]
I find the log output fine enough 😊, it might be because I'm used to it.
Either way, I'll like to have a nicer implementation.
Can I assign you to this task?

**Comment by jld3103** [comment]
I'm already working on it and mostly finished :)

**Comment by Drakirus** [comment]
fixed by: https://github.com/go-flutter-desktop/hover/pull/26
@jld3103 thanks a lot!
