### ISSUE TITLE
Q: Why not allow go build

### ISSUE THREAD

**Issue by jascodes** [go-flutter-desktop/go-flutter#268]
I there reason you guys setup go-flutter like this. Why can't it be independant go project with help hover cli?

Am I mission somthing?

Thx

**Comment by Drakirus** [comment]
Before the `hover` era, and even before the project was moved into a github organization, I used to provide those information in the readme: (now in a wiki:) https://github.com/go-flutter-desktop/go-flutter/wiki/Manual-install-and-usage  

Yes, you are missing something, and the thing is **the flutter engine**.

The flutter engine is precompiled by google, we download it in the shape of a share lib and link go-flutter against it.

Building such package by hand isn't easy here are some of the steps we go through when we create your app:
 - get the current commit id of your flutter toolkit
 - get the corresponding flutter engine (and cache it) 
 - build your flutter application in a very specific way (`flutter build bundle`). This creates a JIT flutter app.
 - Generate the golang bodyplate code ([example](https://github.com/go-flutter-desktop/examples/tree/master/draggable_borderless/go) you need to see this as in the same way you need a android and ios applications template)
 - build the golang embedder (multiple way of building it as there is multiple way to run the app (same as `flutter run` & `flutter build`))
 - in case of `hover run` parse the output of the binary to get the observer URI.
 - from that observer URI, attach the `flutter attach` command to get hot-reload and debug info
 - At first I didn't think hover did that much, and I am getting tired of typing, just gona stop here..
