### ISSUE TITLE
New Plugin: FileChooser plugin

### ISSUE THREAD

**Issue by joeblew99** [go-flutter-desktop/go-flutter#269]
I need to be able to let the user choose a file.

Here is a basic example:
https://github.com/google/flutter-desktop-embedding/blob/master/testbed/lib/main.dart#L25

Here is a more complex example:
https://github.com/authpass/macos_secure_bookmarks/blob/master/README.md

This golang package seems to do what is needed on all desktops.
https://github.com/sqweek/dialog

**Comment by Drakirus** [comment]
![image](https://user-images.githubusercontent.com/7476655/65631420-c7873380-dfd7-11e9-9d7d-382fc3f0ad0d.png)
https://github.com/go-flutter-desktop/plugins

**Comment by joeblew99** [comment]
@Drakirus thanks - missed that :)
