### ISSUE TITLE
Hover bug

### ISSUE THREAD

**Issue by Drakirus** [go-flutter-desktop/go-flutter#271]
https://github.com/go-flutter-desktop/hover/pull/26 introduced a bug.

```log
$ hover
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x4fc1a8]

goroutine 1 [running]:
github.com/go-flutter-desktop/hover/internal/log.hoverPrint()
        /tmp/hover/internal/log/log.go:36 +0x28
github.com/go-flutter-desktop/hover/internal/log.Errorf(0x9fbe7b, 0x6b, 0xc000255d10, 0x1, 0x1)
        /tmp/hover/internal/log/log.go:19 +0x26
github.com/go-flutter-desktop/hover/cmd.initBinaries()
        /tmp/hover/cmd/common.go:50 +0x128
github.com/spf13/cobra.(*Command).preRun(0xe259c0)
        /home/drakirus/lab/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:856 +0x49
github.com/spf13/cobra.(*Command).execute(0xe259c0, 0xc0000201d0, 0x0, 0x0, 0xe259c0, 0xc0000201d0)
        /home/drakirus/lab/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:792 +0x145
github.com/spf13/cobra.(*Command).ExecuteC(0xe259c0, 0xc000255f50, 0x40733f, 0xc00002a118)
        /home/drakirus/lab/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/drakirus/lab/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/go-flutter-desktop/hover/cmd.Execute()
        /tmp/hover/cmd/root.go:44 +0x31
main.main()
        /tmp/hover/main.go:8 +0x20
```

When using `github.com/spf13/cobra` we make extensible uses of the golang `init()` function to create our commands.
When a package contains mutiples `init()` functions, the order of execution is based by the alphabetical order of the filename.

In the above case, the error occurs when the `init()` function of `cmd/common.go` (executed after assets.go and build.go) checks for `initBinaries()`.
If a `log.Errorf` is trigger, a call to `internal/log/log.go` is made and the `hoverPrint()` function fails because `Au` is equal to `nil`.

The `Au` value is set by the `cmd/root.go` `init()` function.

Order of execution:
`cmd/common.go` -> `init()` fails
`internal/log/log.go` -> `Au` still equals `nil` -> panic
`cmd/root.go` -> `init()` still not run..

@GeertJohan and I both reviewed the PR, and didn't saw this bug^^

**Comment by joeblew99** [comment]
How did you work out this is wha the bug is ?
