### ISSUE TITLE
WindowMode Configuration

### ISSUE THREAD

**Issue by ekasetiawans** [go-flutter-desktop/go-flutter#273]
I want to add window mode configuration that allow user to select fullscreen mode or default mode.
I save the configuration in .json file then I want to load that file on application start and passing value to `options` variable. But, I have problem to achieve it, because I can't create func that returning flutter.windowMode.

**Comment by ekasetiawans** [comment]
I want something like this

```
var options = []flutter.Option{
flutter.WindowMode(getWindowModeFromConfig()),
...
}

func getWindowModeFromConfig(){
// reading .json file then returning flutter.windowMode depended by .json value
}
```

**Comment by ekasetiawans** [comment]
Solved

I using `flutter.Option` as return type for getWindowModeFromConfig function instead of flutter.windowMode

**Comment by Drakirus** [comment]
@ekasetiawans can you share the code?

**Comment by ekasetiawans** [comment]
yes, this is the code

https://github.com/ekasetiawans/go-flutter-json-config
