### ISSUE TITLE
Open Virtual Keyboard / On-Screen Keyboard (OSK)

### ISSUE THREAD

**Issue by ekasetiawans** [go-flutter-desktop/go-flutter#274]
Does application will show virtual keyboard automatically on touch screen computer that dont have phisical keyboard?

Or, how to catch open keyboard request? I'll trying to open virtual keyboard manually.

**Comment by Drakirus** [comment]
### go-flutter side
Currently, nothing is done on the go-flutter side when the engine sends `show` and `hide` keyboards events. 

https://github.com/go-flutter-desktop/go-flutter/blob/87e0b2f8baaa5461bb4d09fb67781123ad133de8/textinput.go#L54-L56

In the future, those events coming form the internal  `flutter/textinput` MethodChannel could be expose to end-developers through [`Options`](https://github.com/go-flutter-desktop/go-flutter/wiki/Options) hooks.
The golang code quite straightforward to write, I'll leave this issue open for first-time contributor!

--- 
### end dev side (hover users)
After a bit on googleing, the windows exe to open the on-screen keyboard seems to be `Tabtip.exe`.
For now, I don't want to add this functionality into the go-flutter code, I'll be much better if those special use cases are handled by hover users. Nonetheless, a quick and temporary [Tips-and-tricks](https://github.com/go-flutter-desktop/go-flutter/wiki/Tips-and-tricks) section can be written.

**Comment by Drakirus** [comment]
https://github.com/go-flutter-desktop/go-flutter/wiki/Tips-and-tricks#3-open-the-virtual-keyboard-on-text-edit

For windows, it's up to you to adapt the code.

**Comment by ekasetiawans** [comment]
woow, thanks @Drakirus

**Comment by ekasetiawans** [comment]
I create this for showing windows virtual keyboard.

[https://gist.github.com/ekasetiawans/dfc31125d862fa69abdc977bad6223d1](url)

**Comment by ekasetiawans** [comment]
I have try 
`exec.Command("osk")` or `exec.Command("tabtip.exe")` but not working.

**Comment by Drakirus** [comment]
I do not run on windows so I can't help you.
If it is not possible to open the virtual keyboard in go, maybe try to craft a .bat file that opens the virtual keyboard, and call it from go?

**Comment by ekasetiawans** [comment]
@Drakirus , yes it's not possible to open the virtual keyboard in go. I got `the requested operation requires elevation`. But, now I have solution. I use user32.dll to showing virtual keyboard from tray icon. But this only works on windows 10 and you have to show touch screen keyboard on tray icon.

[This is the link](https://gist.github.com/ekasetiawans/dfc31125d862fa69abdc977bad6223d1)

Maybe someone can review my work.

**Comment by Drakirus** [comment]
Thanks for sharing.
