### ISSUE TITLE
[Hover] Feature: Support/Document setting initialRoute similar to `--route`

### ISSUE THREAD

**Issue by devkabiir** [go-flutter-desktop/go-flutter#276]
When running apps on android flutter supports passing `--route` argument and sets that as the initial route. This is currently not possible for iOS.

However during testing/debugging, it's more productive to directly launch the app in the correct route. Can this be supported?
Example use
`hover run --route="/post/5/edit"`

**Comment by Drakirus** [comment]
Not duplicate nor related, but it does overlaps #240.

More information is available in https://github.com/go-flutter-desktop/go-flutter/issues/240#issuecomment-529126934.

To implement this feature, it is likely that we will need to write a custom plugin that calls the 'flutter/navigation' Method channel. 

I don't know how do design this into hover as this plugin should only be loaded when using `hover run`. I've looked at the flutter source code, I couldn't find how they implemented flag.

**Comment by Drakirus** [comment]
The cleanest way might simply be to add another [Options](https://github.com/go-flutter-desktop/go-flutter/wiki/Options) into go-flutter that calls the `InvokeMethod` on initialization.
The path of the route could be set using `hover` by injecting a build-time variable with Golang CC.

**Comment by Drakirus** [comment]
@devkabiir you can test #288 by running:
`env GOFLUTTER_ROUTE="/post/5/edit" hover run -b '@feature/initial-route'`

**Comment by Drakirus** [comment]
PR for the hover flag done.

**Comment by devkabiir** [comment]
Thanks @Drakirus!, While using a env variable is a good way, they are handled differently based on the host process. So for example, if the host process escapes `"` quotes and my route contains quotes, it will always provide incorrect route to flutter. Or for example if my route contains `$` (special meaning in many shells) it will either be escaped or it will be processed by the host process/shell. I think using the env variable is a good start. It works for simple routes very well. But we will definitely need a better way.

Please consider exposing the functionality to set initialRoute in a more general purpose way. An example usage will be, `my-app://token:123/?confirm_login`, myapp can register a special url schema `my-app://` and anything on the host OS can launch my app. This might require setting the initialRoute programmatically. And this will also require the already running myapp to intercept the `my-app://` url and propely switch the route using `pushRoute` or something similar. (Maybe this should be a separate plugin, what do you think?)

Your initial implementation for setting initialRoute using `hover` and env variable works nice. Thanks and feel free to close this issue.

**Comment by Drakirus** [comment]
> Please consider exposing the functionality to set initialRoute in a more general purpose way. An example usage will be, my-app://token:123/?confirm_login, myapp can register a special url schema my-app:// and anything on the host OS can launch my app. This might require setting the initialRoute programmatically. And this will also require the already running myapp to intercept the my-app:// url and propely switch the route using pushRoute or something similar. (Maybe this should be a separate plugin, what do you think?)

That's another issue: https://github.com/go-flutter-desktop/go-flutter/issues/240

I think the use of venv is good enough for development purposes. (which was your initial request ^^)

**Comment by Drakirus** [comment]
While I see to need for 'uni_links' I don't plan to work on it.
Mainly because it cannot be done without platform specific configuration/code. 

I'll be happy to have a plug-in for url-links, please consider continuing on #240 😊😁

**Comment by pchampio** [comment]
Feature available in go-flutter: `v0.31.0` and hover `v0.36.0`.
Please run: `go get -u github.com/go-flutter-desktop/hover` and then `hover bumpversion` to upgrade hover and the project in which your are.

Then the `hover run --route "/XXX" ` cmd will be available!
