### ISSUE TITLE
Error response from daemon: open \\.\pipe\docker_d4w_systray: The system cannot find the file specified.

### ISSUE THREAD

**Issue by zj8331182** [go-flutter-desktop/go-flutter#279]
## Flutter version

```
Flutter 1.9.1+hotfix.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2d2a1ffec9 (4 weeks ago) • 2019-09-06 18:39:49 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
```

## Golang errors (Optional)

```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: open \\.\pipe\docker_d4w_systray: The system cannot find the file specified.
```

## Steps to Reproduce

1.clone the example code onto my windows pc
2. run command "hover build linux"
3. I make sure my pc's env is ok,beacuse i can run any docker command.
4.I guest the issue is that when i run command "hover build linux"on window pc the file path use is window's path but docker can't identification the window's path,it need linux's path

the flowwing code i guset case the issue case,but I have no idea how to fix

args := []string{
		"run",
		"-w", "/app/go",
		"-v", goPath + ":/go",
		"-v", wd + ":/app",
		"-v", engineCachePath + ":/engine",
		"-v", filepath.Join(userCacheDir, "go-build") + ":/cache",
	}

**Comment by Drakirus** [comment]
1) does Linux (from windows) build works on one of our example, https://github.com/go-flutter-desktop/examples/tree/master/keyboard_event? 
2) can you share the content of your pubspec.yaml file?

**Comment by zj8331182** [comment]
1.I build the stock example,https://github.com/go-flutter-desktop/examples/tree/master/stocks
2.pubspec.yaml file :
name: stocks


environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.15.8
  intl_translation: 0.17.7
  http: 0.12.0+2
  isolate: 2.0.2

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900

# PUBSPEC CHECKSUM: 8e0d

**Comment by zj8331182** [comment]
When i update the hover this issue not appear
