### ISSUE TITLE
docker file share failng

### ISSUE THREAD

**Issue by winwisely99** [go-flutter-desktop/go-flutter#283]
full makefile here:
https://github.com/winwisely99/enrollment-mod/tree/master/enrollment

log:
```
github.com/winwisely99/enrollment-mod/enrollment && hover build darwin-pkg
hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
hover: Compiling 'go-flutter' and plugins
hover: Successfully compiled
hover: Building darwin-bundle first
hover: Packaging bundle in /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/hover-build-enrollment-darwin-bundle593915717
Sending build context to Docker daemon  6.144kB
Step 1/2 : FROM ubuntu:bionic
 ---> 2ca708c1c9cc
Step 2/2 : RUN apt-get update && apt-get install icnsutils -y
 ---> Using cache
 ---> b29840dad2d8
Successfully built b29840dad2d8
Successfully tagged hover-build-packaging-darwin-bundle:latest
/usr/local/bin/docker: Error response from daemon: Mounts denied: 
The path /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/hover-build-enrollment-darwin-bundle593915717
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.

````

env:
```
flutter channel
Flutter channels:
* beta
  dev
  master
  stable


go version
go version go1.13.1 darwin/amd64


docker version
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by Drakirus** [comment]
Packaging uses docker, and is very experimental.
It has only been tested on linux,
Pinging @jld3103 has he might have inside about your issue.

From your log output:
```log
The path /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/hover-build-enrollment-darwin-bundle593915717
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

I am guessing extra steps are required to mount the temporary build file created by hover into the linux VM that's running the docker service.

**Comment by jld3103** [comment]
I simply read the referenced documentation and found this:
`
By default, you can share files in /Users/, /Volumes/, /private/, and /tmp directly. To add or remove directory trees that are exported to Docker, use the File sharing tab in Docker preferences whale
menu -> Preferences -> File sharing. (See Preferences.)
`

The problem is that your folder is in `/var` which is not allowed.

You could have simply read the referenced docs before opening this issue :), but no problem!

**Comment by winwisely99** [comment]
My flutter project code is not in var directory  - Its in a GOPATH.

I know i can configure a share but it means that this will happen for others on MAC too.

**Comment by jld3103** [comment]
Maybe the problem is that creating a temporary directory on MAC is placed in `/var` @GeertJohan ? You have more experience with such things.
Otherwise I have no explanation for that bug

**Comment by winwisely99** [comment]
I tried just now to add the /var share and Docker wont allow it.

![Screenshot 2019-10-18 at 16 08 04](https://user-images.githubusercontent.com/56028033/67101256-94445880-f1c1-11e9-9496-9de4ae5a696e.png)

**Comment by jld3103** [comment]
Oh crap.

**Comment by jld3103** [comment]
@Drakirus can you reopen?

**Comment by Drakirus** [comment]
Is it possible to add `/var/folders/wp/` ?

**Comment by winwisely99** [comment]
let me try now

**Comment by winwisely99** [comment]
Yes its happy with  "/var/folders/wp/ " :)

![Screenshot 2019-10-18 at 16 22 28](https://user-images.githubusercontent.com/56028033/67102286-7ed02e00-f1c3-11e9-8c47-e9c64f687a24.png)

**Comment by jld3103** [comment]
Looks like it's another edge case for cross-compiling / packaging that should be documented

**Comment by winwisely99** [comment]
Looks like it worked now on our project at: https://github.com/winwisely99/enrollment-mod/tree/master/enrollment

````
make flu-desk-pack-all
````

**Comment by winwisely99** [comment]
I just ran the darwin.pkg and it worked flawlessly ...

**Comment by jld3103** [comment]
The red messages are only warnings. I know that that isn't a good practice.

**Comment by winwisely99** [comment]
think its closable.  Maybe add this to the wiki ?
"
On Mac, when building with docker you need to the following share to docker: /var/folders/wp/
"

**Comment by jld3103** [comment]
As I said a lot of things need to be added to the wiki. This is one of them
