### ISSUE TITLE
hover: Failed to parse the 'go-flutter' version in go.mod

### ISSUE THREAD

**Issue by 645638180** [go-flutter-desktop/go-flutter#291]
myapp>hover run
[1;36mhover: [0mUsing engine from cache
[1;36mhover: [0mCleaning the build directory
[1;36mhover: [0m[32mBundling flutter app[0m
hover: Failed to parse the 'go-flutter' version in go.mod

**Comment by 645638180** [comment]
Flutter 1.10.7 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e70236e36c (3 weeks ago) • 2019-10-02 09:32:30 -0700
Engine • revision 9e6314d348
Tools • Dart 2.6.0 (build 2.6.0-dev.4.0 1103600280)

**Comment by 645638180** [comment]
what's the problem?

**Comment by Drakirus** [comment]
What is the content of go/go.mod?

**Comment by 645638180** [comment]
> What is the content of go/go.mod?

![image](https://user-images.githubusercontent.com/45378040/67548703-0c1c0100-f735-11e9-9955-d4f28ddbbbcb.png)
how to open it?

**Comment by 645638180** [comment]
> With a text editor

module std

go 1.12

require (
	golang.org/x/crypto v0.0.0-20190611184440-5c40567a22f8
	golang.org/x/net v0.0.0-20190813141303-74dc4d7220e7
	golang.org/x/sys v0.0.0-20190529130038-5219a1e1c5f8 // indirect
	golang.org/x/text v0.3.2 // indirect
)

**Comment by Drakirus** [comment]
The go projet seems to be wrongly initialized.

Can you:
 1. Make sure you are on the latest version of hover (read the hover Readme) 
  2. Delete the go directory from your project
  3. Run `hover init` and `hover run`

Can you also try a example project? 
https://github.com/go-flutter-desktop/examples/tree/master/mousebuttons

**Comment by 645638180** [comment]
![image](https://user-images.githubusercontent.com/45378040/67552244-3ec9f780-f73d-11e9-8368-8af876c350c2.png)
I delete the go directory ,run hover init and hover run but the same problem
I try the example,but show another problem   (ToT)

**Comment by 645638180** [comment]
More problems now... haha, but thank you so much.

I will study it later.

**Comment by 645638180** [comment]
Hi,I build 'myapp.exe' now.
I run it,but it opens with CMD.
Is that right?
Can I close the CMD?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Pierre Champion"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 下午3:48
收件人:&nbsp;"go-flutter-desktop/go-flutter"<go-flutter@noreply.github.com&gt;;
抄送:&nbsp;"杨杰"<645638180@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [go-flutter-desktop/go-flutter] hover: Failed to parse the 'go-flutter' version in go.mod (#291)



 
exec: "gcc": executable file not found in %PATH%
  
You don't have a C compiler installed on you machine.
 
https://github.com/go-flutter-desktop/hover#install
 
 
Once gcc --version prints something in your terminal, you will have completed the first step for installing hover.
 
Alternatively (I don't recommend since you are on windows) you can use hover run --docker

**Comment by Drakirus** [comment]
`hover build windows` for non debug build.
If you are using Dart Process.run - > https://github.com/go-flutter-desktop/go-flutter/wiki/Tips-and-tricks#1-windows-console

**Comment by yxAnswer** [comment]
I have the same problem.

[1;36mhover: [0mUsing engine from cache
[1;36mhover: [0mCleaning the build directory
[1;36mhover: [0m[32mBundling flutter app[0m
hover: Failed to parse the 'go-flutter' version in go.mod



`module github.com/go-flutter-desktop/hover

go 1.13

require (
	github.com/GeertJohan/go.rice v1.0.0
	github.com/daaku/go.zipexe v1.0.1 // indirect
	github.com/google/go-github v17.0.0+incompatible // indirect
	github.com/google/go-querystring v1.0.0 // indirect
	github.com/hashicorp/go-version v1.2.0
	github.com/logrusorgru/aurora v0.0.0-20191116043053-66b7ad493a23
	github.com/otiai10/copy v1.0.2
	github.com/pkg/errors v0.8.1
	github.com/spf13/cobra v0.0.5
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/tcnksm/go-latest v0.0.0-20170313132115-e3007ae9052e
	golang.org/x/net v0.0.0-20191101175033-0deb6923b6d9 // indirect
	gopkg.in/yaml.v2 v2.2.7
)`

**Comment by 645638180** [comment]
应该是安装go的时候报错了

**Comment by 645638180** [comment]
> I have the same problem.
> 
> �[1;36mhover: �[0mUsing engine from cache
> �[1;36mhover: �[0mCleaning the build directory
> �[1;36mhover: �[0m�[32mBundling flutter app�[0m
> hover: Failed to parse the 'go-flutter' version in go.mod
> 
> `module github.com/go-flutter-desktop/hover
> 
> go 1.13
> 
> require (
> github.com/GeertJohan/go.rice v1.0.0
> github.com/daaku/go.zipexe v1.0.1 // indirect
> github.com/google/go-github v17.0.0+incompatible // indirect
> github.com/google/go-querystring v1.0.0 // indirect
> github.com/hashicorp/go-version v1.2.0
> github.com/logrusorgru/aurora v0.0.0-20191116043053-66b7ad493a23
> github.com/otiai10/copy v1.0.2
> github.com/pkg/errors v0.8.1
> github.com/spf13/cobra v0.0.5
> github.com/spf13/pflag v1.0.5 // indirect
> github.com/tcnksm/go-latest v0.0.0-20170313132115-e3007ae9052e
> golang.org/x/net v0.0.0-20191101175033-0deb6923b6d9 // indirect
> gopkg.in/yaml.v2 v2.2.7
> )`

应该是安装go的时候有错，好像有一个下载需要梯子
