### ISSUE TITLE
Error updating hover

### ISSUE THREAD

**Issue by davidmartos96** [go-flutter-desktop/go-flutter#292]
When installing `hover` with `go get -u github.com/go-flutter-desktop/hover` I'm getting the following error:
```
# github.com/go-flutter-desktop/hover/cmd/packaging
../../go/src/github.com/go-flutter-desktop/hover/cmd/packaging/packaging.go:203:68: dockerBuildCmd.String undefined (type *exec.Cmd has no field or method String)
../../go/src/github.com/go-flutter-desktop/hover/cmd/packaging/packaging.go:204:64: dockerRunCmd.String undefined (type *exec.Cmd has no field or method String)
```

Go version: go1.12.6 linux/amd64

**Comment by davidmartos96** [comment]
Updating to go 1.13 did fix it. I don't know if you would like to keep it open, since in the docs it says go 1.12 as minimum.

**Comment by jld3103** [comment]
This should be kept open as long as there is no fix for it.

**Comment by Drakirus** [comment]
Oups it's my commit😅

It might be time to move to 1.13 and fix #170

@jld3103 should we still wait for 1.13 to really be mainstream, or require 1.13 for all go-flutter-desktop projects

**Comment by jld3103** [comment]
I think moving to 1.13 would be better. Also 1.13 is the latest stable version according to this: https://golang.org/dl/#stable

**Comment by davidmartos96** [comment]
If you guys decide to make 1.13 the supported version, it should be noted in the docs some info about the migration. A small issue I encountered when upgrading to 1.13 was that the go-gl version was giving some conflict versioning errors. I ended up fixing it looking at the solution in a past issue, but better make it explicit somewhere.

**Comment by Drakirus** [comment]
>  I ended up fixing it looking at the solution in a past issue, but better make it explicit somewhere.

Yea, prior to v0.29.0 (IIRC) the way we ref go-gl in our go.sum isn't working with 1.13.

**Comment by jld3103** [comment]
Hm I was using go 1.13 for some weeks and had no migration problems coming from go 1.12

**Comment by Drakirus** [comment]
@jld3103 here is the issue https://github.com/miguelpruivo/flutter_file_picker/issues/140

It is kinda bad since it also affects plug-in. 

We should inform people to use go 1.13 and go-flutter > 0.30.0

**Comment by jld3103** [comment]
Oh yeah I had that error with file picker. I created this PR for it: miguelpruivo/flutter_file_picker#162

**Comment by pchampio** [comment]
Updated hover readme.
