### ISSUE TITLE
examplesapp still in white screen

### ISSUE THREAD

**Issue by YoussefBadal** [go-flutter-desktop/go-flutter#293]
Example name: stocks
Examples repository version: master
## Flutter version

```
Flutter Channel beta, v1.10.7
Framework • revision master (1weeks ago) • xxxxxxxxxxxxxxxxxxxxxxxx
Engine • revision xxxxxxxxxx
Tools • Dart x.x.x (build xxxxxxxxxx)
```

## Golang errors (Optional)

```
Golang's compiling errors
```

## Steps to Reproduce

1.    first of all thanks for you effor to provide us alternative to FDE.
   I have installed go and hover according the description ,and after clone the examples from github , i make hover build  windows , averything is running but when i open stocks.exe from the go\build\outputs\windows the app still in white screen and nothing i coming, the same result is for all examples. i try also to set the flag opengl=none , the same result.
![whiteScreen](https://user-images.githubusercontent.com/19620944/67596637-7cdd1080-f769-11e9-9da1-c5cf290ce047.PNG)

**Comment by jld3103** [comment]
Can you add this line, before `runApp(...)`:
```dart
WidgetsFlutterBinding.ensureInitialized();
```

**Comment by YoussefBadal** [comment]
thanks jld3103 for the answer, but the white screen is  still persist, nothing changed.

**Comment by Drakirus** [comment]
Does this occurs on others examples?

**Comment by YoussefBadal** [comment]
Yes as i wrote the same result for all examples and also my flutter app

Pierre Champion <notifications@github.com> schrieb am Fr., 25. Okt. 2019,
21:20:

**Comment by Drakirus** [comment]
Oh yes sorry,  I somehow miss that from your description.

Does `hover run` gives you an output in the terminal?

**Comment by YoussefBadal** [comment]
with hover run the same result :), i try more then 3 days  :)
![whiteScreenRun](https://user-images.githubusercontent.com/19620944/67599412-4787f100-f770-11e9-890e-20ec747383f8.PNG)

**Comment by Drakirus** [comment]
Humm, whenever I receive an issue, I always have a quick idea for a potential fix, but this one different, I actually have no idea of what is going on 🤔.

No error message + a while screen.. We have to dig deeper. 

Similar to what jld proposed, can you add:
 - A print before runApp(...) to ensure the Dart VM is running.
 - A print before the first return of the build method from your root widget to ensure flutter wants to draw something

**Comment by YoussefBadal** [comment]
so i tried your suggestion with print function and i see that the last print before the return of the build method is not called
![whiteScreenRunPrint](https://user-images.githubusercontent.com/19620944/67602512-10690e00-f777-11e9-950c-9695bdf55f95.PNG)

**Comment by Drakirus** [comment]
Does updating to the latest version of Flutter (still recommend the beta channel) changes something?

**Comment by YoussefBadal** [comment]
The problem is solved .it was my external geforce 520m Graficard it's old one .i switch to internal graficcard from intel and now the apps runs.thanks for the help
