### ISSUE TITLE
hover build darwin-bundle failing

### ISSUE THREAD

**Issue by Tao-Baby** [go-flutter-desktop/go-flutter#295]
TdeMacBook-Pro:demo tao$ hover build darwin-bundle
hover: Using engine from cache
hover: Cleaning the build directory
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Bundling flutter app
hover: Compiling 'go-flutter' and plugins
hover: Successfully compiled
hover: Packaging bundle in /var/folders/b5/3hmlnc3n21g14bm9zchn1ryc0000gn/T/hover-build-demo-darwin-bundle976658021
Sending build context to Docker daemon  6.144kB
Step 1/2 : FROM ubuntu:bionic
 ---> cf0f3ca922e0
Step 2/2 : RUN apt-get update && apt-get install icnsutils -y
 ---> Using cache
 ---> b7f9a7ffcb53
Successfully built b7f9a7ffcb53
Successfully tagged hover-build-packaging-darwin-bundle:latest
mkdir: cannot create directory 'demo.app/Contents/Resources': File exists
hover: Docker run failed: exit status 1
hover: Packaging is very experimental and has only been tested on Linux.
hover: To help us debuging this error, please zip the content of:
       "/var/folders/b5/3hmlnc3n21g14bm9zchn1ryc0000gn/T/hover-build-demo-darwin-bundle976658021"
       and try to package on another OS. You can also share this zip with the go-flutter team.
hover: You can package the app without hover by running:
hover:   `cd /var/folders/b5/3hmlnc3n21g14bm9zchn1ryc0000gn/T/hover-build-demo-darwin-bundle976658021`
hover:   docker build: `/usr/local/bin/docker build -t hover-build-packaging-darwin-bundle .`
hover:   docker run: `/usr/local/bin/docker run -w /app -v /var/folders/b5/3hmlnc3n21g14bm9zchn1ryc0000gn/T/hover-build-demo-darwin-bundle976658021:/app hover-build-packaging-darwin-bundle bash -c mkdir demo.app/Contents/Resources && png2icns demo.app/Contents/Resources/icon.icns demo.app/Contents/MacOS/assets/icon.png && chown 501:20 * -R`

**Comment by jld3103** [comment]
Oh ya. Simple fix. Wait a minute.

**Comment by jld3103** [comment]
@Tao-Baby Please update hover and try again. Should work now.

**Comment by Tao-Baby** [comment]
> @Tao-Baby Please update hover and try again. Should work now.

well,thx.

**Comment by foreverzmy** [comment]
I hava the same problem.

hover build darwin-bundle
hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
hover: Compiling 'go-flutter' and plugins
# github.com/go-gl/glfw/v3.2/glfw
In file included from ../../../Golang/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/c_glfw_darwin.go:8:
../../../Golang/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/glfw/src/cocoa_window.m:989:9: warning: multiple methods named 'center' found [-Wobjc-multiple-method-names]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCollectionViewCompositionalLayout.h:601:19: note: using
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:312:1: note: also found
hover: Successfully compiled
hover: Packaging bundle in /var/folders/kg/cc8xf1x96k7cssvfpc4m7d_00000gn/T/hover-build-yoda-darwin-bundle414015880
Sending build context to Docker daemon  6.144kB
Step 1/2 : FROM ubuntu:bionic
 ---> 775349758637
Step 2/2 : RUN apt-get update && apt-get install icnsutils -y
 ---> Using cache
 ---> c18708973e01
Successfully built c18708973e01
Successfully tagged hover-build-packaging-darwin-bundle:latest
mkdir: cannot create directory 'yoda.app/Contents/Resources': File exists
hover: Docker run failed: exit status 1
hover: Packaging is very experimental and has only been tested on Linux.
hover: To help us debuging this error, please zip the content of:
       "/var/folders/kg/cc8xf1x96k7cssvfpc4m7d_00000gn/T/hover-build-yoda-darwin-bundle414015880"
       and try to package on another OS. You can also share this zip with the go-flutter team.
hover: You can package the app without hover by running:
hover:   `cd /var/folders/kg/cc8xf1x96k7cssvfpc4m7d_00000gn/T/hover-build-yoda-darwin-bundle414015880`
hover:   docker build: `/usr/local/bin/docker build -t hover-build-packaging-darwin-bundle .`
hover:   docker run: `/usr/local/bin/docker run -w /app -v /var/folders/kg/cc8xf1x96k7cssvfpc4m7d_00000gn/T/hover-build-yoda-darwin-bundle414015880:/app hover-build-packaging-darwin-bundle bash -c mkdir yoda.app/Contents/Resources && png2icns yoda.app/Contents/Resources/icon.icns yoda.app/Contents/MacOS/assets/icon.png && chown 501:20 * -R`

**Comment by pchampio** [comment]
Update hover:
`go get -u github.com/go-flutter-desktop/hover`
