### ISSUE TITLE
ClearAllHandler for MethodChannel

### ISSUE THREAD

**Issue by befovy** [go-flutter-desktop/go-flutter#300]
## Is your feature request related to a problem?

`MethodChannel` dose not have clear handler method like java and objc.

## Describe the feature you'd like

add new `ClearAllHandler` method for `MethodChannel` and clear map methods in it 

I'm pleasure to implement it if this new method is accepted

**Comment by pchampio** [comment]
Recreating the NewMethodChannel should do the trick, but it's not a super clean.

Yes, I'm interested in a `ClearAllHandler` method for `MethodChannel`.

You can submit a PR.

**Comment by pchampio** [comment]
tagged into: `v0.32.0`
