### ISSUE TITLE
How can I output ALL logs to a file, include system's log

### ISSUE THREAD

**Issue by ximigame** [go-flutter-desktop/go-flutter#307]
I mean not only the log i call print, but also the system's

**Comment by pchampio** [comment]
What is your system?
What is the use-case? 
On which command would you like to save a log file? (hover run? Or from the binary) 

On Linux: https://stackoverflow.com/a/6674348

I'm not sure I understand your use case.

**Comment by ximigame** [comment]
> What is your system?
---eg.
"go-flutter: recover from wrong editingState: invalid text selection: selectionBase:-1, selectionExtent:-1. Refer to go-flutter-desktop/go-flutter#221"

"creating glfw window: APIUnavailable: WGL: The driver does not appear to support OpenGL"

> What is the use-case?
> On which command would you like to save a log file? (hover run? Or from the binary)

 ----when i use hover run, there are logs in the console. but i can't get logs from the release app(hover build)

> 
> On Linux: https://stackoverflow.com/a/6674348
> 
> I'm not sure I understand your use case.

**Comment by pchampio** [comment]
You will certainly have to modify the template generated by `hover init-package XXX`.
 For example on `hover init-package linux-appimage` the packaging build files are located under `go/packaging/linux-appimage`.
Editing the `AppRun` file and adding the above `> stdout.txt 2> stderr.txt` to the line `exec ./build/simple_app` redirect the output in a log file.

You have to configure your packaging build files to achieve such feature.
