### ISSUE TITLE
How to build mac application and use it in low os.

### ISSUE THREAD

**Issue by CaiJingLong** [go-flutter-desktop/go-flutter#310]
I want to build an application and distribution it to other user to use it.

Now my steps are like this:

1. Build application in mac os 10.15.1.
2. Send dmg to other user.
3. User can't use it.

I use the command to build application.
```bash
hover build darwin-dmg
```

Then all the versions below 10.15 can't use this app. It seems that cgo introduces some system dynamic libraries.

## hover version
<details>

```bash
hover: Running on darwin
hover: Docker installed: true
hover: Sharing flutter version
Flutter 1.10.17-pre.70 • channel master • https://github.com/flutter/flutter.git
Framework • revision 01f4f1ac55 (5 hours ago) • 2019-11-12 18:25:53 -0800
Engine • revision 31cd2dfca2
Tools • Dart 2.7.0
hover: Flutter engine commit: https://github.com/flutter/engine/commit/31cd2dfca2
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Finding out the C compiler version
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
hover: Sharing the content of go.mod
module github.com/fluttercandies/JsonToDart/tree/master/Flutter/desktop/desktop

go 1.12

require (
        github.com/go-flutter-desktop/go-flutter v0.33.0
        github.com/go-gl/glfw v0.0.0-20190519095719-e6da0acd62b1 // indirect
        github.com/pkg/errors v0.8.1
        github.com/stretchr/objx v0.2.0 // indirect
        gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15 // indirect
        gopkg.in/yaml.v2 v2.2.5 // indirect
)
hover: Warning: No hover.yaml file found: open go/hover.yaml: no such file or directory
hover: Sharing the content of go/cmd
go/cmd/main.go  go/cmd/options.go
```
</details>

## log

<details>

```bash
dyld: lazy symbol binding failed: Symbol not found: _objc_opt_class
  Referenced from: /Users/roott/Downloads/darwin/json_to_dart (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_opt_class
  Referenced from: /Users/roott/Downloads/darwin/json_to_dart (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

SIGABRT: abort
PC=0x718c38e m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4152cc0, 0xc000042ab8, 0x400eb48)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc000042a88 sp=0xc000042a50 pc=0x400547b
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwCreateWindow(0x43800000780, 0x661c160, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:536 +0x4e fp=0xc000042ab8 sp=0xc000042a88 pc=0x410f15e
github.com/go-gl/glfw/v3.2/glfw.CreateWindow.func2(0x780, 0x438, 0x661c160, 0x0, 0x0, 0x1)
	/Users/cai/code/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/window.go:287 +0xab fp=0xc000042af0 sp=0xc000042ab8 pc=0x411636b
github.com/go-gl/glfw/v3.2/glfw.CreateWindow(0x780, 0x438, 0x41e4b31, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/cai/code/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/window.go:287 +0xff fp=0xc000042b90 sp=0xc000042af0 pc=0x41141ff
github.com/go-flutter-desktop/go-flutter.(*Application).Run(0xc0000b4000, 0x0, 0x0)
	/Users/cai/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.33.0/application.go:119 +0x100 fp=0xc000042e98 sp=0xc000042b90 pc=0x4139bd0
github.com/go-flutter-desktop/go-flutter.Run(0xc0000920a0, 0x4, 0x4, 0x2, 0xc000042f40)
	/Users/cai/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.33.0/application.go:27 +0x4d fp=0xc000042ec8 sp=0xc000042e98 pc=0x413942d
main.main()
	/Users/cai/Documents/GitHub/fluttercandies/JsonToDart/Flutter/desktop/go/cmd/main.go:24 +0x188 fp=0xc000042f60 sp=0xc000042ec8 pc=0x4145538
runtime.main()
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203 +0x21e fp=0xc000042fe0 sp=0xc000042f60 pc=0x402ffee
runtime.goexit()
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000042fe8 sp=0xc000042fe0 pc=0x4058a91

rax    0x2000209
rbx    0x0
rcx    0x7ffeefbfe488
rdx    0x7ffeefbfe8f0
rdi    0x6
rsi    0x4
rbp    0x7ffeefbfe4d0
rsp    0x7ffeefbfe488
r8     0x7ffeefbfe4f0
r9     0x0
r10    0x68
r11    0x246
r12    0x68
r13    0x7ffeefbfe8f0
r14    0x4
r15    0x6
rip    0x718c38e
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
```

</details>

**Comment by pchampio** [comment]
Packaging is done in docker, But if you are running on the OS of distribution, the default compilation of the binaries (exact output of `hover build darwin`) is perform on the host.

Can you run `hover build darwin-dmg --docker` to have the entire compilation/packaging procedure run on Docker.

**Comment by pchampio** [comment]
You can also add the following line in your `go/cmd/option.go` file:
```go
// #cgo CXXFLAGS: -std=c++11
// #cgo darwin CFLAGS: -mmacosx-version-min=10.13
// #cgo darwin LDFLAGS: -mmacosx-version-min=10.13
// #cgo darwin CXXFLAGS: -mmacosx-version-min=10.13
import "C"
```

**Comment by CaiJingLong** [comment]
I need to contact the App user to determine if it works, because I don't have a lower version of mac os.
Need to wait for the user's reply, I will contact you if there is a message.

**Comment by befovy** [comment]
@CaiJingLong Hi, what is the version number of the "lower version of mac os"?
I have mac os with version 10.14.6 (18G1012).
Where can I get the dmg file? I can make a test.

**Comment by CaiJingLong** [comment]
@pchampio 
I contacted the user and it seems can''t be opened.
I use [tip-and-tricks](https://github.com/go-flutter-desktop/go-flutter/wiki/Tips-and-tricks#4-darwin-how-to-build-mac-application-and-use-it-in-low-os) to build it.

**Comment by CaiJingLong** [comment]
Then, I tried another solution, using the image of macOS-10.14 provided by github actions, but it seems to encounter another problem.

https://github.com/CaiJingLong/JsonToDart/releases/tag/v0.0.20

I get the result when I double click to open it.
![image](https://user-images.githubusercontent.com/14145407/69026684-d9e58280-0a06-11ea-83b6-d0236137e7c8.png)

---

And if I use the cli to open the binary of flutter, it is normal.
`$JsonToDart.app/Contents/MacOS/json_to_dart` 

After opening via cli, the app is also restored to normal, I can open it by double-clicking.

**Comment by pchampio** [comment]
@CaiJingLong please open another issue for the second problem.

**Comment by pchampio** [comment]
Removed Tip-and-tricks 4 from wiki:
---
### 4. Darwin: How to build mac application and use it in low os:

Place the following `compatibility_darwin.go` file into the `go/cmd/` directory: 
```go
package main

// the file compatibility_darwin.go is used to set custom compile fags
 
// #cgo darwin CFLAGS: -mmacosx-version-min=10.13
// #cgo darwin LDFLAGS: -mmacosx-version-min=10.13
// #cgo darwin CXXFLAGS: -mmacosx-version-min=10.13
import "C"
```

By @pchampio, [#310](https://github.com/go-flutter-desktop/go-flutter/issues/310)
---

**Comment by pchampio** [comment]
@CaiJingLong we have another alternative:

Packaging is done in docker, But if you are running on the OS of distribution, the default compilation of the binaries (exact output of `hover build darwin`) is perform on the host.

Can you run `hover build darwin-dmg --docker` to have the entire compilation/packaging procedure run on Docker?
Does `hover build darwin-dmg --docker` fixes the issue?

**Comment by CaiJingLong** [comment]
```bash
$ hover build darwin-dmg --docker          
hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM dockercore/golang-cross
 ---> 44188208cab3
Step 2/2 : RUN apt-get update && apt-get install libgl1-mesa-dev xorg-dev -y
 ---> Using cache
 ---> faf41a014742
Successfully built faf41a014742
Successfully tagged hover-build-cc:latest
hover: Cross-Compiling 'go-flutter' and plugins using docker
github.com/fluttercandies/JsonToDart/tree/master/Flutter/desktop/desktop/cmd
# github.com/fluttercandies/JsonToDart/tree/master/Flutter/desktop/desktop/cmd
osxcross: error: targeted OS X version must be <= 10.10.0 (SDK)
osxcross: error: while detecting target
hover: Docker run failed: exit status 2
```

**Comment by CaiJingLong** [comment]
When I edit the min version to 10.10.0, I get a dmg. I will ask the user to test if it is available.

**Comment by CaiJingLong** [comment]
This is my user capture his screenshot.
![image](https://user-images.githubusercontent.com/14145407/69108606-2042ec00-0ab0-11ea-8947-2ebcecdde3a2.png)

The border of yellow is application windows.

**Comment by pchampio** [comment]
Does `hover build darwin-bundle` produce the same black screen result?

**Comment by pchampio** [comment]
Friendly ping.
Does `hover build darwin-bundle --docker` works on your consumer device?

**Comment by CaiJingLong** [comment]
`hover build darwin-bundle --docker`  it works.
Double-clicking the app directly in dmg will continue to loading, but dragging the app to the `/application` folder will not cause problems.

Thanks for your work.
