### ISSUE TITLE
Hover without flutter !?

### ISSUE THREAD

**Issue by elbashery** [go-flutter-desktop/go-flutter#312]
Why doesn't Hover be a project independent of Flutter?
What do you think of project like this ?
https://gioui.org/
 https://www.youtube.com/watch?v=PxnL3-Sex3o&t=31s

 Could you soon have something great like flutter?
I wonder this question because I believe that there will be no need  Hover when FlutterDesktop becomes stable
I hope I'm wrong.
Thank you

**Comment by jld3103** [comment]
This project is about flutter for desktop. You are free to choose any other UI framework, but go-flutter is only for flutter.

**Comment by pchampio** [comment]
I'm a bit shocked by the "Hover without flutter !?". 
This project isn't about building a UI toolkit. I don't fave any opinions on gioui, as I'm not a ui/ui-toolkit developer. 
Make sure to read: https://github.com/go-flutter-desktop/go-flutter/issues/191

And please:
> Could you soon have something great like flutter?

Have you heard of open source maintainer burnout? (remove the soon from your sentence next time😉)

**Comment by elbashery** [comment]
Thank you very much.
