### ISSUE TITLE
build module requires Go 1.13 cross-compiling

### ISSUE THREAD

**Issue by nzlov** [go-flutter-desktop/go-flutter#313]
## Hover doctor

```
$ hover doctor
hover: Running on darwin
hover: Docker installed: true
hover: Sharing flutter version
Flutter 1.10.15-pre.23 • channel master • https://github.com/flutter/flutter.git
Framework • revision 440753bae8 (6 weeks ago) • 2019-10-08 21:33:17 -0700
Engine • revision 0d749933bc
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 f4a72bfc64)
hover: Flutter engine commit: https://github.com/flutter/engine/commit/0d749933bc
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Finding out the C compiler version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
hover: Sharing the content of go.mod
module minesweeper/go

go 1.13

require (
	github.com/go-flutter-desktop/go-flutter v0.33.0
	github.com/go-flutter-desktop/plugins/shared_preferences v0.4.3
	github.com/pkg/errors v0.8.1
)
hover: Sharing the content of hover.yaml
target: lib/main_desktop.dart
branch: ""
cache-path: ""
opengl: ""
docker: false
hover: Sharing the content of go/cmd
go/cmd/import-shared_preferences-plugin.go	go/cmd/main.go	go/cmd/options.go
```

## Error output

Using `hover build [...] --XXX` to build my application, I get the following
error:

```log
hover: Using engine from cache
hover: Cleaning the build directory
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Bundling flutter app
hover: Because darwin is not able to compile for windows out of the box, a cross-compiling container is used
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM dockercore/golang-cross
 ---> 44188208cab3
Step 2/2 : RUN apt-get update && apt-get install libgl1-mesa-dev xorg-dev -y
 ---> Using cache
 ---> a7763d7b30c3
Successfully built a7763d7b30c3
Successfully tagged hover-build-cc:latest
hover: Cross-Compiling 'go-flutter' and plugins using docker
github.com/go-flutter-desktop/plugins/shared_preferences
# github.com/go-flutter-desktop/plugins/shared_preferences
/go/pkg/mod/github.com/go-flutter-desktop/plugins/shared_preferences@v0.4.3/plugin.go:47:28: undefined: os.UserConfigDir
note: module requires Go 1.13
hover: Docker run failed: exit status 2
```

## Why:
docker image `golang-cross` based on `golang 1.12.12`.
`shared_preferences` use `os.UserConfigDir` in `golang 1.13`

## How Fix
rebuild `golang-cross` image based on `golang 1.13`

**Comment by jld3103** [comment]
I think you need to update the docker image. I have no problem with cross-compiling.

**Comment by pchampio** [comment]
@jld3103 can you test with `github.com/go-flutter-desktop/plugins/shared_preferences v0.4.3`?
dockercore/golang-cross dosn't support golang 1.13. Pending PR https://github.com/docker/golang-cross/pull/45.
I didn't realized it when I've fixed: #170 

@nzlov a temporary fix is to downgrade shared_preferences to `v0.4.1`. sorry for the inconvenience.

**Comment by pchampio** [comment]
Waiting for docker/golang-cross#45

**Comment by pchampio** [comment]
After a bit of search on the docker hub, I've found [this](https://hub.docker.com/r/goreng/golang-cross) container that supports golang 1.13.

If you want to compile everything using golang 1.13, the temporary solution is to edit the `go/cross-compiling/Dockerfile` file and change the `FROM dockercore/golang-cross` to `FROM goreng/golang-cross:v1.13.1`.

Keeping this PR open, I would prefer to use docker/golang-cross as a build container, because the code source is open.
And hover needs to be updated!

**Comment by jld3103** [comment]
Maybe `goreng/golang-cross:v1.13.1` should be the default as long as the official golang cross-compiling image is not published.
We require go 1.13 as minimum version, but don't support it on cross-compiling. We should be consistent about that.

**Comment by pchampio** [comment]
Ok, @jld3103 you can do the PR/Merge on hover.

**Comment by jld3103** [comment]
@pchampio Can you do it? I need to get some sleep and can only do something again tomorrow evening

**Comment by pchampio** [comment]
ok

**Comment by pchampio** [comment]
@nzlov please update hover: `go get -u github.com/go-flutter-desktop/hover`, rm `go/cross-compiling` and rerun your build!

**Comment by nzlov** [comment]
@pchampio @jld3103 
Why use `goreng/golang-cross: v1.13.1` instead of the `dockercore/golang-cross` change implementation?

**Comment by pchampio** [comment]
We use the goreng/golang-cross image because we don't have another choice.
It's the only image that supports golang 1.13.

You aren't affected by this change.
