### ISSUE TITLE
hardware keyboard text selection

### ISSUE THREAD

**Issue by pchampio** [go-flutter-desktop/go-flutter#314]
The flutter team is implementing keyboard text selection movement at the framework level.
They are using the [`"flutter/keyevent"` BasicMessageChannel](https://github.com/go-flutter-desktop/go-flutter/blob/master/key-events.go#L11) as source of keyboard selection/movement events.

Currently go-flutter has implemented text selection movement at the embedder (glfw) level.
Work is duplicate (handlers in go-flutter and flutter for the same purpose), once everything is up on the framework side we should delete our handler. (textinput_{linux, windows, darwin}.go and some stuff in textinput-model.go)

Some related flutter PRs:
https://github.com/flutter/flutter/pull/44130
https://github.com/flutter/flutter/pull/42879
https://github.com/flutter/flutter/issues/36316

BUG: Having duplicate handler for keyboard shortcut causes issue with pasting text, **Ctrl-v** is trigger twice, resulting in double pastes.

**Comment by stuartmorgan** [comment]
FWIW this is an area of ongoing discussion; see https://github.com/flutter/flutter/issues/30725 for some of it.

**Comment by pchampio** [comment]
Using `Flutter 1.12.13+hotfix.5 • channel stable`, there is an issue with copying text in `SelectableText`.

`SelectableText` doesn't expose the text content through the `"flutter/textinput"` MethodChannel, meaning embedder cannot directly query the text content and put it in the OS clipboard. (This is how go-flutter handles it when using `TextField`: [code](https://github.com/go-flutter-desktop/go-flutter/blob/f223ac0af05e98652479444f720d4f4b1bb57b2f/textinput.go#L190-L194))

On prior version of the framework, there was no way for your embedder to get the content of the `SelectableText` text and put it in the OS clipboard.

With the latest version of the Flutter framework, Copy is handled through the [`"flutter/keyevent"` BasicMessageChannel](https://github.com/go-flutter-desktop/go-flutter/blob/master/key-events.go#L11). As we are using GLFW for all platform (linux/windows/macos) this raises the question on **how the flutter team plans to support** each rendering graphics library on each platform.

The Copy shortcut for GLFW on windows/linux isn't the same as on MacOS, and currently, when sending [GLFW keyevents](https://github.com/go-flutter-desktop/go-flutter/blob/f223ac0af05e98652479444f720d4f4b1bb57b2f/key-events.go#L76-L84) for the copy action, only the windows/linux shortcut is supported.

If the flutter team plan to only use the [`"flutter/keyevent"` BasicMessageChannel](https://github.com/go-flutter-desktop/go-flutter/blob/master/key-events.go#L11) for text shortcut selection/navigation/copy/paste.. they would have to support the X*Y matrices, X been the platform and Y been the rendering graphics library. I would much rather (and it is how stuff is currently done in go-flutter) handles everything at the engine/embedder level than dealing with the framework abstraction (in the context of building a cross-platform embedder like go-flutter or flutter-rs).

**Comment by pchampio** [comment]
Need to write a PR on flutter.
GLFW RawKeyEvent can be used on MacOS.
Have to change:
https://github.com/flutter/flutter/blob/1ba4f1f509202f3d2ec16f053edcbe2df6b7107e/packages/flutter/lib/src/rendering/editable.dart#L481
To:
`something == TargetPlatform.macOS`
