### ISSUE TITLE
TextEditingController not working properly

### ISSUE THREAD

**Issue by Vinoth1094** [go-flutter-desktop/go-flutter#319]
TextEditingController.**text** always returns empty String.

I'm using TextEditingController as controller for TextField and added listener to the TextEditingController as below,

**TextEditingController usernameController = TextEditingController();**

**usernameController.addListener(() {
      print(usernameController.text);
});**

**TextField(
      controller: usernameController,
      focusNode: usernameFocusNode,
)**

The above listener was triggered each time text of TextField changed. But the value printed is always empty String.

Please let me know if there is any solution or at least any workaround available or not.

Here is the hover doctor command output

> hover doctor
> [1;36mhover: [0m[32mRunning on windows[0m
> [1;36mhover: [0m[32mDocker installed: false[0m
> [1;36mhover: [0m[32mSharing flutter version[0m
> Flutter 1.12.6-pre.13 • channel master • https://github.com/flutter/flutter.git
> Framework • revision 0b502b1f8b (5 days ago) • 2019-11-20 22:11:51 -0500
> Engine • revision 7a77e3625d
> Tools • Dart 2.7.0
> hover: Flutter engine commit: https://github.com/flutter/engine/commit/7a77e3625d
> hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
> hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
> hover: Finding out the C compiler version
> gcc (tdm64-1) 5.1.0
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> hover: Sharing the content of go.mod
> module model_generator/go
> 
> go 1.13
> 
> require (
>         github.com/go-flutter-desktop/go-flutter v0.33.0
>         github.com/go-flutter-desktop/plugins/shared_preferences v0.4.3
>         github.com/pkg/errors v0.8.1
> )
> hover: Sharing the content of hover.yaml
> target: lib/main_desktop.dart
> branch: ""
> cache-path: ""
> opengl: ""
> docker: false
> hover: Sharing the content of go/cmd
> go\cmd\main.go  go\cmd\options.go

**Comment by pchampio** [comment]
I can see that you are running on `master`, does the `flutter channel beta` works?

**Comment by Vinoth1094** [comment]
Yes, it does work in the beta channel. But pasting text using shortcut **Ctrl+V** pastes the text twice.

This issue can be reproduced every time in both beta and master channels.
Can anyone help to resolve this issue?

**Comment by pchampio** [comment]
Closing this issue because Master can be unstable, can always be reopened if needed.

About:
> But pasting text using shortcut Ctrl+V pastes the text twice.

This is another issue, please refer to #314 
The flutter team is currently working on the text back-end, some issues are still discussed. The go-flutter team is waiting to have a stable behavior rather than hot-fixing every little issue. If you want **Ctrl-V** to work, you need to use `flutter version v1.9.1-hotfixes` (no text shortcut back-end on flutter/flutter) with go-flutter [go-flutter@v0.33.0](https://github.com/go-flutter-desktop/go-flutter/releases/tag/v0.33.0)

**Comment by JulienMalige** [comment]
do we have any news about this? It still doesn't seem to work properly.

**Comment by JulienMalige** [comment]
It seems to be resolved with flutter 2.0.3!

**Comment by davidgaspardev** [comment]
I have a problem with the `addListener` method of `TextEditingController`, the method is not called when a change occurs.

I'm in the process of migrating the old code to a new repository, and the `addListener` method in the old code works just fine.

This is my class for abstracting the TextField:
```dart
/// External package
import 'package:flutter/material.dart';
/// Internal packages
import 'package:hoppy/app/helpers/palette.dart';
import 'package:hoppy/app/helpers/widgets/label.dart';

/// Input
/// 
/// It's a customized [TextField] Widget, but unlike Label, it does not extend TextField, 
/// it extends [Stateless] and instantiates TextField, because TextField is Stateful.
class Input extends StatelessWidget {

  // Attributes
  final int maxLines;
  final String? hintText;
  final double hintSize;
  final FontStyle hintStyle;
  final FontWeight hintWeight;
  final String hintFamily;
  final EdgeInsets? margin;
  final Function(String text)? onChanged;
  final TextEditingController? controller;
  final TextInputType keyboardType;
  final Color backgroundColor;
  final double height = (20 + 20);
  final double? width;

  /// Constructor
  Input({
    Key? key,
    this.maxLines = 1,
    this.hintText,
    this.hintSize = Label.defaultFontSize,
    this.hintStyle = Label.defaultFontStyle,
    this.hintWeight = Label.defaultFontWeight,
    this.hintFamily = Label.defaultFontFamily,
    this.margin,
    this.onChanged,
    this.controller,
    this.keyboardType = TextInputType.text,
    this.backgroundColor = Palette.greyCultured,
    this.width
  }): super(key: key);

  @override
  Widget build(BuildContext context) {

    // Return widget
    return Container(
      margin: this.margin,
      width: this.width,
      height: this.height,
      decoration: BoxDecoration(
        color: this.backgroundColor.withOpacity(.5),
        borderRadius: BorderRadius.circular(this.height / 4)
      ),
      child: TextField(
        maxLines: this.maxLines,
        controller: this.controller,
        keyboardType: this.keyboardType,
        onChanged: this.onChanged,
        scrollPadding: EdgeInsets.zero,
        decoration: InputDecoration(
          isDense: true,
          border: InputBorder.none,
          contentPadding: EdgeInsets.symmetric(
            vertical: 10,
            horizontal: 10,
          ),
          hintText: this.hintText,
          // Setting style to the hint
          hintStyle: TextStyle(
            fontSize: this.hintSize,
            fontStyle: this.hintStyle,
            fontWeight: this.hintWeight,
            fontFamily: this.hintFamily,
          ),
        ),
      ),
    );
  }
}
```
<details>
  <summary>flutter doctor -v</summary>

```terminal
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-BR)
    • Flutter version 2.2.1 at /Library/Developer/Flutter
    • Framework revision 02c026b03c (3 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/davidgaspardev/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/davidgaspardev/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • XT1022 (mobile)            • 0428641352                           • android-arm • Android 4.4.4 (API 19)
    • iPhone 12 Pro Max (mobile) • 6601D386-283D-4D23-8A5D-F38D59F30E78 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)

• No issues found!
```
</details>

**Comment by westdabestdb** [comment]
@JulienMalige It's still happening here on MacOS.

**Comment by MSatyam-Mishra** [comment]
it was working perfectly but in one project its not working
