### ISSUE TITLE
Index out of range, When selecting the EngineOpenGL

### ISSUE THREAD

**Issue by rodolfoaguiar** [go-flutter-desktop/go-flutter#32]
Hi, I made a app to receive data from internet (on the flutter side) and persist on the SQLite  (using the JSONMessageCodec and the pluginReceiver) but I'm receiving this error sometimes when the memory  usage exceeds 200mb

> panic: runtime error: index out of range
goroutine 17 [running, locked to thread]:
github.com/Drakirus/go-flutter-desktop-embedder/flutter.proxy_make_current(0x6812490, 0x4320870)
	/go/src/github.com/Drakirus/go-flutter-desktop-embedder/flutter/flutter_proxy_glfw.go:43 +0xd2
github.com/Drakirus/go-flutter-desktop-embedder/flutter._cgoexpwrap_e5bc8fd1c1b7_proxy_make_current(0x6812490, 0x23ff7e00)
	_cgo_gotypes.go:376 +0x2b

Am I doing something wrong?

Thanks.

**Comment by Drakirus** [comment]
No, you are not doing something wrong, it's an embedder crash.  
Can you change this [Line](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/ff753a81e67abc18eca7fe13f58c54240116818b/flutter/flutter_proxy_glfw.go#L43) to `return C.bool(flutterEngines[0].FMakeCurrent(v))`, and see if the error still occurs?

Also, "when the memory usage exceeds 200mb", you are speaking of the embedder's memory usage? (or SQLite, ..?)

**Comment by rodolfoaguiar** [comment]
Thanks for your help.

I changed the code but now I have the same error on the 57 line
`
return C.bool(flutterEngines[index].FPresent(v))
`

I tried to change to index 0 too but the error persist 

`
return C.bool(flutterEngines[0].FPresent(v))
`

> panic: runtime error: index out of range
> 
> goroutine 17 [running, locked to thread]:
> github.com/Drakirus/go-flutter-desktop-embedder/flutter.proxy_present(0x6901fa0, 0x43208b0)
> 	/Users/rodolfoaguiar/go/src/github.com/Drakirus/go-flutter-desktop-embedder/flutter/flutter_proxy_glfw.go:57 +0xd2
> github.com/Drakirus/go-flutter-desktop-embedder/flutter._cgoexpwrap_a100b3ae5f80_proxy_present(0x6901fa0, 0x69169a0)
> 	_cgo_gotypes.go:402 +0x2b


Any ideias ?

About the memory, I was speaking about the embedder's memory.

Thanks.

**Comment by Drakirus** [comment]
I managed to reproduce the error on linux, I don't thinks it's related to the process memory used.  

The [EngineOpenGL](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/eba787891c74796a014acf3f2d5ba201a9ab3e82/flutter/flutter.go#L39) is stored [globally](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/eba787891c74796a014acf3f2d5ba201a9ab3e82/flutter/flutter.go#L15) at the moment.
This error might come from the Golang Memory management.

**Comment by rodolfoaguiar** [comment]
Thanks for your help

**Comment by GeertJohan** [comment]
@rodolfoaguiar Can you please try if this problem still occurs with the most recent version of this package? Make sure to update both the go-getted package (`go get -u -a github.com/Drakirus/go-flutter-desktop-embedder`) and any sources you have manually cloned.

If this problem still occurs, can you share a standalone project that reproduces the issue, so I may try to debug this.

**Comment by GeertJohan** [comment]
Without more information it's hard for us to reproduce the described behaviour. Also, a lot has changed in the way engine lookups work, and some bugs that may have caused this error were fixed. Please open a new issue if the problem still occurs with the latest version of go-flutter.
