### ISSUE TITLE
hover not finding my flutter install.

### ISSUE THREAD

**Issue by kenthinson** [go-flutter-desktop/go-flutter#323]
Hello. I have been using hover for a few days to make a app without issue. Today I started up my computer and I see this 
```
hover: Failed to lookup 'flutter' executable. Please install flutter.
https://flutter.dev/docs/get-started/install
```
flutter is installed and in my path
```
flutter doctor -v
[✓] Flutter (Channel beta, v1.12.13+hotfix.2, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.12.13+hotfix.2 at /Users/kent/Developer/flutter
    • Framework revision 4f54e46f56 (28 hours ago), 2019-12-04 09:20:18 -0800
    • Engine revision 6955b06ced
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kent/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Please advise thanks.

**Comment by pchampio** [comment]
Your shell binary path might be not linked to your system path.
Are you sure flutter is in your path? 

I guess you can try to craft a small golang binary which calls the flutter command. Then you will have to look at the error value

**Comment by kenthinson** [comment]
Figured out that if I change shell I can get it to work. Closing thanks.

**Comment by ShiinaOrez** [comment]
I face the same situation now: Flutter in my PATH, but when I run the cmd [hover run], it will remind me I need to install flutter... why hover cannot find my flutter? I want to now the reason.

**Comment by ShiinaOrez** [comment]
It's strange. I wrote a simple golang program that import "os/exec" and execute "env" and "flutter create xxx". The "env" command output the PATH variable (include flutter path!), but the "flutter create xxx" command still failed with "flutter not installed".
Please teach me how to link my shell binary path to system path. @pchampio

**Comment by ShiinaOrez** [comment]
figure it out.
Just link flutter to /usr/local/bin by `sudo ln -s YOUR-FLUTTER-PATH/flutter/bin/flutter /usr/local/bin`

**Comment by mesabo** [comment]
If you're on ubuntu after downloaded go into you /home folder, export on your path:
sudo nano ~/.bashrc and paste like

> export PATH="/usr/local/go/bin:$PATH"

> export PATH="/home/your-name/go/bin/:$PATH"
