### ISSUE TITLE
[Question] How to use MethodChannel for invoking golang func

### ISSUE THREAD

**Issue by tdh8316** [go-flutter-desktop/go-flutter#330]
Hi, I'm a newbie for this project.
I'd like to call functions written in Golang. In mobile flutter, I could invoke native functions via `MethodChannel`.

But I have no idea if `go-flutter` has MethodChannel, and how can I use it.

Can anyone provide an example of MethodChannel of `go-flutter`?

It'd be cool if this project has a well-organized document!

**Comment by jld3103** [comment]
Here is a plugin example: https://github.com/go-flutter-desktop/examples/tree/master/plugin_tutorial. You can use it like any normal plugin using MethodChannels.

**Comment by tdh8316** [comment]
Thank you for letting me know!

**Comment by pchampio** [comment]
> It'd be cool if this project has a well-organized document!

Please refer to our [wiki](https://github.com/go-flutter-desktop/go-flutter/wiki)
