### ISSUE TITLE
Crash happens when delete characters of a unicode string, such as "🍷hello🎤world🤗"

### ISSUE THREAD

**Issue by zhileichen** [go-flutter-desktop/go-flutter#332]
## Environment
```
Windows 10
go-flutter v0.34.0
```

## Step to Repreduce 

1. Copy the sample string  "🍷hello🎤world🤗" into a **TextField**
2. Click **Backspace** key in the keyboard to delete any character
3. Then the crash happens

## Go Error
```
runtime.boundsError
runtime error: slice bounds out of range [4:3]
```

## Go Stacktrace
```
textinput-model.go in (*textinputPlugin).addChar at line 27
textinput.go in (*textinputPlugin).glfwCharCallback at line 137
input.go in goCharCB at line 295
_cgo_gotypes.go in _cgoexpwrap_173d98a40ae9_goCharCB at line 2120
_cgo_gotypes.go in _Cfunc_glfwWaitEventsTimeout at line 1985
window.go in WaitEventsTimeout at line 823
application.go in (*Application).Run.func11 at line 331
event-loop.go in (*EventLoop).WaitForEvents at line 124
application.go in (*Application).Run at line 330
application.go in Run at line 27
main.go in main at line 53
```

**Comment by pchampio** [comment]
Flutter ([source](https://github.com/flutter/flutter/blob/ab36346af6e6c61ab4174c753b1ec3f3260fa56a/packages/flutter/lib/src/services/text_formatter.dart#L142-L166)) and golang (through `[]rune`) have a different ways of handling index in text that have emoji.

I think using something like https://github.com/tmdvs/Go-Emoji-Utils can be a great help.

Btw, are you seeing the emoji on your app? (on mine it just shows up as a invalid character ▯)

**Comment by pchampio** [comment]
https://github.com/tmdvs/Go-Emoji-Utils/blob/47a2e1776a742286b6766c73a3ad153ee0f2ceb4/search.go#L56

**Comment by pchampio** [comment]
As keyboard shortcut (like `backspace`) might be handled in the framework side https://github.com/go-flutter-desktop/go-flutter/issues/314, I think we should wait.
If keyboard gets rolled to channel beta, we will adapt our embedder.

**Comment by pchampio** [comment]
Dart inaccuracy calculate the RuneLen in the presence of those characters. The Dart lang bug https://github.com/dart-lang/sdk/issues/28404 has been filed to address this in Dart.

Btw, are you seeing the emoji on your app? (on mine it just shows up as a invalid character ▯)
