### ISSUE TITLE
Flutter draggable widget does not work on Windows desktop

### ISSUE THREAD

**Issue by Murtuzakabul** [go-flutter-desktop/go-flutter#333]
## Hover doctor
hover: Running on windows
hover: Docker installed: false
hover: Sharing flutter version
Flutter 1.12.13+hotfix.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 18cd7a3601 (3 weeks ago) • 2019-12-11 06:35:39 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
hover: Flutter engine commit: https://github.com/flutter/engine/commit/2994f7e1e6
hover: Finding out the C compiler version
gcc (tdm64-1) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO 
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

hover: Sharing the content of go.mod
module github.com/my-organization/simpleApplication/go

go 1.13

require (
        github.com/go-flutter-desktop/go-flutter v0.33.0
        github.com/go-gl/glfw v0.0.0-20191125211704-12ad95a8df72 // indirect
        github.com/miguelpruivo/plugins_flutter_file_picker/go v0.0.0-20191117141101-23934697c1ad
        github.com/pkg/errors v0.8.1
)
hover: Sharing the content of hover.yaml
target: lib/main_desktop.dart
branch: ""
cache-path: ""
opengl: ""
docker: false
hover: Sharing the content of go/cmd
go\cmd\main.go  go\cmd\options.go

## Error output

No errors are being displayed

Tried out the draggable component of flutter which does not seem to work on desktop (Windows). Probably it might not work for Mac and Linux too.

**Comment by pchampio** [comment]
Can you share a simple main.dart file that reproduce this error?

**Comment by pchampio** [comment]
Without additional information, we are unfortunately not sure how to resolve
this issue. We are therefore reluctantly going to close this bug for now. Please
don't hesitate to comment on the bug if you have any more information for us; we
will reopen it right away!
Thanks for your contribution.
