### ISSUE TITLE
Crash happens when i run the exe on the virtual machine which os is windows7 x64,the os is just new installed,how can i make it running,any other files needed?

### ISSUE THREAD

**Issue by nbwithlb** [go-flutter-desktop/go-flutter#337]
anything the running environment needed?

**Comment by pchampio** [comment]
Its not possible to run the app on a VM. This has already been attempted, and it has failed.

Out of curiosity, what is your host OS? 
Which VM toolkit are you using?

**Comment by pchampio** [comment]
duplicate: https://github.com/go-flutter-desktop/go-flutter/issues/272
