### ISSUE TITLE
Go-flutter: no handler found for channel

### ISSUE THREAD

**Issue by nadimgouia** [go-flutter-desktop/go-flutter#346]
Am working on desktop with flutter, and am using connectivity, path_provider packages in my project, and everything was good, until i added hover and  go-flutter.
I added hover to my project, because i need file_picker plugins, and it doesnt work on desktop without it.  
Now i have the file_picker plugin works fine but the other plugins (connectivity and path_provider) dont work any more, 

## Error output

Using `hover build [...] --XXX` to build my application, I get the following
error:

```log
go-flutter: no handler found for channel plugins.flutter.io/connectivity
go-flutter: no handler found for channel plugins.flutter.io/connectivity_status
go-flutter: no handler found for channel plugins.flutter.io/path_provider
[...]
```
## Hover doctor

```log
hover: Running on darwin
hover: Docker installed: true
hover: Sharing flutter version
Flutter 1.14.1-pre.23 • channel master • https://github.com/flutter/flutter.git
Framework • revision f34bb03d89 (7 days ago) • 2020-01-15 23:57:05 -0500
Engine • revision 09d892b3bf
Tools • Dart 2.8.0 (build 2.8.0-dev.2.0 862d5012ae)
hover: Flutter engine commit: https://github.com/flutter/engine/commit/09d892b3bf
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Finding out the C compiler version
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
hover: Sharing the content of go.mod
module flutter_desktop/go

go 1.13

require (
	github.com/go-flutter-desktop/go-flutter v0.34.1
	github.com/miguelpruivo/flutter_file_picker/go v0.0.0-20191218104902-b68ee11c6ac1
	github.com/pkg/errors v0.9.1
)
hover: Sharing the content of hover.yaml
target: lib/main_desktop.dart
branch: ""
cache-path: ""
opengl: ""
docker: false
hover: Sharing the content of go/cmd
go/cmd/main.go	go/cmd/options.go
```

**Comment by pchampio** [comment]
Please share the output of `hover doctor`.
Read this wiki section: https://github.com/go-flutter-desktop/go-flutter/wiki/Plugin-info
And checkout the implemented plugin, https://github.com/go-flutter-desktop/plugins.

**Comment by stuartmorgan** [comment]
> until i added hover and go-flutter.
> I added hover to my project, because i need file_picker plugins, and it doesnt work on desktop without it.

It sounds like you were [Flutter's desktop support](https://flutter.dev/desktop) previously? If so, I think the confusion here is that you haven't *added* hover and go-flutter, you've switched from one desktop embedding (the one that's part of the Flutter project) to a different embedding (go-flutter-desktop). The two are completely distinct, and have incompatible plugin ecosystems.

**Comment by nadimgouia** [comment]
> > until i added hover and go-flutter.
> > I added hover to my project, because i need file_picker plugins, and it doesnt work on desktop without it.
> 
> It sounds like you were using [Flutter's desktop support](https://flutter.dev/desktop) previously? If so, I think the confusion here is that you haven't _added_ hover and go-flutter, you've switched from one desktop embedding (the one that's part of the Flutter project) to a different embedding (go-flutter-desktop). The two are completely distinct, and have incompatible plugin ecosystems.

i didnt use any other desktop embedding before in my project, i have normal project and i just executed the cmd : "hover init", after that, all other plugins declared in the pubspec.yaml file stop working. plugin declared in the go/cmd/options.go work. 
when i  execute "hover run" i get this message: 
"go-flutter: no handler found for channel plugins.flutter.io/plugin_name_here" (example connectivity)

**Comment by stuartmorgan** [comment]
> i didnt use any other desktop embedding before in my project, i have normal project

Embeddings aren't part of your project, they are the layer between the OS and the Flutter engine. Any time you run your project before, you are using some embedding. If you previously used `flutter run` you were using an embedding that is part of the Flutter project. When you use `hover` you are using this project's embedding instead.

The embedding is also the layer that provides the plugin API, which is why the plugins aren't interoperable.

**Comment by pchampio** [comment]
Closing this issue, go-flutter provide an implementation for path_provider. connectivity and connectivity_status are still missing.

**Comment by Shree-hari** [comment]
go-flutter: no handler found for channel miguelruivo.flutter.plugins.filepicker
I found this issue and am not able to solve it
Please help
