### ISSUE TITLE
Colored log doesn't work on windows

### ISSUE THREAD

**Issue by jld3103** [go-flutter-desktop/go-flutter#348]
The colored log doesn't work on windows and prints a lot of garbage symbols.
We should disable it on windows by default.

**Comment by jld3103** [comment]
Umm sometimes it works sometimes not.

**Comment by jld3103** [comment]
Solution: https://github.com/logrusorgru/aurora/issues/2#issuecomment-299014211

**Comment by altermark** [comment]
At the start `hover` should set a windows console flag that enables processing of escape sequences. 

See https://docs.microsoft.com/en-us/windows/console/setconsolemode

If it does not, the flag will be set later in the run/build process by 
flutter tooling. Colors then seem to appear only in later log messages.

![hover_partial_colors](https://user-images.githubusercontent.com/49390312/85196715-709b5a00-b2dc-11ea-95a7-e3c432440fd5.png)

I was able to fix the issue for me using modified `hover/main.go`.

![hover-modified](https://user-images.githubusercontent.com/49390312/85196751-958fcd00-b2dc-11ea-9d68-ab3f6b9827c3.png)

	package main

	import (
		"github.com/go-flutter-desktop/hover/cmd"

		"golang.org/x/sys/windows"
		"syscall"
		"log"
	)

	func SetColorConsole() {
		var console_handle syscall.Handle
		var err error

		console_handle, err = syscall.Open("CONOUT$", syscall.O_RDWR, 0)
		if err != nil {
			log.Println("Error getting console handle:", err)
			return
		} 

		var mode uint32
		err = windows.GetConsoleMode(windows.Handle(console_handle), &mode)
		if err != nil {
			log.Println("Error getting console mode:", err)
			return
		}
		err = windows.SetConsoleMode(windows.Handle(console_handle), mode | windows.ENABLE_VIRTUAL_TERMINAL_PROCESSING)
		if err != nil {
			log.Println("Error setting console mode:", err)
			return
		}
	}

	func main() {
		SetColorConsole()
		cmd.Execute()
	}

I'd rather let someone more knowledgeable to do proper integration...

**Comment by jld3103** [comment]
I don't have a lot of experience with windows so I guess you are the one with proper knowledge. Could you make a PR with your changes?

**Comment by altermark** [comment]
OK, I'll try and not mess up other operating systems.

**Comment by jld3103** [comment]
Fixed in https://github.com/go-flutter-desktop/hover/pull/154. Thanks @altermark
