### ISSUE TITLE
Update path_provider plugin

### ISSUE THREAD

**Issue by jld3103** [go-flutter-desktop/go-flutter#351]
The `path_provider` got updated a lot in recent times and got some new functions and even desktop exclusives. We need to update the plugin accordingly.
https://github.com/flutter/plugins/blob/master/packages/path_provider/lib/path_provider.dart
When I have time I'll create a PR in the next days.

**Comment by pchampio** [comment]
@jld3103 what is your plan for the PR?
I've looked at the new channels [method_channel_path_provider.dart](https://github.com/flutter/plugins/blob/c03166bc12791bebc172b63259bd7200c052187e/packages/path_provider/path_provider_platform_interface/lib/src/method_channel_path_provider.dart#L29) some of them could indeed be merged into the plugin.

Some links:
https://github.com/golang/go/issues/29960

**Comment by jld3103** [comment]
I didn't work on that, because the project I needed it for was changed in a way that the plugin was no longer in use, but I could actually update the plugin in the next days.
