### ISSUE TITLE
Cannot run on a Windows 7 host remotely logged on using mstsc

### ISSUE THREAD

**Issue by ContainsK** [go-flutter-desktop/go-flutter#352]
I have no problem running on my windows 10.
I doubt it's OpenGL's problem. How can I solve it?

**Comment by pchampio** [comment]
Is the machine you are connecting to a virtual machine?

**Comment by ContainsK** [comment]
> 您正在连接到虚拟机的计算机吗？

It's not a virtual machine's computer. It's another physical machine. I connect it through mstsc

**Comment by ContainsK** [comment]
> Is the machine you are connecting to a virtual machine?

It's not a virtual machine's computer. It's another physical machine. I connect it through mstsc

**Comment by pchampio** [comment]
When using this physical machine without mstsc, does it work?

**Comment by ContainsK** [comment]
> When using this physical machine without mstsc, does it work?

Yes, it can't be used on mstsc .

**Comment by pchampio** [comment]
I'm sorry, but I have no intention to work on this issue.
Here is a stackoverflow.com post you might want to read https://stackoverflow.com/questions/51705471/current-state-and-solutions-for-opengl-over-windows-remote

If others people are facing the same problem, please report it on this issue, someone might have a solution to this issue.

**Comment by pchampio** [comment]
Closing this issue, "OpenGL and Windows Remote don't play along nicely." and since go-flutter uses OpenGL. mstsc is simply not compatible with go-flutter.
