### ISSUE TITLE
How to support debugging Android studio plug-ins ?

### ISSUE THREAD

**Issue by ContainsK** [go-flutter-desktop/go-flutter#353]
How can I debug my desktop app like a mobile app in Android studio, so that I can use the plugins "flutter inspector" and "flutter outline"

**Comment by pchampio** [comment]
From what I currently know, this isn't possible at the moment. https://github.com/flutter/flutter-intellij/issues/2250
Somewhat duplicate of https://github.com/go-flutter-desktop/go-flutter/issues/213

**Comment by pchampio** [comment]
This isn't something the go-flutter can work on.
The flutter plugin on android studio is less polished than the one on vs-code.
