### ISSUE TITLE
Image Widget freeze latest windows 10 64bit

### ISSUE THREAD

**Issue by madestuff** [go-flutter-desktop/go-flutter#356]
The Flutter Image Widget freeze on my windows 10 laptop.
The application just freeze and there is no error log.

Seems to be the displaying of an image, since all "versions" freeze - assets, url etc.
Test-app ist just the helloworld flutter app with an image widget.

The application was build on another windows 10 pc with latest flutter and flutter go / hover and runs there just fine.

Hardware : i7 6700hq, nvidia gtx 960m
The resolution does not affect the freezing and sometimes it does work just as normal.
Also there is no software installed hooking/modifying the graphic card output.

**Comment by pchampio** [comment]
Can you create a debug version of your application, `hover build windows --debug`.
Then can you run it using the cmd and check if there is log printed?

Can you also try an older version of flutter? Maybe `flutter version v1.9.1-hotfixes` works.

**Comment by itMicmouse** [comment]
I have the same problem  
<img width="1082" alt="D7D2C326-8526-4F6E-8D82-6C6C415C220E" src="https://user-images.githubusercontent.com/14135612/74703651-d1405a80-5248-11ea-9a8c-167dcdf94650.png">
<img width="365" alt="B4901930-9636-4EA4-AC8B-B59DBBBEE7F2" src="https://user-images.githubusercontent.com/14135612/74703719-0e0c5180-5249-11ea-9b86-208ac0bcfdbd.png">

**Comment by chengxuncc** [comment]
Same problem for me.
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.15.3, on Microsoft Windows [Version 10.0.19551.1005], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[!] VS Code, 64-bit edition (version 1.41.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Proxy Configuration
[√] Connected device (1 available)
```
I test commits of `go-flutter` master branch one by one, successfully run on commit `e989718 docs: update Mac OS CGO_LDFLAGS for embedder readme (#305)`, but it won't work after `62fe831 Bugfix/texture thread (#304)`, hope this helps.

**Comment by pchampio** [comment]
Does `hover run --opengl=none` works?

**Comment by chengxuncc** [comment]
> Does `hover run --opengl=none` works?

Yes, it work.

**Comment by pchampio** [comment]
When you remove the `opengl.GLFWWindowHint()` line, everything works?
I'm talking about the one in `createResourceWindow` not in ``
https://github.com/go-flutter-desktop/go-flutter/blob/d57ad2bcb4c4dcd434d628e2db6a12341f6989a4/application.go#L70-L71
not the one in `(a *Application) Run()`
https://github.com/go-flutter-desktop/go-flutter/blob/d57ad2bcb4c4dcd434d628e2db6a12341f6989a4/application.go#L107-L111

**Comment by pchampio** [comment]
Fixed in `v0.35.2`

**Comment by chengxuncc** [comment]
How could I make sure everything works? There should be an app for testing kinds of functions.

**Comment by pchampio** [comment]
https://github.com/go-flutter-desktop/examples/tree/master/texture_tutorial

**Comment by chengxuncc** [comment]
`texture_tutorial` is not using `Image.asset()`.

**Comment by chengxuncc** [comment]
When `draggable_borderless` uses `Image.asset()`, It works. This is different.

**Comment by pchampio** [comment]
Since the fix affected texture I wanted to test if the `texture_tutorial` was sitll working.
I'm kinda in a rush ATM, I don't have an example with `Image.asset()`, but I thinks it's not that complicated to create.

Nevertheless, big thanks for going through the process of finding the commit that created this regression. :+1: :fireworks:.

I hope it works^^
