### ISSUE TITLE
Hover: remove the assumption that the go dir is the project root for golang tooling

### ISSUE THREAD

**Issue by james-lawrence** [go-flutter-desktop/go-flutter#357]
currently hover assumes that it controls go.mod, it generates one and then looks for it in a specific location.

this is relatively undesirable because it forces the end user to a specific directory tree or to run into issues dealing with golangs vendor tooling for private repositories.

we should be able to remove this assumption by letting the standard go tooling find the go.mod file.

some relevant documentation:

[module file parser](https://godoc.org/golang.org/x/mod/modfile)
[how to find the module file](https://github.com/golang/go/blob/88e564edb13f1596c12ad16d5fd3c7ac7deac855/src/cmd/dist/build.go#L1595)

**Comment by pchampio** [comment]
If you want to add this feature to hover, I can assign you to this task!

**Comment by james-lawrence** [comment]
I'll gladly help out with it. mainly filed so it was on the radar and if anyone else has ideas towards its implementation they wish to add.
