### ISSUE TITLE
missing text handles

### ISSUE THREAD

**Issue by james-lawrence** [go-flutter-desktop/go-flutter#358]
I have a text input box for sensitive information that has a hide/display button that transforms the text.

the text fails to change due to missing handlers.

```
go-flutter: no method handler registered for method 'TextInput.setEditableSizeAndTransform' on channel 'flutter/textinput'
go-flutter: no method handler registered for method 'TextInput.setStyle' on channel 'flutter/textinput'
```

couple of related issues:
#355 
#354

**Comment by stuartmorgan** [comment]
> the text fails to change due to missing handlers.

The only bug related to those log messages is the logging itself; see https://github.com/flutter/flutter/issues/49960 for relevant discussion from the macOS Flutter embedding.

Whatever functionality issues you are seeing, they aren't related to those log messages.
