### ISSUE TITLE
Transparent background Option

### ISSUE THREAD

**Issue by ghost** [go-flutter-desktop/go-flutter#364]
I'm adding window shadow, however, it seems that init background color is black, I can't make it look like shadow but fat black line.

**Comment by ShinyV** [comment]
It only support `glfw.TransparentFramebuffer` Hint on go-gl/glfw 3.3.

**Comment by ShinyV** [comment]
Insert a line to [flutter.Run()](https://github.com/go-flutter-desktop/go-flutter/blob/512489aa1e6aabd7b33ddde932c13dde2dc5706b/application.go#L97):
```
glfw.WindowHint(glfw.TransparentFramebuffer, glfw.True)
```

**Comment by GeertJohan** [comment]
This sounds like something that could be an `Option`.

**Comment by Kassan424kh** [comment]
hi,

how can i use it in my app, could anyone help please

**Comment by pchampio** [comment]
@Kassan424kh 
https://github.com/go-flutter-desktop/go-flutter/wiki/Options
```
flutter.WindowTransparentBackground(true)
```

**Comment by Kassan424kh** [comment]
@pchampio Thank you very much 💪
