### ISSUE TITLE
Building examples resolves an error "GLFW"

### ISSUE THREAD

**Issue by younlok** [go-flutter-desktop/go-flutter#368]
## Hover doctor

```
$ hover doctor
hover: Running on linux
hover: Docker installed: true
hover: Sharing flutter version
[...]
```

## Error output
creating glfw window: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig
hover: App 'stocks' exited with error: exit status 1

**Comment by pchampio** [comment]
Does `hover run -b '@v0.35.1'` works

**Comment by younlok** [comment]
this give me this 
 21 % / 100 %hover: Failed to download artifacts: read tcp 192.168.1.8:37398->216.58.205.80:443: read: connection reset by peer

**Comment by younlok** [comment]
i geet this error 
`So, because stocks depends on intl 0.16.0, version solving failed.
pub get failed (1; So, because stocks depends on intl 0.16.0, version solving failed.)
hover: Flutter build failed: exit status 1
`

what is intl ?? sorry i am new to flutter :/
also thank for your time

**Comment by pchampio** [comment]
Try another example.

**Comment by younlok** [comment]
same problem

**Comment by pchampio** [comment]
which problem?
using which hover command? `hover run -b '@v0.35.1'` ;)

**Comment by younlok** [comment]
`creating glfw window: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig
hover: App 'keyboard_event' exited with error: exit status 1`

and yes with 
`hover run -b '@v0.35.1'`

**Comment by pchampio** [comment]
Can you try with `hover run -b '@v0.35.3'`

**Comment by younlok** [comment]
`creating glfw window: VersionUnavailable: EGL: Failed to create context: Arguments are inconsistent
hover: App 'keyboard_event' exited with error: exit status 1
`

**Comment by younlok** [comment]
`hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
hover: Downloading 'go-flutter' @v0.35.3
go: finding github.com/go-gl/glfw latest
go: finding github.com/go-gl/gl latest
hover: 'go-flutter' is on version: v0.35.3
hover: Failed to retrieve the organization name: open android/app/src/main/AndroidManifest.xml: no such file or directory
hover: Compiling 'go-flutter' and plugins
hover: Successfully compiled
hover: Build finished, starting app...
hover: Running keyboard_event in debug mode
creating glfw window: VersionUnavailable: EGL: Failed to create context: Arguments are inconsistent
hover: App 'keyboard_event' exited with error: exit status 1
`

**Comment by pchampio** [comment]
Does `go run test.go` works,
test.go is a file with the following content:
```go
package main

import (
	"runtime"

	"github.com/go-gl/glfw/v3.3/glfw"
)

func init() {
	// This is needed to arrange that main() runs on main thread.
	// See documentation for functions that are only allowed to be called from the main thread.
	runtime.LockOSThread()
}

func main() {
	err := glfw.Init()
	if err != nil {
		panic(err)
	}
	defer glfw.Terminate()

	glfw.WindowHint(glfw.ContextCreationAPI, glfw.EGLContextAPI)
	window, err := glfw.CreateWindow(640, 480, "Testing", nil, nil)
	if err != nil {
		panic(err)
	}

	window.MakeContextCurrent()

	for !window.ShouldClose() {
		// Do OpenGL stuff.
		window.SwapBuffers()
		glfw.PollEvents()
	}
}
```

**Comment by younlok** [comment]
yes it works i get a black screen and alright

**Comment by pchampio** [comment]
Je think the error comes from an openGL driver.
Can you try `hover run -b '@v0.35.3' --opengl=None`

**Comment by younlok** [comment]
worked cool ty 
but the stocks project still doesn't work can you tell me why (just curiosity )

**Comment by pchampio** [comment]
Cool!

> but the stocks project still doesn't work can you tell me why (just curiosity )

Just a flutter dependency stuff, you can update it by changing [this](https://github.com/go-flutter-desktop/examples/blob/34585bad11bac7390b7b5441ecb4afadfc8f0f54/stocks/pubspec.yaml#L13) line.
