### ISSUE TITLE
[feature-request] Custom name for AppImage and Snap

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [go-flutter-desktop/go-flutter#372]
## Is your feature request related to a problem?

Nope.

## Describe the feature you'd like

It would be great if I could specify the final executable name for the build application.

E.g. my dart project's name is `my_test_application` then the built AppImage executable is currently just named `my_test_application.AppImage` too. It would be great if this was adjustable somewhere. Same applies for Snaps.

**Comment by jld3103** [comment]
That's definitely a thing that is easily possible, but I'd like to wait for https://github.com/go-flutter-desktop/hover/pull/73, because then we have a new packaging structure and it's going to be a lot cleaner. I imagine renaming the executable would also be nice for more packaging formats than app image and snap

**Comment by JasMich** [comment]
For those others it already is possible by renaming the `go/packaging/linux-*[...]/usr/bin/my_executable`.

**Comment by jld3103** [comment]
I will work on this in the next days. My idea was to add two fields for `binary_name` and `app_name` in the [hover project config file](https://github.com/go-flutter-desktop/hover/blob/master/assets/app/hover.yaml).
@TheOneWithTheBraid @pchampio what do you think about that approach?

**Comment by jld3103** [comment]
I think also an `author` field would be good.

**Comment by GeertJohan** [comment]
So `binary_name` is the name of the actual executable inside the package, and `app_name` is the name of the package file?

If app name only defines the name of the outputted file, maybe we shouldn't add that to hover and just let it be a `mv` executed by the user or CI?

Having a value to change the name of the binary during/after the build process sounds good to me. I think it should affect both build (without packaging) and packaging. So it's done at the end of build, not at the start of packaging.
To keep things clean I would suggest to have just a single override. If we allow different binary names for each target/packaging hover provides.

I think that when we're developing features like these, breaking and changing flags is easier and has less impact for our users than breaking config, so it'd be nice if we can first experiment with flags. And if we have used those for a while and we like how they work, we can add them to config. Of course even if they're in config I would think the flag can still be used to override the config value.

So to use dart-escue notation:
```
binary_name = ( flags.binary_name ?? config.binary_name ?? pubspec.name )
```

Concerning the `author` field: Can't we use the value from pubspec.yaml? In what scenario is the author for the hover-built app different than the author for the flutter-built app?
Also: The author value is already copied to the generated files by `init-packaging`, if we want the changed config to be reflected in packaged apps, we should make the value templated like `Version: {{.version}}`. At the same time, one could say that not having the value templated is precicely how one can modify the author value differently for each packaging method.

**Comment by jld3103** [comment]
> If app name only defines the name of the outputted file, maybe we shouldn't add that to hover and just let it be a mv executed by the user or CI?

That wouldn't work, because some packaging formarts needs to know the name of the executable.

> Concerning the author field: Can't we use the value from pubspec.yaml? In what scenario is the author for the hover-built app different than the author for the flutter-built app?

The author field is necessary for some packaging formats, but the pubspec author field is not necessary and hover defaults to the username of the system.

> Also: The author value is already copied to the generated files by init-packaging, if we want the changed config to be reflected in packaged apps, we should make the value templated like Version: {{.version}}. At the same time, one could say that not having the value templated is precicely how one can modify the author value differently for each packaging method.

I already implemented that.

I don't know how to proceed exactly, but I would propose to make a PR with my changes and if they are acceptable they can be merged. I'll add the flags, but make the config file entries not mandatory. Like you said we can make them mandatory later.

**Comment by jld3103** [comment]
Also I added an `packageName` field for the name of the package app.

**Comment by GeertJohan** [comment]
> That wouldn't work, because some packaging formarts needs to know the name of the executable.

Sorry, I meant the outputted packaged file (dmg, appimage, etc), not the executable.

**Comment by TheOneWithTheBraid** [comment]
Thank you!
