### ISSUE TITLE
Save the pos and size of the app automatically

### ISSUE THREAD

**Issue by leedstyh** [go-flutter-desktop/go-flutter#381]
Hi, I wanna save the pos and size of the app. And tried to write a plugin with the code like this:

```
glfw.Init()
window := glfw.GetCurrentContext()
var x, y = window.GetPos()
var w, h = window.GetSize()
```

But no luck, window is `nil` all the time.

So can this feature be built into the go-flutter(save automatically when I move/resize the app), or any hints to do this?

Thanks

**Comment by pchampio** [comment]
You can interact with the glfw window through GLFWPlugin, here are multiple examples: https://github.com/go-flutter-desktop/go-flutter/issues/181#issuecomment-508308348 |  [WIKI](https://github.com/go-flutter-desktop/go-flutter/wiki/GLFW-Plugin-example) | https://github.com/go-flutter-desktop/go-flutter/issues/267 | [Tips-and-tricks#4](https://github.com/go-flutter-desktop/go-flutter/wiki/Tips-and-tricks#4-save-the-windows-mode-fullscreen-or-default)

**Comment by leedstyh** [comment]
Thanks @pchampio works like a charm
