### ISSUE TITLE
locale.languageCode always returns 'en' on Linux

### ISSUE THREAD

**Issue by alex-min** [go-flutter-desktop/go-flutter#387]
Hi,

I'm running my project on an Linux distribution where english isn't the main language. It seems the go-flutter-desktop doesn't read the "LANG" env variable before starting the app and the app is incorrectly using english on the localizationsDelegates.

This is a very simple issue I think and I would be very happy to contribute a PR myself if someone would provide some pointers on how to fix it.

I see there's some FlutterEngineUpdateLocales C call but I'm not sure if that's what I should use for that. Please let me know if you have some insights.

## Hover doctor

```
hover: Running on linux
hover: Docker installed: true
hover: Sharing flutter version
Flutter 1.12.13+hotfix.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 18cd7a3601 (il y a 4 mois) • 2019-12-11 06:35:39 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
hover: Flutter engine commit: https://github.com/flutter/engine/commit/2994f7e1e682039464cb25e31a78b86a3c59b695
hover: Finding out the C compiler version
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

hover: Sharing the content of go.mod
module project/go

go 1.14

require (
        github.com/davidmartos96/go-flutter-plugin-sqlite v0.0.0-20200129162105-68dfe5aa4b3e
        github.com/go-flutter-desktop/go-flutter v0.36.1
        github.com/go-flutter-desktop/plugins/shared_preferences v0.4.3
        github.com/nealwon/go-flutter-plugin-sqlite v0.0.0-20190909095325-db6bdfd6b983
        github.com/pkg/errors v0.9.1
)
hover: Sharing the content of hover.yaml
target: lib/main_desktop.dart
branch: ""
cache-path: ""
opengl: ""
engine-version: ""
docker: false
hover: Sharing the content of go/cmd
go/cmd/main.go  go/cmd/navbarheight     go/cmd/options.go

```

**Comment by pchampio** [comment]
Sure, I'll be happy to have you contribute onto the project.
I think the engine C call to `FlutterEngineUpdateLocales` should fix this issue.
Here are some pointer for you:
* [arguments to provide to `FlutterEngineUpdateLocales`](https://github.com/flutter/engine/blob/c5329ef5c42a4b55b03ab7b84f1cbcecf43baf7d/shell/platform/embedder/embedder.h#L840-L862)
* [example of usage (from the unittests)](https://github.com/flutter/engine/blob/ff62dec5c96d3560b36ca0a3924d28a3c97b7788/shell/platform/embedder/tests/embedder_unittests.cc#L2850-L2877)
* [The wiki page that informs you how to work on go-flutter](https://github.com/go-flutter-desktop/go-flutter/wiki/Setting-up-hover-to-use-a-home-made-version-of-'go-flutter')
* [An example of an engine call (with strings)](https://github.com/go-flutter-desktop/go-flutter/blob/a526e1d973c515ebc03d9d5c2737fe6dca64ad56/embedder/embedder.go#L261-L287)  
  > I think we are missing a C.free call here.
* [Where we start the engine (I would expect the call to `FlutterEngineUpdateLocales` must be performed AFTER the engine is started..)](https://github.com/go-flutter-desktop/go-flutter/blob/a526e1d973c515ebc03d9d5c2737fe6dca64ad56/application.go#L245-L246)

**Comment by pchampio** [comment]
Can I assign you to this task?

**Comment by alex-min** [comment]
Thanks a lot, yes you can assign me, I'll try to make that work :)

**Comment by pchampio** [comment]
The locale can be query through `window.locales`
```dart
// This example demos the TextField/SelectableText widget and keyboard
// integration with the go-flutter text backend

import 'package:flutter/material.dart';
import 'dart:ui';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    print(window.locales);
    print(window.locale.languageCode);
    print(window.locale.countryCode);
    print(window.locale.scriptCode);
    return MaterialApp(
      title: 'Flutter Code Sample for testing text input',
      theme: ThemeData(
        // If the host is missing some fonts, it can cause the
        // text to not be rendered or worse the app might crash.
        fontFamily: 'Roboto',
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Hover Example'),
        ),
        body: Text("Local: " + window.locale.toString()),
      ),
    );
  }
}
```
