### ISSUE TITLE
 file was built for unsupported file format on Mac

### ISSUE THREAD

**Issue by carlosbdw** [go-flutter-desktop/go-flutter#39]
GitHub/go-flutter-desktop-embedder/example/simpleDemo/FlutterEmbedder.framework/FlutterEmbedder, file was built for unsupported file format ( 0x56 0x65 0x72 0x73 0x69 0x6F 0x6E 0x73 0x2F 0x43 0x75 0x72 0x72 0x65 0x6E 0x74 ) which is not the architecture being linked (x86_64): GitHub/go-flutter-desktop-embedder/example/simpleDemo/FlutterEmbedder.framework/FlutterEmbedder
Undefined symbols for architecture x86_64:

**Comment by gedw99** [comment]
I tried out the new Downloader in the Demo and had no issues for what it worth.
Have been working many times for me.

@carlosbdw can you give me info on what you did. Env, etc

**Comment by GeertJohan** [comment]
@carlosbdw Is this still an issue for you?

**Comment by GeertJohan** [comment]
@carlosbdw Please re-open if this is still an issue.
