### ISSUE TITLE
China problem

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#392]
github.com/Caijinglong/flutter-go-example/go/cmd imports
	github.com/go-flutter-desktop/go-flutter: module github.com/go-flutter-desktop/go-flutter: Get https://proxy.golang.org/github.com/go-flutter-desktop/go-flutter/@v/list: dial tcp 172.217.24.17:443: i/o timeout
github.com/Caijinglong/flutter-go-example/go/cmd imports
	github.com/pkg/errors: module github.com/pkg/errors: Get https://proxy.golang.org/github.com/pkg/errors/@v/list: dial tcp 172.217.24.17:443: i/o timeout
hover: Go mod tidy failed: exit status 1

Unacceable inside China

**Comment by pchampio** [comment]
Can you report the same issue when you used hover?

**Comment by pchampio** [comment]
does `hover run` works even if you encounter this error?

**Comment by pchampio** [comment]
@jld3103 maybe we should add [this](https://github.com/go-flutter-desktop/hover/blob/1e0fd4b19e2cac8e1b24e7edb1338497d88cbe46/cmd/build.go#L592-L593) line to [cmdGoModTidy](https://github.com/go-flutter-desktop/hover/blob/5c2ae7b20a4211241773970fc8d0c7af61905fde/cmd/common.go#L170) ?

**Comment by jld3103** [comment]
Yes, but I'd like to have in a more general way. Something like a variable for all go command environments

**Comment by jinfagang** [comment]
Basically, nothing to do with hover code, but proxy.google.com does not accessable, change it to github is OK I think. Otherwise this blocks lots of Chienese developer outside of the door.

**Comment by jld3103** [comment]
> @jld3103 maybe we should add [this](https://github.com/go-flutter-desktop/hover/blob/1e0fd4b19e2cac8e1b24e7edb1338497d88cbe46/cmd/build.go#L592-L593) line to [cmdGoModTidy](https://github.com/go-flutter-desktop/hover/blob/5c2ae7b20a4211241773970fc8d0c7af61905fde/cmd/common.go#L170) ?

Hm this makes no sense, because `GOPROXY` already comes from `os.Environ()` if set. So that can't be the problem.

**Comment by jinfagang** [comment]
So any updates on this? I still got timeout in China.

**Comment by pchampio** [comment]
Does
```
$ go env -w GOPROXY=https://goproxy.cn,direct
$ hover run
```
works. Please don't use docker.

**Comment by jinfagang** [comment]
@pchampio Will try it, am not using docker but host device directly.

**Comment by jinfagang** [comment]
@pchampio  No, it doesn't work.

Now my outputs are:

```
hover run
hover: Target file "lib/main_desktop.dart" not found.
hover: Let hover add the "lib/main_desktop.dart" file? 
hover: [y/N]? y
hover: Target file "lib/main_desktop.dart" has been created.
hover:        Depending on your project, you might want to tweak it.
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Building flutter bundle
hover: Using engine from cache
hover: Failed to parse the 'go-flutter' version in go.mod

```
I am a little bit confusion, why a golang package problem can be so compilcated... Any easy way to solve it? Make it useable out of box in China?

**Comment by pchampio** [comment]
```
hover: Failed to parse the 'go-flutter' version in go.mod
```
the error is now different!

> I am a little bit confusion, why a golang package problem can be so compilcated... Any easy way to solve it? Make it useable out of box in China?

Looking at your github traffic, I can tell you that the majority of our user are base in China.
TBH, I think you miss installed golang. (`go env -w GOPROXY=https://goproxy.cn,direct` should be automatically if you reside in china) 

To solve the new issue you encountered, please:
````
# remove the go directory
$ rm -rf go
# re-initialize hover
$ hover init
# run
$ hover run
```

**Comment by jinfagang** [comment]
@pchampio  I think it's due to doesn't delete go directory. Now I got error with GL lib:

```
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Building flutter bundle
hover: Using engine from cache
hover: Failed to retrieve the organization name: open android/app/src/main/AndroidManifest.xml: no such file or directory
hover: Compiling 'go-flutter' and plugins
github.com/go-gl/glfw/v3.3/glfw
github.com/go-gl/gl/v3.3-core/gl
# github.com/go-gl/glfw/v3.3/glfw
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status

```

But `libgl1-mesa-dev` already installed and `libGL` is under my `/usr/lib` and `/usr/lib/x86-linux/`:

```
b/x86_64-linux-gnu/libGL.la
/usr/lib/x86_64-linux-gnu/libGL.so.1
/usr/lib/x86_64-linux-gnu/libGL.so.1.7.0
/usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.1
/usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.440.64
/usr/lib/x86_64-linux-gnu/libGLESv2.so.2
/usr/lib/x86_64-linux-gnu/libGLESv2.so.2.1.0
/usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.2
/usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.440.64
/usr/lib/x86_64-linux-gnu/libGLEW.so
/usr/lib/x86_64-linux-gnu/libGLEW.so.2.1
/usr/lib/x86_64-linux-gnu/libGLEW.so.2.1.0
/usr/lib/x86_64-linux-gnu/libGLEWmx.so.1.13
/usr/lib/x86_64-linux-gnu/libGLEWmx.so.1.13.0
/usr/lib/x86_64-linux-gnu/libGLU.a
/usr/lib/x86_64-linux-gnu/libGLX.so.0
/usr/lib/x86_64-linux-gnu/libGLX.so.0.0.0
/usr/lib/x86_64-linux-gnu/libGLX_indirect.so.0
/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0
/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0
/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.440.64
/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0
/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0

```

**Comment by jinfagang** [comment]
It runs!!!

On last question, how to update go-flutter to catch latest updates of go=flutter?

**Comment by pchampio** [comment]
```
$ hover run --help         
Build and start a desktop release, with hot-reload support

Usage:
  hover run [flags]

Flags:
  -b, --branch string             The 'go-flutter' version to use. (@master or @v0.20.0 for example)
```
use the b flag with `'@master'` or edit [go/hover.yaml](https://github.com/go-flutter-desktop/examples/blob/master/stocks/go/hover.yaml)

But on it's own, hover will check if your version is up to date, and prompt you to `hover bumpversion` when needed.
```
❯ hover help        
Hover helps developers to release Flutter applications on desktop.

Usage:
  hover [command]

Available Commands:
  build          Build a desktop release
  bumpversion    upgrade the 'go-flutter' golang library in this project
```
