### ISSUE TITLE
Is it possible to add the right mouse button menu

### ISSUE THREAD

**Issue by qianniancn** [go-flutter-desktop/go-flutter#397]
If the text box receives a right-click message, is it possible to add a menu.
for example Menu items: undo, cut, copy, cut, select all

**Comment by pchampio** [comment]
This issue is already tracked by https://github.com/flutter/flutter/issues/31955
Once the flutter team exposes the correct ABI, we will implement it. (Note: this feature might or might not require modification to go-flutter (or any other embedder)).
