### ISSUE TITLE
Molten / Vulkan / Metal support

### ISSUE THREAD

**Issue by ghost** [go-flutter-desktop/go-flutter#40]
I get warnings all the time about openGL being deprecated in the future because of Apple moving to Molten ( Apple's version of Vulkan / Metal ). 
Skia and Flutter can do Vulkan on Desktop ( and mobile) and so that is not going to be an issue, but the golang openGL, GLFW will be a problem soon.

Would be good to look into what else is out there for Golang on MacOS to solve this that will eventually hit.
There is decent Vulkan support for golang to do windowing etc.

Edit: On doing a bit of research it might be fine. There is a project where they are using golang GLFW on Metal.
See here: https://github.com/go-gl/glfw/pull/219#issuecomment-434779797

**Comment by Drakirus** [comment]
At the moment the flutter/engine is not supporting Vulkan [embedder header file] (https://github.com/flutter/engine/blob/7375a0f414bde4bc941e623482221db2fc8c4ab5/shell/platform/embedder/embedder.h#L31).
As you pointed out this might be a non-issue if Vulkan/Metal is ported into GLFW.

**Comment by gedw99** [comment]
i guess what the space ...

**Comment by pchampio** [comment]
Issue tracked by: https://github.com/flutter/flutter/issues/47562
