### ISSUE TITLE
in China hover: Warning, couldn't read the online plugin list

### ISSUE THREAD

**Issue by qianniancn** [go-flutter-desktop/go-flutter#406]
### Sometimes this happens in China，Sometimes such problems do not happen

- `hover: Warning, couldn't read the online plugin list: Get "https://raw.githubusercontent.com/go-flutter-desktop/plugins/master/list.json": dial tcp 151.101.228.133:443: connectex: No connection could be made because the target machine actively refused it.`

- `hover: Warning, couldn't read the online plugin list: Get "https://raw.githubusercontent.com/go-flutter-desktop/plugins/master/list.json": net/http: TLS handshake timeout`

**Comment by GeertJohan** [comment]
Hmm, I guess the connection is firewalled sometimes... Needs investigation into how we can serve that file from within china, in the same way the flutter engine downloader can switch to china-based servers using `$FLUTTER_STORAGE_BASE_URL`

**Comment by qianniancn** [comment]
> Hmm, I guess the connection is firewalled sometimes... Needs investigation into how we can serve that file from within china, in the same way the flutter engine downloader can switch to china-based servers using `$FLUTTER_STORAGE_BASE_URL`

ok
