### ISSUE TITLE
It is recommended to add. The default position of the startup window is in the middle

### ISSUE THREAD

**Issue by qianniancn** [go-flutter-desktop/go-flutter#407]
Hey, can you add the window's default start position to the screen center in the `flutter.WindowInitialLocation` function?
I know that InitPluginGLFW is used to gain control over the glfw.Window

**Comment by GeertJohan** [comment]
I'm not sure if initial location is something that we should force, or is something that maybe the systems' window manager should manage (keeping track of where it was last time). In any case, this could be something for a plugin, yes.

**Comment by qianniancn** [comment]
> 我不确定初始位置是我们应该强制执行的，还是系统的窗口管理器应管理的位置（跟踪上次的位置）。无论如何，这可能是插件的事情，是的。

**Comment by qianniancn** [comment]
> 我不确定初始位置是我们应该强制执行的，还是系统的窗口管理器应管理的位置（跟踪上次的位置）。无论如何，这可能是插件的事情，是的。

**Comment by qianniancn** [comment]
> I'm not sure if initial location is something that we should force, or is something that maybe the systems' window manager should manage (keeping track of where it was last time). In any case, this could be something for a plugin, yes.

ok，Thank you

**Comment by GeertJohan** [comment]
If you make such a plugin, please let us know, we could add it to the list of interesting plugins in go-flutter-desktop/plugins.

**Comment by qianniancn** [comment]
> If you make such a plugin, please let us know, we could add it to the list of interesting plugins in go-flutter-desktop/plugins.

Hmm，no problem

**Comment by pchampio** [comment]
This can be implemented without the use of a plugin.
[2. Set the initial window dimension based on screen resolution(]https://github.com/go-flutter-desktop/go-flutter/wiki/Tips-and-tricks#2-set-the-initial-window-dimension-based-on-screen-resolution)

**Comment by qianniancn** [comment]
> This can be implemented without the use of a plugin.
> [Tips-and-tricks 2. Set the initial window dimension based on screen resolution](https://github.com/go-flutter-desktop/go-flutter/wiki/Tips-and-tricks#2-set-the-initial-window-dimension-based-on-screen-resolution)

This solution is better, thanks

**Comment by MostHated** [comment]
Just in case anyone is looking for a quick way to use the above to have a fixed size window but start the window center of the screen, you can use the following.

```go
package main

// the file window-size-based-on-resolution.go is used to set the initial
// dimension of the window based on screen resolution.
//
// The following example sets the window to take all of the monitor screen
// minus a border.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	"github.com/go-gl/glfw/v3.3/glfw"
)

const windowHeight = 430
const windowWidth = 800

func init() {
	// Notice: Code in init() delays first frame!

	// Not best practice, you should let go-flutter make this call.
	err := glfw.Init()
	if err != nil {
		panic(err)
	}

	vidMoce := glfw.GetPrimaryMonitor().GetVideoMode()

	options = append(options,
		flutter.WindowInitialDimensions(
			windowWidth,
			windowHeight,
		))
	options = append(options,
		flutter.WindowInitialLocation((vidMoce.Width/2)-(windowWidth/2), (vidMoce.Height/2)-(windowHeight/2)),
	)
}

```

**Comment by qianniancn** [comment]
@MostHated Thank you for your contribution
