### ISSUE TITLE
Black screen. Does not draw initially on MacOS Mojave (10.14)

### ISSUE THREAD

**Issue by gedw99** [go-flutter-desktop/go-flutter#41]
Seems many others getting exact same issue

https://github.com/go-gl/glfw/issues/231

Basically the window opens and its just all black.
Once you maximise the window its ok and renders the FLutter scene
Also when you resize it goes black as you resize and then comes back to Flutter scene.

**Comment by zephylac** [comment]
Known isssue, seems to be fixed : [glfw/glfw#1334](https://github.com/glfw/glfw/issues/1334)

**Comment by GeertJohan** [comment]
I cannot reproduce this issue at Mac OS Mojave 10.14.3. The window is black for a short time but then automatically renders. Perhaps this has been solved by glfw, or because by a recent change in go-flutter's handling of window redrawing. @gedw99 Is this still an issue for you?

**Comment by gedw99** [comment]
This is now fixed thanks to Hover !!
