### ISSUE TITLE
Hover for cli application

### ISSUE THREAD

**Issue by marchellodev** [go-flutter-desktop/go-flutter#415]
It would be really great to be able to compile cli applications on dart just as flutter applications using hover and it's cross-compiling feature.

As far as I understand, currently it's not possible

**Comment by jld3103** [comment]
Um go-flutter/hover is only about a custom embedder for flutter in go. You can compile dart apps using `dart2native`. I'm not sure about crosscompiling there, but maybe it's possible.

**Comment by jld3103** [comment]
So I think it's currently out of scope of this project, but I also think there is currently no other project that packages dart/flutter/go apps to so many packaging formats. I'm not sure about the progress of fyne, but that's pure go project. So I'd keep the issue open, but it's definitely not a short term goal.

**Comment by marchellodev** [comment]
Yeah, dart2native is an option but it doesn't allow cross-compiling as well as packaging to so many formats

And, obviously, channels, they are present in pure dart, right? Go has a lot useful plugins to offer.

**Comment by jld3103** [comment]
Cross-compiling would only be possible with something like this: https://blog.dantup.com/2019/11/easily-compiling-dart-to-native-executables-for-windows-linux-macos-with-github-actions/
On the developer's machine it would only be possible to compile for the host.

**Comment by GeertJohan** [comment]
jld3103 is correct. We cannot compile a pure-dart application. Hover and go-flutter rely on the Dart/Flutter SDK to compile Dart and the Flutter Engine to run compiled Dart code. We don't really compile Dart ourselves, we just run the Flutter Engine on desktop platforms.
Sorry we cannot be of help here.
