### ISSUE TITLE
go-flutter: no handler found for channel assets_audio_player

### ISSUE THREAD

**Issue by yossefEl** [go-flutter-desktop/go-flutter#417]
Thanks for making this awesome package!
I trying to make my app work on Desktop, I'm using Linux and when i run 
```hover run ```
i get this error 
**go-flutter: no handler found for channel assets_audio_player**
the link of this plugin : https://pub.dev/packages/assets_audio_player
Thanks in advance :heart: :bow:

**Comment by jld3103** [comment]
That is because go-flutter doesn't have an implementation for that plugin. You may ask the plugin maintainer to add an implementation or you create one yourself.

**Comment by pchampio** [comment]
The go-flutter team has implemented flutter maintained plugins: https://github.com/go-flutter-desktop/plugins
We don't plan to work on community based plugins.
Closing this issue.
