### ISSUE TITLE
Black screen in windows.

### ISSUE THREAD

**Issue by frocelu** [go-flutter-desktop/go-flutter#419]
## Hover doctor

```
$ hover doctor
hover: Running on windows
hover: Sharing flutter version
Flutter 1.17.0-3.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 0da1ab0922 (3 days ago) • 2020-04-28 11:02:34 -0700
Engine • revision 376ad6a64b
Tools • Dart 2.8.0
hover: Flutter engine commit: https://github.com/flutter/engine/commit/376ad6a64b08aa26005e3f82aed26de2e290b572
hover: Finding out the C compiler version
gcc (tdm64-1) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

hover: Sharing the content of go.mod
module github.com/go-flutter-desktop/examples/stocks/desktop

go 1.12

require (
        github.com/go-flutter-desktop/go-flutter v0.39.0
        github.com/pkg/errors v0.9.1
)
hover: Warning: No hover.yaml file found: open go\hover.yaml: The system cannot find the file specified.
hover: Sharing the content of go/cmd
go\cmd\main.go  go\cmd\options.go
```
## Error output

Using `hover build [...] --XXX` to build my application, I get the following
error:

```log
WGL: Failed to make context current: The requested resource is in use
```

I try to build a demo project from examples/stocks for testing.
But when I run hover run, I always get a black screen of the application.
My windows version is 1909.

**Comment by pchampio** [comment]
Does 'hover run -b "v0.38.0"' works ?

**Comment by davidmartos96** [comment]
I have encountered with the same issue. 0.38.0 works, but the -b option wasn't working for me. I had to change the version in the go.mod file.

Using `hover run -b "v0.38.0"` gave me this error:
```
go get github.com/go-flutter-desktop/go-flutterv0.38.0: git ls-remote -q origin in C:\Users\Martyns\go\pkg\mod\cache\vcs\caa3ec4c492888e81a47e74d9466ef24bc912f91df44f1a0949c85254a603489: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/go-flutter-desktop/go-flutterv0.38.0/' not found
hover: Updating go-flutter to v0.38.0 version failed: exit status 1
```

**Comment by pchampio** [comment]
I forgot to add the `@`.
@frocelu does `hover run -b '@v0.38.0'` works ?

**Comment by pchampio** [comment]
@davidmartos96 thanks for your response.

**Comment by davidmartos96** [comment]
@pchampio Yes, the @ does it. Sorry, I haven't use the -b option that much 😅

**Comment by pchampio** [comment]
@all to further investigative this.
Run 1 - Does `hover run -b '@9823ced8f7491631c320500356875ba518148d32'` work?
Run 2 - Does `hover run -b '@ec926762cc39ace963f974fbb19971b5cfe60b97'` work?

might be related to https://github.com/go-flutter-desktop/go-flutter/pull/390

**Comment by davidmartos96** [comment]
Run 1: Doesn't work
Run 2: Doesn't work

**Comment by pchampio** [comment]
Okaay..
Run 3: does `hover run -b '@0ce8cfb2cca96753c1cde72663618389bb601279'` work? - Yes/No
Run 4: does `hover run -b '@100c066ded9b176203c96a3fc008c19ba1d38b87'` work? - Yes/No

**Comment by davidmartos96** [comment]
@pchampio 
Run 3: Doesn't work
Run 4: Works 😄

**Comment by pchampio** [comment]
good..
Run 5: does `hover run -b '@master'` work? - Yes/No

**Comment by davidmartos96** [comment]
@pchampio Yes, latest revert works fine.

**Comment by pchampio** [comment]
I'm sorry to tag commits that doesn't works, such issue is kinda hard to test.
I don't have the infrastructure resources to run all test properly.
Thanks to you for feed back!

**Comment by pchampio** [comment]
Just to be 100%, @davidmartos96 your issue was the same as @frocelu:
`WGL: Failed to make context current: The requested resource is in use`

**Comment by davidmartos96** [comment]
@pchampio Yes, the exact same issue. Black screen and the posted error message is getting printed constantly in the console.

**Comment by pchampio** [comment]
Run 6: does `hover run -b '@8ee826935244fe6431b0f6afae6e29455a81104c'` (from https://github.com/go-flutter-desktop/go-flutter/pull/422) work? - Yes/No

**Comment by davidmartos96** [comment]
@pchampio No, it doesn't work.
These are the logs:
```
EventLoop Thread id: (int64) -2

Task Thread id: (int64) -2

Task Thread id: (int64) -2

Task Thread id: (int64) -2

-- GLMakeResourceCurrent
Task Thread id: (int64) -2
```

**Comment by pchampio** [comment]
Run 7: what is the output of `hover run -b '@c89185c3a2dfd2fda1fb3cfaab3997f5781b2779'` ?

**Comment by davidmartos96** [comment]
@pchampio Fails

```
Real Thread id: (currentthread._Ctype_HANDLE) 0xfffffffffffffffe

EventLoop Thread id: (int64) -2
```

**Comment by pchampio** [comment]
What's the full output?

**Comment by davidmartos96** [comment]
```
Real Thread id: (currentthread._Ctype_HANDLE) 0xfffffffffffffffe

EventLoop Thread id: (int64) -2

Real Thread id: (currentthread._Ctype_HANDLE) 0xfffffffffffffffe

Real Thread id: (currentthread._Ctype_HANDLE) 0xfffffffffffffffe

Task Thread id: (int64) -2

Real Thread id: (currentthread._Ctype_HANDLE) 0xfffffffffffffffe

Task Thread id: (int64) -2

Real Thread id: (currentthread._Ctype_HANDLE) 0xfffffffffffffffe

Task Thread id: (int64) -2

-- GLMakeResourceCurrent
Real Thread id: (currentthread._Ctype_HANDLE) 0xfffffffffffffffe

Task Thread id: (int64) -2

-- GLMakeCurrent
Real Thread id: (currentthread._Ctype_HANDLE) 0xfffffffffffffffe

Task Thread id: (int64) -2
-- GLMakeCurrent
2020/05/02 12:22:53 PlatformError: WGL: Failed to make context current: The requested resource is in use. 
```

**Comment by pchampio** [comment]
Okay, I think I got a fix.

**Comment by pchampio** [comment]
@davidmartos96 does `hover run -b '@revert-421-revert-390-macOS_no_resize_crash'` works?

**Comment by pchampio** [comment]
Also, If you have new C warning, please report them!

**Comment by davidmartos96** [comment]
@pchampio It works without any warnings! 🎊

**Comment by pchampio** [comment]
tagged in [v0.40.1](https://github.com/go-flutter-desktop/go-flutter/releases/tag/v0.40.1)

**Comment by frocelu** [comment]
Sorry about my late reply and poor English.
hover run -b "@v0.38.0"   works for me.
So is this a problem in current version?

**Comment by pchampio** [comment]
@frocelu a regression was introduced on windows in v0.39.0.
v0.40.0 reverted it.
v0.40.1 re-introduced the feature but without the windows regression.

please run `hover bumpversion` and `hover run`

**Comment by frocelu** [comment]
Ok, thank you.
I am a newbie in flutter and this project, so I really thought that I do something wrong in my installing.

**Comment by ekasetiawans** [comment]
@pchampio i facing this issue again after upgrade to flutter stable 1.17.
here my [previous issue](https://github.com/go-flutter-desktop/go-flutter/issues/326#issuecomment-613330091)

**Comment by pchampio** [comment]
Please open a new issue

**Comment by ekasetiawans** [comment]
> Please open a new issue

ok, I open issue #438
