### ISSUE TITLE
How to release Windows desktop app, to be usable in another machine?

### ISSUE THREAD

**Issue by KanybekMomukeyev** [go-flutter-desktop/go-flutter#42]
Hi, every time when i build from source code ``` go build main.go ```
```
func main() {
	var (
		err error
	)

	_, currentFilePath, _, _ := runtime.Caller(0)
	dir := path.Dir(currentFilePath)
        //.....
}
```
Here the "dir path" is fixing my local path.
And whenever triying ro run in another machine, app crashes, 
with error that app can not find my local path. 

For example:
```
can not open C:/src/flutter_projects/go-flutter-desktop-embedder/example/simpleDemo/assets/icon.png: The system cannot find the path specified.
```
this is another machine, there should not be go-flutter-desktop-embedder

Or this kind of issue:
```
[FATAL:e:\b\build\slave\windows_engine\build\src\flutter\fml\icu_util.cc(92)] Check failed: context->IsValid(). Must be able to initialize the ICU context. Tried: C:/src/flutter_projects/go-flutter-desktop-embedder/example/simpleDemo/icudtl.dat
```

**Comment by zephylac** [comment]
When trying on another machine did you just copied files or did you fully reinstalled ?
Shared Library are dependant on your architecture (Windows, MacOS, Linux).

**Comment by KanybekMomukeyev** [comment]
There are 2 machines:
 1) mine.
 2) collegue.

a) I build flutter windows desktop app on mine machine.
b) Copy neede files into one folder (assets, dll framework, icu file ....)
c) Send folder to collegue machine by messenger.

Whenever run app in folder, i have mentioned issues on collegue machine.

**Comment by zephylac** [comment]
To run the application you need flutter. And your icudtl.dat file is dependant of the flutter version installed and the OS.

>I highly recommend you to reinstall it by following the README.md when switching computer

You can try to create a file that automatically execute installation steps and launch your app. So that you colleague can just execute that file to launch the app.

**Comment by Drakirus** [comment]
Can you try to remove:
```
	_, currentFilePath, _, _ := runtime.Caller(0)
	dir := path.Dir(currentFilePath)
```
and use `gutter.OptionAssetPath("flutter_project/stocks/build/flutter_assets")` instead of `gutter.OptionAssetPath(dir + "/flutter_project/demo/build/flutter_assets")` and so on every time you encounter `dir + <...>`

---

Here is an older example of the `main.go` used in the prebuild embedder [main.go](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/d4df6def83fded24ecfe83dc0f2f498331062715/example/stocks/main.go)

**Comment by KanybekMomukeyev** [comment]
@Drakirus, your solution worked like charm, removed "dir" everywhere.

**Comment by GeertJohan** [comment]
Closed because issue seems to be fixed. Please re-open if this is not the case.
