### ISSUE TITLE
Problem installing hover in ubuntu 18.04

### ISSUE THREAD

**Issue by shaw8wit** [go-flutter-desktop/go-flutter#423]
I installed hover by running this in terminal:
`GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover`

Also installed the 2 packages required for ubuntu, still, I'm getting the error:

> Command 'hover' not found,

**Comment by GeertJohan** [comment]
You're probably missing `$HOME/bin` in your PATH, so the shell cannot find the hover command.

**Comment by shaw8wit** [comment]
That doesn't seem to be the case as I've checked my .proflie to see that `PATH="$HOME/bin:$PATH"` is present.

**Comment by jld3103** [comment]
The go bin directory is under `$HOME/go/bin` normally
