### ISSUE TITLE
Renovate bot update github action

### ISSUE THREAD

**Issue by pchampio** [go-flutter-desktop/go-flutter#427]
Renovate is updating the gitlab-ci file when a new hover tag is pushed but not the github action 
https://github.com/go-flutter-desktop/examples/blob/master/.github/workflows/main.yml#L16

**Comment by jld3103** [comment]
See https://docs.renovatebot.com/modules/manager/github-actions/

**Comment by pchampio** [comment]
It's not possible using the WhiteSource Renovate app (currently the one we use).
 https://github.com/renovatebot/config-help/issues/570

Since the action is trigger by gitlab ci, we can use `@latest` instead of hard-coding the version.

**Comment by pchampio** [comment]
fixed by https://github.com/go-flutter-desktop/examples/pull/90
