### ISSUE TITLE
Is there a way to reduce RAM footprint ?

### ISSUE THREAD

**Issue by dedesite** [go-flutter-desktop/go-flutter#432]
## Is your feature request related to a problem?

When building linux application with go-flutter, the sample application takes about ~50Mb RAM in my system (Xunbuntu 18.04).

It is my understanding that flutter use low level API like Skia so I was hopping that application take less RAM than that.

Remark : it's better than official flutter debug build which takes about 150Mb.

Are those 50Mb a "bare minimum" or is there way to reduce footprint to something "decent" (let's say 10Mb for a very simple application) ?

Thanks for your time and for building go-flutter !

Andréas

**Comment by jld3103** [comment]
Yes. When we get AOT support the RAM usage is much lower. Until then there is little that can be done. See https://github.com/go-flutter-desktop/go-flutter/issues/259

**Comment by dedesite** [comment]
Ok thanks for your reply, I'll wait then :).

**Comment by pchampio** [comment]
I've run some test with a JIT / AOT app.
The results are more like:
```
Private  +   Shared  =  RAM used       Program
 63.1 MiB +   1.8 MiB =  64.8 MiB       stocksAOT
150.4 MiB +   1.8 MiB = 152.2 MiB       stocks
```

**Comment by pchampio** [comment]
Demo AOT app: [aot-flutter-linux.zip](https://github.com/go-flutter-desktop/go-flutter/files/4599029/aot-flutter-linux.zip)

**Comment by dedesite** [comment]
Thanks @pchampio for your tests and the demo.

However, I wouldn't compare flutter with Electron which is basically an entire web browser which bundle node and some platform API, but for me, we can compare it with native cross platform frameworks like Qt or Gtk and they have a much smaller footprint.

I thought the flutterengine was better is this domain, does it takes those resources on Android or iOs ?

Anyway, it's still an awesome technology.

**Comment by pchampio** [comment]
> I thought the flutterengine was better is this domain, does it takes those resources on Android or iOs ?

yea, pretty much.
It also depends on the backing store, Meta or OpenGl or vulkan or software.
Meta is the less memory intensive. 
Currently for desktop only OpenGL and software are available.

> we can compare it with native cross platform frameworks like Qt or Gtk and they have a much smaller footprint.

Hum, not really, the comparison with web browser is actually quite relevant.
In "AOT" mode, snapshot produced aren't native ARM64 code, we still need a "AOT" Dart VM to run the "aot" snapshot.

Flutter "AOT" is a middleground between native code and Electron with his web engine/JS interpreter. 
In my humble opinion the "AOT" dart vm is like the java interpreter (but better) and the flutter engine is Qt or Gtk. As you see, there is another layer (the dart vm) between the corss platform framework (flutter engine) and the code you write.

So expecting native performance like C application written to talk to Qt/Gtk application is by design not possible.
All of this also explains why flutter app have bigger installer size than native on.

**Comment by pchampio** [comment]
And now, get ready (I'm pretty sure you aren't expecting this).
In `--release` mode, your code isn't necessary AOT.
That why i've used "AOT", in the case of desktop, we will be using the dart execution mode "Core JIT mode".

All of this is super confusing, just know that saying `--release` is AOT, is a commercial move of the flutter commercial team. Actually they never said that, they said it's like AOT.

Please read more at: https://proandroiddev.com/flutters-compilation-patterns-24e139d14177

**Comment by pchampio** [comment]
Also from that forum: https://groups.google.com/a/dartlang.org/forum/#!topic/misc/BCfmQ6WTfNU "is probably not beneficial."

**Comment by dedesite** [comment]
> Hum, not really, the comparison with web browser is actually quite relevant.

Maybe in term of performance, but not in term of memory footprint. A web browser is complex as hell, it's more like an entire OS than an "simple" UI framework.

> In my humble opinion the "AOT" dart vm is like the java interpreter (but better) and the flutter engine is Qt or Gtk.

I agree with that, but dart vm and go runtime (in the case of go-flutter-desktip) aren't that much memory intensive.

Here are a few numbers :
* The simplest go program is about 300Kb
* The simplest dart program is about 2.2Mb

So the overhead of using Dart VM and Go runtime is quite insignificant and for a comparaison : 
* mate-calc (GTK 3 based app) is about  7.7Mb and is does more than the Flutter sample app
* kcalc (Qt bases app) is about 14.2Mb
* glxgears is about 6.1Mb

This means that Flutter SDK takes at least 40~50Mb which is quite huge considering it's pretty low level compared to Electron (which embeded a whole lot of thing and has a pretty complex parsing and layout system due to HTML/CSS).

Maybe flutter will be more modular in the future and  allow to include only what needed in the binaries ? Wasn't tree shacking already suppose to do that ?

Sorry if my questions seems dumb, I'm really new to flutter and dart, but it seems such an impressive peace of code that I want to understand how it works and its limits.

Andréas

**Comment by pchampio** [comment]
Tree shaking is perform for dart application.
The engine VM and flutter engine cannot be tree shaken because they are pretty slow to compile. And the language, C++, is not know to me tree shakable.

**Comment by dedesite** [comment]
>  And the language, C++, is not know to me tree shakable.

Ah your right a big part of Flutter is not written in Dart !
So the only solution would be to split Flutter SDK into multiple modules.
But I guess reduce RAM consumption is not the priority.
I'll continue to learn Flutter and maybe choose it for my future projects. The multiplatform aspect and the very modern design is quite appreciable.

This is something that doesn't exist anywhere else.

And it's clearly less bloated as an electron application that carry a lot of unnecessary code and is pretty unstable on Linux (in my case all the electron apps tend to freeze my computer at a certain moment or when using multiple electron app simultaneously).
