### ISSUE TITLE
how to custom projectName and icon

### ISSUE THREAD

**Issue by jlcool** [go-flutter-desktop/go-flutter#433]
how to custom projectName and icon

**Comment by jlcool** [comment]
I cannot modify pubspec.yaml name

**Comment by jld3103** [comment]
To change the icon just replace the `go/assets/icon.png` with your own png. It has to be a square and you should use atleast 256x256.
You can modify the values in `go/hover.yaml` to your liking.

**Comment by jlcool** [comment]
how to modify hover.yaml tocustom projectName?

**Comment by jld3103** [comment]
I don't understand. Just change the entries in the file

**Comment by jlcool** [comment]
this [link](https://github.com/go-flutter-desktop/hover/blob/788eec5627356dfd5671783b9cd6246e8ce1dd27/cmd/run.go#L49) shows that the project name is obtained from pubspec.yaml

**Comment by jld3103** [comment]
1. I found a bug in that part of the code around the executable name
2. What do you want to change exactly? You can change the executable, the application and package name.

**Comment by jld3103** [comment]
1. Bug fixed in hover `v0.41.5`. Please update

**Comment by jlcool** [comment]
In the Mac system, when I run hover run, the name displayed in the dock is the name in pubspec.yaml, but this name can't be changed at will. I want to customize what to do with this name change. I set application name: "" executable name: "" package name: "" in hover.yaml, which is useless

**Comment by jld3103** [comment]
Your hover.yaml should use the entries like this:
```yaml
application-name: "My super fancy app"
executable-name: "my-super-fancy-app"
package-name: "mysuperfancyapp"
```

**Comment by pchampio** [comment]
The name of the windows (in docks, windows decoration, apps bar) is set using an internal flutter method channel.

To support setting the name describes here, we need use build-constraint.go

This feature requires isn't available ATM
Please wait for the next release of go-flutter

**Comment by jlcool** [comment]
Invalid on MAC

> Your hover.yaml should use the entries like this:
> 
> ```yaml
> application-name: "My super fancy app"
> executable-name: "my-super-fancy-app"
> package-name: "mysuperfancyapp"
> ```

**Comment by jlcool** [comment]
> Your hover.yaml should use the entries like this:
> 
> ```yaml
> application-name: "My super fancy app"
> executable-name: "my-super-fancy-app"
> package-name: "mysuperfancyapp"
> ```

The file name displayed by Darwin DMG has not been changed. It is still the name of pubspec.yaml
