### ISSUE TITLE
How the go plug-in calls setMethodCallHandler

### ISSUE THREAD

**Issue by jlcool** [go-flutter-desktop/go-flutter#434]
``` dart
StreamController<bool> _responseInitController =
  new StreamController.broadcast();
  Stream<bool> get responseFromInit =>
      _responseInitController.stream;

responseFromInit.listen((data) {
//todo
})
```

**Comment by pchampio** [comment]
Please read:
https://github.com/go-flutter-desktop/go-flutter/wiki/Plugin-info
https://github.com/go-flutter-desktop/go-flutter/wiki/Create-a-hover-compatible-plugin
https://github.com/go-flutter-desktop/go-flutter/wiki/Implement-a-plugin <--- The best
https://github.com/go-flutter-desktop/go-flutter/wiki/GLFW-Plugin-example

And checkout our demo repo:
https://github.com/go-flutter-desktop/examples/tree/master/plugin_tutorial
https://github.com/go-flutter-desktop/examples/tree/master/xbox_controller

**Comment by jlcool** [comment]
@pchampio How does invokemethod return Map，It seems that only string can be returned

**Comment by GeertJohan** [comment]
A map is returned as a `map[string]interface{}`, you have to type-cast that `interface{}` value to what you know it is. Don't forget to check the error on type casts, just in case the dart-side somehow doesn't send the type you expect.
