### ISSUE TITLE
hover lost connection to device windows 10

### ISSUE THREAD

**Issue by iamsabet** [go-flutter-desktop/go-flutter#440]
hi , im using latest on beta on windows 10 
when i run my project 
`hover run`
the cli works at first and app starts then hot-reload , hot-restart works perfectly
but after being seconds afk or do a save on 1 .dart file in project it drops :
LOST CONNECTION TO DEVICE
and continues to log everything else an even app is working completley but 
No Hot-restart and Hot-Reload 
NO debugger!
when i do ctrl+c and close the app 
all of my  rRrrRR that didnt work for reload or restart where inside input buffer if that helps

![image_2020-05-09_19-27-08](https://user-images.githubusercontent.com/20267993/81567493-9fefaa80-93b1-11ea-8487-8aff32b97f6c.png)

![image_2020-05-09_19-33-18](https://user-images.githubusercontent.com/20267993/81567512-a41bc800-93b1-11ea-9d3e-24c86c9b3e1b.png)

i appreciate a fast guide or answer if possible cause we need it right now 
ty 
awesome job

**Comment by pchampio** [comment]
Open a new terminal (while `hover run` is still running) and type: `flutter attach http://127.0.0.1:50300`
This will by pass `hover`. This way, hot reload is only performed using the flutter toolchain.

**Comment by iamsabet** [comment]
how can i automate this ?
at least with vscode or android studio config
a little help ?

**Comment by pchampio** [comment]
> how can i automate this ?

No idea, `LOST CONNECTION TO DEVICE` isn't an error from go-flutter or hover but from `flutter attach`, so what I'm proposing isn't really an alternative, just a way to not rerun `hover run`  every time you get the `LOST CONNECTION TO DEVICE` (unknown to me).

> at least with vscode or android studio config
a little help ?

Yea, sure, try:
https://github.com/go-flutter-desktop/vscode-hover
https://github.com/go-flutter-desktop/hover#ide-integration

**Comment by pchampio** [comment]
Also, I'm a vim user. SOoooo I cannot really help you with vscode or android studio config..

**Comment by GeertJohan** [comment]
I think @jld3103 is working on an extension for Android Studio.

The VSCode extension is very new, but sure give it a try!

**Comment by pchampio** [comment]
I thinks this can also help you: https://github.com/flutter/flutter/issues/26945

**Comment by jld3103** [comment]
> I think @jld3103 is working on an extension for Android Studio.
> 
> The VSCode extension is very new, but sure give it a try!

Yeah, but I hit some barriers where I need mor documentation, examples or tutorials to break through.

**Comment by pchampio** [comment]
Closing this issue because it's not related to go-flutter-desktop.
More info can be found on the flutter issue tracker: https://github.com/flutter/flutter/search?q=lost+connection+to+device&type=Issues
Please keep reporting your findings here! And sorry for not been able to provide you with a fix.
