### ISSUE TITLE
I have a problem trying to write a WebView plug-in

### ISSUE THREAD

**Issue by jlcool** [go-flutter-desktop/go-flutter#444]
https://github.com/zserge/webview

``` go
func (p *FlutterPlugin) InitPlugin(messenger plugin.BinaryMessenger) error {
	p.channel = plugin.NewMethodChannel(messenger, channelName, plugin.StandardMethodCodec{})

	p.channel.HandleFuncSync("auth", p.handleGoogleLogin)
	return nil
}

func (p *FlutterPlugin) handleGoogleLogin(arguments interface{}) (reply interface{}, err error) {
	debug := false
	w := webview.New(debug)
	defer w.Destroy()
	w.SetTitle("webview example")
	w.SetSize(800, 600, webview.HintNone)
	w.Bind("callback", func(unionid, name, oauthId, profile string) {
		m1 := make(map[string]string)
		m1["name"] = name
		b, err := json.Marshal(m1)
		p.channel.InvokeMethod("onCallback", string(b))
	})
	w.Bind("quit", func() {
		w.Terminate()
		w.Destroy()
	})
	w.Navigate("https://www.google.com")
	fmt.Println("------------>1")
	w.Run()//It's stuck here
	fmt.Println("------------>2")//Can't execute here
	return nil, nil
}
```

**Comment by pchampio** [comment]
The go-doc of zserge/webview says that:
>  // Run runs the main loop until it's terminated. After this function exits - you must destroy the webview.

It implies that `w.Run()` is a blocking function call!
If you want to run the webview main loop in a non-blocking manner please use `go w.Run()`.

As this issue is about golang programing closing the issue.

**Comment by pchampio** [comment]
Still, using `zserge/webview` building a google_auth plugin might possible! So Cool!

**Comment by jlcool** [comment]
There are still problems use `go w.Run()`，
use `w.Run()`  Windows can be displayed, but go desktop windows are locked
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'

**Comment by jlcool** [comment]
@pchampio  Can you help me？thanks

**Comment by pchampio** [comment]
The go-flutter lib has to perform rendering on the main thread.
I don't know if the https://github.com/zserge/webview lib can work in a background thread.

@jlcool Please ask the author of zserge/webview to know if  `w.Run()` can be called in a sub-goroutine. The go-flutter has to `runtime.LockOSThread()` on his main thread.

> Can you help me？

To some extent, yes.
But I cannot free that much time,  learning how zserge/webview works and helping you to solve zserge/webview 'issues' isn't possible. Please reach to the author of zserge/webview.

**Comment by jlcool** [comment]
Thank you for your reply. I went to ask him a [question](https://github.com/zserge/webview/issues/382)

**Comment by JanezStupar** [comment]
@pchampio I am facing the same issue on my `flutter_systray` plugin. The `systray` library has a blocking `systray.Run()` method. If I run it as a goroutine I get the same panic error as @jlcool  above.

I am not expecting you to solve the issue for me, but perhaps dropping a few keywords that would help me understand the problem would be greatly appreciated.

**Comment by JanezStupar** [comment]
@pchampio I did a bit more research so if I understand correctly - there is no way to got this resolved outside of say merging systray logic into go-flutter if I understand correctly and even that may not be feasible?

**Comment by pchampio** [comment]
In the webview case, it's quite complicated since you have to run 2 event loop at once. And there will be dead-locks..
But if event can be computed independently without a event loop. You can `Run` event alongside the the go-flutter event loop using [`HandleFuncSync`](https://pkg.go.dev/github.com/go-flutter-desktop/go-flutter/plugin#MethodChannel.HandleFuncSync).

Here is an example on how to process event in the main blocking go-flutter loop: https://github.com/go-flutter-desktop/examples/tree/master/draggable_borderless

https://github.com/go-flutter-desktop/examples/blob/49586b2d40c9accbb62c1bff6b4a66323abf1dcf/draggable_borderless/go/cmd/options.go#L51-L62

Overall, it's a combination of running some computation on a go-routine (not the go-flutter thread [`HandleFunc`](https://pkg.go.dev/github.com/go-flutter-desktop/go-flutter/plugin#MethodChannel.HandleFunc)) so that we don't block the go-flutter render thread. And process the result in the main go-flutter thread.

**Comment by JanezStupar** [comment]
@pchampio thanks for this feedback. It was precisely what I needed.

**Comment by pchampio** [comment]
The systray go module doesn't seems to allow for individual event to be exec without using the module bundled event loop `systray.Run()`. 

Maybe try: https://github.com/getlantern/systray
There is a section: "co-exist with other UI elements"
https://github.com/getlantern/systray#the-webview-example

**Comment by JanezStupar** [comment]
@pchampio ultimately I had to use a different library for MacOS, but your advice was invaluable. Take care!
