### ISSUE TITLE
Building on MacOS 10.15 not compatible with older OS

### ISSUE THREAD

**Issue by etx** [go-flutter-desktop/go-flutter#447]
## Is your feature request related to a problem?

When building with `hover build darwin` the binary produced is not compatible with MacOS versions below 10.15.

## Describe the feature you'd like

It looks like the clang compiler on 10.15 requires a flag to build for older versions of MacOS. The flag is `CGO_CFLAGS=-mmacosx-version-min=10.8`. I'm unsure if the linker needs this flag as well, I believe it may. I tried exporting this before a build but I believe hover is superseding the env. 
https://github.com/go-flutter-desktop/hover/blob/master/cmd/build.go#L469

If you try `otool -l go/build/outputs/darwin/outputBinary` you will notice:
```
platform 1
       sdk 10.15.4
     minos 10.15
```

Is there currently a way to pass through additional flags? If not and we can come to an agreement on implementation we could most likely get a PR together for it.

**Comment by jld3103** [comment]
Currently there is no way for passing flags (I believe), but the flag should definitely be added.

**Comment by etx** [comment]
Would it make sense to live in hover.yaml?

**Comment by jld3103** [comment]
I would just directly put it into hover, because the flag seems to be needed for compatability so everyone should get the fix. Just put it here: https://github.com/go-flutter-desktop/hover/blob/master/cmd/build.go#L460
Can you try that and make a PR if it works?

**Comment by jld3103** [comment]
I'm not sure if there is a usecase for custom compiler flags. If then we could add a field in hover.yaml and add a flag to build/run.

**Comment by etx** [comment]
You're right. Assuming it doesn't cause any errors for older versions of clang it should be fine. I just sent a PR to the hover repo. 

https://github.com/go-flutter-desktop/hover/pull/133

Tested builds on MacOS 10.14 and 10.13 and they worked well.

Thanks for the great tool!
