### ISSUE TITLE
Profile mode with go-flutter

### ISSUE THREAD

**Issue by Tokenyet** [go-flutter-desktop/go-flutter#452]
## Is your feature request related to a problem?
App/Software optimization

## Describe the feature you'd like
`hover run --profile` or  `hover run --p` 

Recently, [my app](https://minecraftscepter.github.io/) that met a memory problem when users open the app over 2 days, then 2 gb ram will be filled up. Since observatory's memory native profiler only supported in profile mode, let me here to request this feature :P 

![image](https://user-images.githubusercontent.com/6420527/83259280-5513c680-a1ea-11ea-930e-e902170670e3.png)

**Comment by pchampio** [comment]
Profile mode requires a special version of the flutter engine.
Profile/Release mode requires https://github.com/go-flutter-desktop/go-flutter/issues/259 to first be fixed.
