### ISSUE TITLE
Can't build with docker (manifest unknown)

### ISSUE THREAD

**Issue by marchellodev** [go-flutter-desktop/go-flutter#453]
```
goflutter/hover:v0.41.6 hover-safe.sh build linux --skip-flutter-build-bundle --skip-engine-download
docker container: Unable to find image 'goflutter/hover:v0.41.6' locally
docker container: /usr/bin/docker: Error response from daemon: manifest for goflutter/hover:v0.41.6 not found: manifest unknown: manifest unknown.
docker container: See '/usr/bin/docker run --help'.
hover: Docker run failed: exit status 125
```

**Comment by jld3103** [comment]
We had an issue with the docker image so that some hover versions are not available as docker images. We need to release a new version of hover to fix it @GeertJohan.
As temporary fix you can clone hover and install it locally. Then it pulls the latest docker image which works again.

**Comment by jld3103** [comment]
`v0.42.0` has been released. It will take some minutes to build the docker image, but when you try in about an hour or so it should already be available
