### ISSUE TITLE
windows release shortcut icon is too small

### ISSUE THREAD

**Issue by geata** [go-flutter-desktop/go-flutter#455]
1. run `hover build windows-msi --docker` 
2. install 
3. the shortcut icon look blurred

i see the command is 
`/bin/bash -c convert -resize x16 build/assets/icon.png build/assets/icon.ico && wixl -v ......`

is it too small of **x16**

**Comment by jld3103** [comment]
You are using an old version of hover. Please update and then the icon has the same size as your png in the assets.
