### ISSUE TITLE
Hover packaging linux-rpm and linux-deb fail when there is no description in pubspec.yaml

### ISSUE THREAD

**Issue by GeertJohan** [go-flutter-desktop/go-flutter#456]
https://github.com/go-flutter-desktop/examples/pull/97/checks?check_run_id=723591244

**Comment by GeertJohan** [comment]
I guess there are three ways to handle this:
- Let any hover package command fail with a descriptive error when there is no description available in pubspec.yaml
- Only let linux-deb and linux-rpm command fail with an error when there is no description.
- Use "No description was provided during the build of this application" as description for linux-deb / linux-rpm when none was given.

**Comment by pchampio** [comment]
I'll perfer the point 3 ("No description was provided during the build of this application" as description) with a descriptive warning.
