### ISSUE TITLE
Cannot use replace directive in go.mod

### ISSUE THREAD

**Issue by jld3103** [go-flutter-desktop/go-flutter#457]
Since the changes of https://github.com/go-flutter-desktop/hover/pull/120 I'm not able to use a local go-flutter module, because hover fails with `hover: failed to parse the 'go-flutter' version in go.mod` when using a `replace ...` in the go.mod file.
Just wanted to track it, PR coming soon.

**Comment by pchampio** [comment]
fixed by: https://github.com/go-flutter-desktop/hover/pull/148
