### ISSUE TITLE
Deployment Target not picking from the Mac project in flutter

### ISSUE THREAD

**Issue by neerajjaiswal** [go-flutter-desktop/go-flutter#464]
Hi,

I have set the Deployment Target as 10.11 for macos, but still the app which is generated doesn't run on a mac with 10.14. It is looking for version 10.15, same as the one on which I did my development.

Is there any other way I have to set the deployment target for hover to pick it up?

**Comment by jld3103** [comment]
Which hover version do you have? The target thing has been fixed in https://github.com/go-flutter-desktop/hover/pull/133 and is available in hover versions >= v0.41.6. If you are running an older version please update

**Comment by pchampio** [comment]
Without additional information, we are unfortunately not sure how to resolve
this issue. We are therefore reluctantly going to close this bug for now. Please
don't hesitate to comment on the bug if you have any more information for us; we
will reopen it right away!
Thanks for your contribution.
