### ISSUE TITLE
no method handler registered for method 'TextInput.setEditableSizeAndTransform' on channel 'flutter/textinput'

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#467]
```
go-flutter: no method handler registered for method 'TextInput.setEditableSizeAndTransform' on channel 'flutter/textinput'
go-flutter: no method handler registered for method 'TextInput.setEditableSizeAndTransform' on channel 'flutter/textinput'
go-flutter: no method handler registered for method 'TextInput.setEditableSizeAndTransform' on channel 'flutter/textinput'
go-flutter: no method handler registered for method 'TextInput.setEditableSizeAndTransform' on channel 'flutter/textinput'
```

Can not input text with Chinese:

![image](https://user-images.githubusercontent.com/21303438/83938543-d7fad980-a807-11ea-9df1-d6093d876182.png)

Anybody knows how to solve it?

**Comment by pchampio** [comment]
What's the output of `hover doctor`.
This issue should be fixed in `v0.41.1`.
Please `hover bumpversion` if needed.

**Comment by jinfagang** [comment]
```
hover bumpversion                    1 master!
hover: Using engine from cache
hover: Using engine from cache
go: finding github.com/go-flutter-desktop/go-flutter v0.41.1
verifying github.com/go-flutter-desktop/go-flutter@v0.41.1/go.mod: github.com/go-flutter-desktop/go-flutter@v0.41.1/go.mod: Get https://sum.golang.org/lookup/github.com/go-flutter-desktop/go-flutter@v0.41.1: dial tcp 34.64.4.17:443: i/o timeout
hover: Updating go-flutter to @latest version failed: exit status 1

```

I can't bumpversion in China, old issue, golang.org can not access.

**Comment by pchampio** [comment]
What is the output of: `cd go && go get -u -d -v github.com/go-flutter-desktop/go-flutter@latest`

**Comment by jinfagang** [comment]
```
~/go> go get -u -d -v github.com/go-flutter-desktop/go-flutter@latest         1
go: cannot use path@version syntax in GOPATH mode

```

**Comment by pchampio** [comment]
Is GO111MODULE=on (v-env)?

**Comment by jinfagang** [comment]
I set it and now seems `go get -u -d -v github.com/go-flutter-desktop/go-flutter@latest` this command can run.

However when run `hover bumpversion` got;

```
hover bumpversion                 master! master!
hover: Using engine from cache
hover: Using engine from cache
go: finding github.com/go-gl/gl latest
go: finding github.com/go-gl/glfw/v3.3/glfw latest
go get: upgrading golang.org/x/text@v0.3.0: unrecognized import path "golang.org/x/text" (https fetch: Get https://golang.org/x/text?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/text@v0.3.2: unrecognized import path "golang.org/x/text" (https fetch: Get https://golang.org/x/text?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
hover: Updating go-flutter to @latest version failed: exit status 1

```

Seems golang.org/x/text can not upgrade.

**Comment by jinfagang** [comment]
Actually I am already install text 0.3.2

```
ff@ff ~/g/p/m/g/x/text@v0.3.2> pwd                                                           
/home/ff/go/pkg/mod/golang.org/x/text@v0.3.2

```

Why it was still upgrading...

**Comment by pchampio** [comment]
Golang.org/x/text doesn't matters.
After successfully updating go-flutter with 'go get -u -d ...' does the warning message about 'TextInput.set...' still shows-up?

**Comment by jinfagang** [comment]
```
 no method handler registered for method 'TextInput.setEditableSizeAndTransform' on channel 'flutter/textinput'
go-flutter: no method handler registered for method 'TextInput.setStyle' on channel 'flutter/textinput'

```

Still shows up, and Chinese still can not input.

For reference, here is my TextField dart code:

```dart
TextField(
                        maxLines: 10,
                        controller: _controller,
                        style: NORMAL_TXT_STYLE,
                        keyboardType: TextInputType.multiline,
                        decoration: InputDecoration(
                            hintText: "任务备注",
                            border: InputBorder.none,
                            focusedBorder: InputBorder.none),
                        onChanged: (value) {
                          createTaskBloc.updateComment(value);
                        },
                      ),
```

Does there looks any wrong?

**Comment by pchampio** [comment]
What's the output of 'hover doctor' ?

**Comment by jld3103** [comment]
> ```
> ~/go> go get -u -d -v github.com/go-flutter-desktop/go-flutter@latest         1
> go: cannot use path@version syntax in GOPATH mode
> ```

I think you were in the wrong directory when updating go-flutter. Looks like you were in `~/go` instead of `/path/to/project/go`. Is that right?

**Comment by jinfagang** [comment]
@jld3103  That problem resolved by add GO111MODULE=on.

But that warning and Chinese charactor can not input still exist.

**Comment by jinfagang** [comment]
I suppose this can be easily revealed if you guys have a Chinese input method on linux? (I haven't tested on macOS and windows yet) but Linux (Ubuntu 20.04) will have this problem.

**Comment by pchampio** [comment]
What's the output of `hover doctor`?

**Comment by pchampio** [comment]
> I suppose this can be easily revealed if you guys have a Chinese input method on linux? (I haven't tested on macOS and windows yet) but Linux (Ubuntu 20.04) will have this problem.

Not related please read: https://github.com/go-flutter-desktop/go-flutter/issues/454

**Comment by pchampio** [comment]
This warning is not displayed in hover `v0.41.1`:
https://github.com/go-flutter-desktop/go-flutter/blob/2a5ae05b74a731701781bc9d02d788e35025c804/text-input.go#L74-L75

You can manually update your project's version by editing `go/go.mod` and switching the version number of the required dependency `github.com/go-flutter-desktop/go-flutter` to `v0.41.1`.

**Comment by jinfagang** [comment]
@pchampio  Hi, I followed your instructions and the warning is gone.

But Chinese characters still can not input.

![image](https://user-images.githubusercontent.com/21303438/84033567-a7639d00-a9cb-11ea-8422-fd07bac16a41.png)

**Comment by pchampio** [comment]
The Chinese characters issue is described in: https://github.com/go-flutter-desktop/go-flutter/issues/355 (linux only issue).

Still, `hover bumpversion` doesn't work.
@jld3103 can you add a condition on the command to only

append `GOPROXY=direct` to `cmdGoGetU.Env` if `buildOrRunGoFlutterBranch` has a `/` in it's name. Thanks
https://github.com/go-flutter-desktop/hover/blob/df5597276fcc278762c31302cc345abcbc7afa0b/cmd/bumpversion.go#L50-L59
