### ISSUE TITLE
hover: Cannot obtain version information from hover build.

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [go-flutter-desktop/go-flutter#471]
## Hover doctor

```
yazeed@Yazeed-AlKhalaf-Ubuntu:~/development/code/my_projects/flutter_projects/split_it$ hover doctor
hover: Cannot obtain version information from hover build. To resolve this, please go-get hover using Go 1.13 or newer.
```

## Error output

Using `hover run` to build my application, I get the following
error:

```log
yazeed@Yazeed-AlKhalaf-Ubuntu:~/development/code/my_projects/flutter_projects/split_it$ hover run
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Building flutter bundle
Font subetting is not supported in debug mode. The --tree-shake-icons flag will be ignored.
hover: Using engine from cache
hover: Cannot obtain version information from hover build. To resolve this, please go-get hover using Go 1.13 or newer.
```

**Comment by jld3103** [comment]
Which go version are you using? You need to user >=1.13

**Comment by YazeedAlKhalaf** [comment]
>=1.13 I am using latest 1.14

**Comment by YazeedAlKhalaf** [comment]
yazee@Yazeed-AlKhalaf MSYS ~
$ go version
go version go1.14.4 windows/amd64

**Comment by YazeedAlKhalaf** [comment]
When I try running hover version the same happens, I think there is a problem with it

**Comment by pchampio** [comment]
`go env GO111MODULE` must be set to `on`.

Did you installed hover with:
`GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover`
?

**Comment by YazeedAlKhalaf** [comment]
Yes I did

**Comment by YazeedAlKhalaf** [comment]
Yes I did install it with the variable on

**Comment by YazeedAlKhalaf** [comment]
I have discovered that I have to change the variable globally before running the installation. Anyways thank to @pchampio

**Comment by SureshKumar311** [comment]
i had install go in my system 
but GO111MODULE=on is not  recognized 

C:\Users\sk>GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover
'GO111MODULE' is not recognized as an internal or external command,
operable program or batch file.

**Comment by SureshKumar311** [comment]
the hover is install but not correctly in my system 
i am geting error 


C:\Users\sk>hover
Hover helps developers to release Flutter applications on desktop.

Usage:
  hover [command]

Available Commands:
  build          Build a desktop release
  bumpversion    upgrade the 'go-flutter' golang library in this project
  doctor         Show information about the installed tooling
  help           Help about any command
  init           Initialize a flutter project to use go-flutter
  init-packaging Create configuration files for a packaging format
  init-plugin    Initialize a go-flutter plugin in a existing flutter platform plugin
  plugins        Tools for plugins
  publish-plugin Publish your go-flutter plugin as golang module in your github repo.
  run            Build and start a desktop release, with hot-reload support
  version        Print Hover version information

Flags:
      --colors    Add colors to log (default true)
      --docker    Run the command in a docker container for hover
  -h, --help      help for hover
  -v, --verbose   increase logging verbosity

Use "hover [command] --help" for more information about a command.

C:\Users\sk>hover version
hover: Cannot obtain version information from hover build. To resolve this, please go-get hover using Go 1.13 or newer.

**Comment by SureshKumar311** [comment]
thank for u help @pchampio 
 now working 

C:\Users\sk>go env GO111MODULE =on
on


C:\Users\sk>GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover
'GO111MODULE' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\sk>go get -u -a github.com/go-flutter-desktop/hover
go: downloading github.com/go-flutter-desktop/hover v0.43.0
go: github.com/go-flutter-desktop/hover upgrade => v0.43.0
go: downloading golang.org/x/mod v0.3.0
go: downloading github.com/GeertJohan/go.rice v1.0.0
go: downloading github.com/hashicorp/go-version v1.2.1
go: downloading github.com/Kodeworks/golang-image-ico v0.0.0-20141118225523-73f0f4cfade9
go: downloading github.com/daaku/go.zipexe v1.0.1
go: downloading github.com/tcnksm/go-latest v0.0.0-20170313132115-e3007ae9052e
go: downloading golang.org/x/xerrors v0.0.0-20191011141410-1b5146add898
go: downloading golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading github.com/otiai10/copy v1.2.0
go: downloading github.com/google/go-querystring v1.0.0
go: github.com/spf13/pflag upgrade => v1.0.5
go: gopkg.in/yaml.v2 upgrade => v2.3.0
go: github.com/pkg/errors upgrade => v0.9.1
go: github.com/daaku/go.zipexe upgrade => v1.0.1
go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
go: golang.org/x/net upgrade => v0.0.0-20200904194848-62affa334b73
go: golang.org/x/sys upgrade => v0.0.0-20200918174421-af09f7315aff
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/sys v0.0.0-20200918174421-af09f7315aff

C:\Users\sk>hover
Hover helps developers to release Flutter applications on desktop.

Usage:
  hover [command]

Available Commands:
  build          Build a desktop release
  bumpversion    upgrade the 'go-flutter' golang library in this project
  doctor         Show information about the installed tooling
  help           Help about any command
  init           Initialize a flutter project to use go-flutter
  init-packaging Create configuration files for a packaging format
  init-plugin    Initialize a go-flutter plugin in a existing flutter platform plugin
  plugins        Tools for plugins
  publish-plugin Publish your go-flutter plugin as golang module in your github repo.
  run            Build and start a desktop release, with hot-reload support
  version        Print Hover version information

Flags:
      --colors    Add colors to log (default true)
      --docker    Run the command in a docker container for hover
  -h, --help      help for hover
  -v, --verbose   increase logging verbosity

Use "hover [command] --help" for more information about a command.

C:\Users\sk>hover version
Hover v0.43.0
