### ISSUE TITLE
Hover. Failed to download engine: remote error: tls: handshake failure

### ISSUE THREAD

**Issue by chuguofei** [go-flutter-desktop/go-flutter#472]
hover: Downloading engine for platform darwin-x64 at version 49891e065313d26bbc2ddc9805fb7ed27edae174...
hover: Failed to download engine: Get "https://storage.flutter-io.cn/flutter_infra/flutter/49891e065313d26bbc2ddc9805fb7ed27edae174/darwin-x64/FlutterEmbedder.framework.zip": remote error: tls: handshake failure

**Comment by pchampio** [comment]
Humm, are you using a VPN?
Are you located under China's 'Great Firewall?

**Comment by pchampio** [comment]
https://github.com/go-flutter-desktop/hover/blob/b250fc13e9e87549c3c30f94d6e2fdb5de954e69/internal/enginecache/cache.go#L248-L252

https://flutter.dev/community/china

**Comment by chuguofei** [comment]
> https://github.com/go-flutter-desktop/hover/blob/b250fc13e9e87549c3c30f94d6e2fdb5de954e69/internal/enginecache/cache.go#L248-L252
> 
> https://flutter.dev/community/china

ok，I've solved it； Can this be embedded in the web page
