### ISSUE TITLE
Support flavors

### ISSUE THREAD

**Issue by jld3103** [go-flutter-desktop/go-flutter#475]
I want to migrate my app to use flavors, because it is a modular app and we publish two versions with different features included.
Hover should support `--flavor` and use `go/hover.yaml` to determine the flavor config. That should include the application, executable and package name, license, and target.

This feature shouldn't be too hard to implement, because the existing config can be used to create a list of the above mentioned config keys per flavor.
The icon should also be easy, because we can just do something like `icon-${flavor}.png` and copy it to the alread used `icon.png`.
So backwards compatability should be easy to maintain.

Thoughts @GeertJohan @pchampio ?

**Comment by GeertJohan** [comment]
I like the idea of flavors. I use it in some non-desktop apps. So +1 on the feature request.
Needs some proper brainstorm on implementation details though.

**Comment by edTheGuy00** [comment]
Currently I have a `Makefile` that just replaces the contents of `hover.yaml`. 

I was looking though the code and saw that [`"hover.yaml"`](https://github.com/go-flutter-desktop/hover/blob/master/internal/config/config.go#L76) is just hardcoded in there. 

Ideally, a `--flavor` flag can be added on [run.go](https://github.com/go-flutter-desktop/hover/blob/master/cmd/run.go) and [build.go](https://github.com/go-flutter-desktop/hover/blob/master/cmd/build.go) which could select the desired flavor eg.

`hover run --flavor FLAVOR_NAME` -> `hover-FLAVOR_NAME.yaml`

**Comment by jld3103** [comment]
That sounds better than my idea, especially because backwards compatibility is preserved
