### ISSUE TITLE
utf-8 textinput

### ISSUE THREAD

**Issue by pchampio** [go-flutter-desktop/go-flutter#478]
Uses utf-8 internally

https://github.com/flutter/flutter/pull/53381 was merge, no need for the utf-16/utf-8 rollercoster used in the text-input.go plugin.

Waiting for this feature to be available in flutter channel beta.

**Comment by jld3103** [comment]
That PR got reverted for now, because it caused some problems https://github.com/flutter/flutter/issues/59645

**Comment by justinmc** [comment]
Hopefully I'll be able to un-revert that PR soon in https://github.com/flutter/flutter/pull/59778.

**Comment by pchampio** [comment]
On the embedder side, uft16 is the default text encoding. https://github.com/flutter/engine/pull/17831
