### ISSUE TITLE
32-bit mingw compiler accidentally picked up

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#479]
```
 hover run
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Building flutter bundle
hover: Missing/Empty `version` field in pubspec.yaml. Please add it or otherwise you may publish your app with a wrong version. Continuing with `0.0.1` as a placeholder version.
hover: Using engine from cache
hover: Compiling 'go-flutter' and plugins
runtime/cgo
# runtime/cgo
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
hover: Go build failed: exit status 2
```

Any idea？

**Comment by jld3103** [comment]
From this thread https://github.com/hajimehoshi/ebiten/issues/689 I would guess you have a 32-bit mingw version installed which gets used for cgo. If you also have a 64-bit version installed you need to change the default pickup and if you don't have a 64-bit version installed you need to install one.

**Comment by jld3103** [comment]
Maybe we should limit go-flutter compilation to `x86_64` using
```go
// +build amd64
```
What do you think @pchampio @GeertJohan

**Comment by GeertJohan** [comment]
I'm not sure if we'd want to limit to amd64 only, maybe we could also support ARM targets, but that needs work on enginecache and packaging.

**Comment by pchampio** [comment]
hover's requirement is specified in the hover's readme.
https://github.com/golang/go/wiki/InstallFromSource#install-c-tools
