### ISSUE TITLE
can not show emoji on linux

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#481]
Does any one knows why?

![image](https://user-images.githubusercontent.com/21303438/85508092-fc3b2080-b625-11ea-9650-dc3c3d256f8e.png)

Even my terminal can printout emoji:

![image](https://user-images.githubusercontent.com/21303438/85508122-09f0a600-b626-11ea-8296-351daea14120.png)

```
flutter: get projects: 2
flutter: {🚖 工作 2: 2.0, 🍓 生活 0: 0.0}

```

**Comment by GeertJohan** [comment]
Most likely the font is missing emojii's.
Make sure you have the font you want to use in the assets folder and linked in pubspec.yaml.
If the font is not in your app, then Flutter will try to use the fonts from the operating system, but you can never be sure your users have the font you want to use. So always bundle fonts with your app.
Please re-open this issue if the problem did not go away after adding the font to your app.

**Comment by pchampio** [comment]
![image](https://user-images.githubusercontent.com/7476655/86784797-395dd480-c062-11ea-93f1-90feb988b67b.png)
Tested with https://github.com/samuelngs/apple-emoji-linux and  https://github.com/MorbZ/OpenSansEmoji and the emoji where properly displayed.

Still, you have to bundle the font in the app. Like in this example: https://github.com/go-flutter-desktop/examples/blob/768b3c12b46778d78c7bc1edf29b957777be87e6/text_demo/pubspec.yaml#L43-L57

**Comment by pchampio** [comment]
All other font related information can be found here: https://github.com/flutter/flutter/issues/30700#issuecomment-541269268

**Comment by jinfagang** [comment]
@pchampio  thanks for your reply. I actually buddled the fonts to my app, and the normal text ca be shown (charactors), only emoji can not shown. 

Did u guys means, my custom fonts doesn't contain emoji? I suppose emoji is not related with fonts but system encoded pattern to show. My system is linux, and my linux can show emoji in terminal (as you can see ) at least the terminal shows like a normal emoji rather than boxes.

So, I have already added fonts in my pubspec.yml, what else need I do to make it show? By using default fonts?

**Comment by pchampio** [comment]
> Did u guys means, my custom fonts doesn't contain emoji? I suppose emoji is not related with fonts but system encoded pattern to show. My system is linux, and my linux can show emoji in terminal (as you can see ) at least the terminal shows like a normal emoji rather than boxes.

Please read the above comment https://github.com/flutter/flutter/issues/30700#issuecomment-541269268 

Here is an example: 
https://file.io/2xJLLY7q

**Comment by jinfagang** [comment]
https://file.io/EBfmqaQ7 this link shows 404.

So, is because linux can not found the last fallback font which is Robo font on linux?

how to set a fallback font on linux since every font maybe missing and different paltform may have different fallback font.

What's the standard solution for this? I think this is a simple and foundamental using scenarios of apps on desktop.

**Comment by pchampio** [comment]
https://we.tl/t-J5V6fZcKtl

**Comment by pchampio** [comment]
> So, is because linux can not found the last fallback font which is Robo font on linux?
how to set a fallback font on linux since every font maybe missing and different paltform may have different fallback font.
What's the standard solution for this? I think this is a simple and foundamental using scenario of apps on desktop.

I don't have answer to your questions, the level of which go-flutter operates isn't on that level.
What's I can say is that bundling a font that has support for emoji and using this font in your applications works.

**Comment by jinfagang** [comment]
@pchampio  thanks! weird thing I test again on windows, it can show emoji, if it related about fonts, this shouldn't happen.

Anyway, I will test add fallback fonts on ubuntu
