### ISSUE TITLE
Building/Crosscompiling for Linux ARM/ARM64

### ISSUE THREAD

**Issue by NO-ob** [go-flutter-desktop/go-flutter#486]
It may already be possible but i'm not sure I was wondering if support could be added to build and crosscompile appimages for arm/aarch64 on linux?

**Comment by jld3103** [comment]
It's not possible yet. To make it possible we either need https://github.com/go-flutter-desktop/go-flutter/issues/363 or the flutter team uploads the needed engine files.

**Comment by NO-ob** [comment]
I opened an issue on the flutter repo here https://github.com/flutter/flutter/issues/60678

**Comment by jld3103** [comment]
I'm also interested in this feature for a new project so I'm going try to setup some CI that builds the engines and make hover compatible.

**Comment by jld3103** [comment]
@NO-ob 
> It doesn't support cross compiling so the end goal is to build the app with go flutter on the pinephone for the pinephone

This currently true, but adding cross-compile functionality is mandatory for easy development so that will be included when I add the feature to hover

**Comment by jld3103** [comment]
After reading some issues and PRs in the flutter repo it seems like there are already people working on supporting arm64 targets in flutter with all the required infrastructure. So it's better to wait for the engines to become available than trying to compile them ourself.

**Comment by NO-ob** [comment]
The arm64 engine changes have been merged now I think https://github.com/flutter/engine/pull/20254#issuecomment-694546839

**Comment by jld3103** [comment]
Then we need support for engines in https://github.com/flutter-rs/engine-builds . I'll ask them and update this issue when something changes

**Comment by jld3103** [comment]
https://github.com/flutter/flutter/projects/181#card-48274867

**Comment by pchampio** [comment]
Duplicate (or related) to https://github.com/go-flutter-desktop/go-flutter/issues/363
