### ISSUE TITLE
Where to put a function to trigger on exit/stop/close event of application?

### ISSUE THREAD

**Issue by satindergrewal** [go-flutter-desktop/go-flutter#489]
I'm running a gRPC server via ffi and flutter Isolates, and when I close the application I keep getting the following waiting for isolates to check in.

I can make a function to stop the server, but I need to know where to put it to trigger on application close/exit action.

Can you please tell me how can I trigger a function to stop the server when exiting the application?

```
An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:50300/
go-flutter: closing application
Attempt:11 waiting for isolate _startGrpc to check in
Attempt:12 waiting for isolate _startGrpc to check in
```

This is the example code that I'm using to test go-flutter: https://github.com/satindergrewal/flutter-practice/tree/master/flutter_isolates

Thanks,
Satinder

**Comment by pchampio** [comment]
Since you are using FFI, you only use go-flutter for embedding. Even if we had exit/stop/close event, you couldn't query them since you aren't writing a go-flutter plugin https://github.com/go-flutter-desktop/go-flutter/wiki.

This issue is FFI related, please ask for help directly through the flutter/flutter issue tracker.

**Comment by satindergrewal** [comment]
Okay, thanks for quick response @pchampio 👍 
I'll ask for help on flutter/dart resources.

**Comment by satindergrewal** [comment]
@pchampio from https://github.com/flutter/flutter/issues/61372#issuecomment-660380405

> A Dart hook that would allow you to know when the app is exiting falls under #30735; closing as a duplicate.

> Note that there's no reason you (or go-flutter) couldn't write this functionality in the short term for your application using native code and method channels. The only thing that go-flutter would need Flutter support for is having a standard API already defined. (And if/when such an API is defined, go-flutter will still have to implement support for it.)

Is that something go-flutter can help with?
Or in case give me some pointers what needs to be done, at least I'll try to attempt solving it.

**Comment by pchampio** [comment]
As Stuart said:
> The only thing that go-flutter would need Flutter support for is having a standard API already defined. (And if/when such an API is defined, go-flutter will still have to implement support for it.)

So on the go flutter side, we are waiting of the standard API to come and implement it.

Nevertheless, you can still write a go- flutter glfw plugin that send a close trigger when the application closes.
Check out our wiki for more information on how to write such plugin.

**Comment by pchampio** [comment]
Issue tracker by: https://github.com/flutter/flutter/issues/30735
