### ISSUE TITLE
emoji and Chinese support at the same time on Linux

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#492]
Hi, I have posted simillar question before, my problem get quite embarrasing, I really want a help.

Some of your main develop give me a solution and example to show emoji shows correctly on linux. I runed it, and it indeed shows emoji.

But when I using that font, my Chinese gets mess again:
![image](https://user-images.githubusercontent.com/21303438/87393634-104cbf00-c5e1-11ea-81a1-8968e33d5c65.png)

So, my question is, how to make emoji and Chinese look nice at the same time? Cause when I using my custom Chinese font, emoji doesn't shows well

**Comment by pchampio** [comment]
Pick a Chinese font that have support for emoji.
Or, merge both individual fonts into a single one that have graphemes for emoji and Chinese entires.

**Comment by jinfagang** [comment]
@pchampio  How to check a font has emoji or not? Can u give me an advise?

**Comment by jinfagang** [comment]
@pchampio Sorry for bother, I have tried several other very very common fonts in Chinese such as 宋体 and 微软雅黑, if those can not support emoji, can u tell me which on can support?

After change to them, nothing changed:

![image](https://user-images.githubusercontent.com/21303438/87504979-5154da00-c69a-11ea-925a-7406014be0d6.png)

**Comment by jld3103** [comment]
Look at this: https://superuser.com/a/1382162/955784 Something like that should work so you can merge the Chinese font with the Emoji font

**Comment by jinfagang** [comment]
@jld3103 thanks for your link. I have look around, merging fonts using fontforge or script like that one is for English mostly, Chinese  have encoding issue. Really, except of this, anyone could give me a indicate which a simple way to using go-flutter-desktop with Chinese and emoji?

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/87514735-4788a200-c6ad-11ea-96af-155e3f3f15c3.png)

**Comment by jinfagang** [comment]
Allright... I tried merge a standalone emoji font....

![image](https://user-images.githubusercontent.com/21303438/87516188-933c4b00-c6af-11ea-8996-0b5128e2742d.png)

It breaks some existed charactors and the size is so large..
