### ISSUE TITLE
[Dart FFI] An example on how to use async callbacks between Dart and golang?

### ISSUE THREAD

**Issue by ganeshrvel** [go-flutter-desktop/go-flutter#498]
I have been trying to setup a project which requires to make async calls from Flutter to golang native functions.  There is an example for the same https://github.com/dart-lang/sdk/tree/master/samples/ffi/async but the code is vague to get started.

According to https://github.com/dart-lang/sdk/issues/37022 they have recently added callback support from the native code to the dart code via Nativeport. But I am unable to get it working with golang.

It would be great if you guys could give us an example code which could get us started on async calls to native code and callbacks from go to dart. 

I had appreciate any sort of help.

**Comment by ganeshrvel** [comment]
@jld3103 any updates on this?

**Comment by jld3103** [comment]
I wasn't able to get it working, but I think it is possible. I guess it was especially hard, because I was using a static Rust librarys

**Comment by ganeshrvel** [comment]
Please let us know if you were able to get it working. Please keep this issue open till then.

**Comment by jld3103** [comment]
I'm not working on it, because I have no project that needs it, but still this issue should be kept open

**Comment by ganeshrvel** [comment]
Finally an engineer from Google made this happen.

Use Dart FFI and Go asynchronously.
 https://github.com/mraleph/go_dart_ffi_example

Thanks to @mraleph 🎉

**Comment by jld3103** [comment]
That's really cool

**Comment by jerson** [comment]
@ganeshrvel i have a library using golang (ffi and also protobuf for messages) and dart, also Hover :D if you want to take a look here it is
https://github.com/jerson/flutter-rsa
