### ISSUE TITLE
New system channels

### ISSUE THREAD

**Issue by jld3103** [go-flutter-desktop/go-flutter#503]
```log
go-flutter: no method handler registered for method 'routeUpdated' on channel 'flutter/navigation'
```
https://github.com/flutter/flutter/pull/60299

**Comment by chunhtai** [comment]
This should not have throw because we also change the navigation channel to OptionalMethodChannel. Do you have a repro?

**Comment by jld3103** [comment]
It only happened once seemingly random. I've never seen it again.

**Comment by stuartmorgan** [comment]
> This should not have throw because we also change the navigation channel to OptionalMethodChannel.

@chunhtai This isn't throwing; that message is coming from the go-flutter-desktop embedding, which [logs every unrecognized method channel call](https://github.com/go-flutter-desktop/go-flutter/blob/2a5ae05b74a731701781bc9d02d788e35025c804/plugin/method-channel.go#L199).

I'm not sure why this embedding does that, given that it's at odds with the concept of `OptionalMessageChannel`, but it's not a Flutter issue.
