### ISSUE TITLE
The` hover build windows-msi -- docker` is used to package MSI files in Windows environment.But when you run this file in a Windows environment, you will be prompted

### ISSUE THREAD

**Issue by MiSeWang** [go-flutter-desktop/go-flutter#509]
Hover： v0.42.0

go-flutter： v0.41.2

The` hover build windows-msi -- docker` is used to package MSI files in Windows environment.But when you run this file in a Windows environment, you will be prompted
**Aportion of the folder path "is invalid. It is either empty or exceeds the length allowed by the system.**
When packaged with pointer_demo, it will run successfully. 
What are the possible reasons for the prompt?Sorry, this is very important to me. I hope you can let me know if you know.
Can I choose the installation path or the path to generate the shortcut?Finally, we want to have a variety of packaged use cases or documents that might be helpful to the user.

**Comment by jld3103** [comment]
Can you make an exact list of steps to reproduce this?
