### ISSUE TITLE
MacOS shortcut support

### ISSUE THREAD

**Issue by zephylac** [go-flutter-desktop/go-flutter#51]
## Flutter version
```
Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (2 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

## Does the prebuilt and portable version works ?
Yes

###### Download [Link](https://github.com/Drakirus/go-flutter-desktop-embedder/releases)
 - No

## Steps to Reproduce

Under MacOS High Sierra 10.13.6, shortcuts doesn't works. I also tested on MacOS Mojave, I would assume it won't work on any MacOS.

After doing so testing. When checking for copy and paste, the key cmd is not tested.
Current:   `mods == glfw.ModControl`  
Fix : `(mods == glfw.ModControl || mods == glfw.ModSuper)` 

This fix might broke copy and paste from other architecture since I didn't check if `glfw.ModSuper` is fired when pressing windows or linux key on keyboard.

I'm working on a fix right  now.

**Comment by zephylac** [comment]
https://github.com/Drakirus/go-flutter-desktop-embedder/tree/feature/MacOS_Shortcuts

**Comment by GeertJohan** [comment]
Perhaps the modifier key should be selected using go build tags.
https://golang.org/pkg/go/build/

A file that's just compiled for GOOS=darwin could override the default modifier key to ModSuper.

**Comment by zephylac** [comment]
I agree, I've done this in the new branch that supports keyboard shortcuts for MacOS

[sample](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/feature/MacOS_Shortcuts/gutter.go#L102-L109)

**Comment by GeertJohan** [comment]
@zephylac Could you open a PR for this?

**Comment by zephylac** [comment]
Merged branch
