### ISSUE TITLE
 Cannot obtain version information from hover build.

### ISSUE THREAD

**Issue by SureshKumar311** [go-flutter-desktop/go-flutter#513]
when is use to run hover doctor i dot issue  

E:\project_flutter\examples-master\text_demo> hover doctor
hover: Cannot obtain version information from hover build. To resolve this, please go-get hover using Go 1.13 or newer.

when is use to run in project 

 E:\project_flutter\examples-master\text_demo> hover run
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Building flutter bundle
hover: Using engine from cache
hover: Cannot obtain version information from hover build. To resolve this, please go-get hover using Go 1.13 or newer.

plz help me 
thank you advance

**Comment by pchampio** [comment]
The `GO111MODULE=on` must be set to 'on'
System-wide overwrite: `go env -w GO111MODULE=on`

**Comment by SureshKumar311** [comment]
i had tried but same error


C:\Users\sk>go env -w GO111MODULE=on

C:\Users\sk>hover version
hover: Cannot obtain version information from hover build. To resolve this, please go-get hover using Go 1.13 or newer.
