### ISSUE TITLE
creating glfw window: APIUnavailable: WGL: The driver does not appear to support OpenGL hover: App 'text_demo' exited with error: exit status 1

### ISSUE THREAD

**Issue by SureshKumar311** [go-flutter-desktop/go-flutter#514]
i am in master mode of flutter channel
i had install go and hover 
but i am getting error plz help to slove this error

E:\project_flutter\examples-master\text_demo>hover run
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Building flutter bundle
hover: Using engine from cache
hover: Checking available release on Github
hover: Failed to retrieve the organization name: open android/app/src/main/AndroidManifest.xml: The system cannot find the path specified.
hover: Compiling 'go-flutter' and plugins
go: downloading github.com/go-flutter-desktop/go-flutter v0.42.0
go: downloading github.com/go-gl/glfw/v3.3/glfw v0.0.0-20200707082815-5321531c36a2
go: downloading github.com/Xuanwo/go-locale v0.3.0
go: downloading github.com/go-gl/gl v0.0.0-20190320180904-bf2b1f2f34d7
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/go-ole/go-ole v1.2.4
golang.org/x/text/internal/tag
github.com/go-ole/go-ole
golang.org/x/text/internal/language
golang.org/x/text/internal/language/compact
github.com/go-ole/go-ole/oleutil
golang.org/x/text/language
runtime/cgo
github.com/Xuanwo/go-locale
github.com/go-flutter-desktop/go-flutter/internal/debounce
github.com/go-flutter-desktop/go-flutter/internal/execpath
github.com/go-flutter-desktop/go-flutter/internal/tasker
github.com/go-flutter-desktop/go-flutter/plugin
github.com/go-flutter-desktop/go-flutter/internal/currentthread
github.com/go-flutter-desktop/go-flutter/embedder
github.com/go-gl/glfw/v3.3/glfw
github.com/go-gl/gl/v3.3-core/gl
github.com/go-flutter-desktop/go-flutter/internal/keyboard
github.com/go-flutter-desktop/go-flutter/internal/priorityqueue
github.com/go-flutter-desktop/go-flutter/internal/opengl
github.com/go-flutter-desktop/go-flutter
text_demo/go/cmd
hover: Successfully compiled executable binary for windows
hover: Build finished, starting app...
hover: Running text_demo in debug mode
creating glfw window: APIUnavailable: WGL: The driver does not appear to support OpenGL
hover: App 'text_demo' exited with error: exit status 1

E:\project_flutter\examples-master\text_demo>hover
Hover helps developers to release Flutter applications on desktop.

Usage:
  hover [command]

Available Commands:
  build          Build a desktop release
  bumpversion    upgrade the 'go-flutter' golang library in this project
  doctor         Show information about the installed tooling
  help           Help about any command
  init           Initialize a flutter project to use go-flutter
  init-packaging Create configuration files for a packaging format
  init-plugin    Initialize a go-flutter plugin in a existing flutter platform plugin
  plugins        Tools for plugins
  publish-plugin Publish your go-flutter plugin as golang module in your github repo.
  run            Build and start a desktop release, with hot-reload support
  version        Print Hover version information

Flags:
      --colors    Add colors to log (default true)
      --docker    Run the command in a docker container for hover
  -h, --help      help for hover
  -v, --verbose   increase logging verbosity

Use "hover [command] --help" for more information about a command.

E:\project_flutter\examples-master\text_demo>hover doctor
hover: Hover version v0.43.0 running on windows
hover: Sharing flutter version
Flutter 1.22.0-10.0.pre.269 • channel master • https://github.com/flutter/flutter.git
Framework • revision 51fa704642 (2 days ago) • 2020-09-19 11:27:04 -0700
Engine • revision 4b8477d115
Tools • Dart 2.10.0 (build 2.10.0-142.0.dev)
hover: Flutter engine commit: https://github.com/flutter/engine/commit/4b8477d11573d233e6791204191c0090f733b05d
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Finding out the C compiler version
gcc (tdm64-1) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

hover: Sharing the content of go.mod
module text_demo/go

go 1.13

require (
        github.com/go-flutter-desktop/go-flutter v0.42.0
        github.com/pkg/errors v0.9.1
)

// replace github.com/go-flutter-desktop/go-flutter => /home/pchampio/lab/go/src/github.com/go-flutter-desktop/go-flutter
hover: Sharing the content of hover.yaml
application-name: ""
executable-name: ""
package-name: ""
license: ""
target: lib/main_desktop.dart
branch: ""
cache-path: ""
opengl: ""
engine-version: ""
hover: Sharing the content of go/cmd
go\cmd\main.go  go\cmd\options.go

**Comment by pchampio** [comment]
Are you running your app in a VM?
Could you try `hover run --opengl=none`

**Comment by pchampio** [comment]
Without additional information, we are unfortunately not sure how to resolve
this issue. We are therefore reluctantly going to close this bug for now. Please
don't hesitate to comment on the bug if you have any more information for us; we
will reopen it right away!
Thanks for your contribution.
