### ISSUE TITLE
Help -> Mac: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by bettersun** [go-flutter-desktop/go-flutter#517]
MacOS High Serria(10.13.6)

$ hover run
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Building flutter bundle
hover: Using engine from cache
hover: Checking available release on Github
hover: Failed to check the latest release of 'hover': Get https://api.github.com/repos/go-flutter-desktop/hover/tags: dial tcp 13.250.168.23:443: connect: connection refused
hover: Failed to write the update timestamp to file: open /Users/sunjiashu/Library/Caches/hover/.last_hover_check: permission denied
hover: Compiling 'go-flutter' and plugins
github.com/go-flutter-desktop/go-flutter/embedder
\# github.com/go-flutter-desktop/go-flutter/embedder
Undefined symbols for architecture x86_64:
  "_FlutterEngineCollectAOTData", referenced from:
      __cgo_09bdfa4a8952_Cfunc_FlutterEngineCollectAOTData in _x003.o
     (maybe you meant: __cgo_09bdfa4a8952_Cfunc_FlutterEngineCollectAOTData)
  "_FlutterEngineCreateAOTData", referenced from:
      __cgo_09bdfa4a8952_Cfunc_FlutterEngineCreateAOTData in _x003.o
     (maybe you meant: __cgo_09bdfa4a8952_Cfunc_FlutterEngineCreateAOTData)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
hover: Go build failed: exit status 2

**Comment by jld3103** [comment]
It's likely that you are using an old version of flutter since the required features already arrived in the stable channel, but for go-flutter you should use the beta channel, so please try updating flutter.
If it doesn't fix it run `hocer doctor` and comment the output.

**Comment by bettersun** [comment]
> 
> 
> It's likely that you are using an old version of flutter since the required features already arrived in the stable channel, but for go-flutter you should use the beta channel, so please try updating flutter.
> If it doesn't fix it run `hover doctor` and comment the output.

Thank you very much.

**Comment by bettersun** [comment]
This problem is fixed on flutter 1.20.4.
