### ISSUE TITLE
hover: To package windows-msi these tools are required: candle,light

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#520]
```
hover: To package windows-msi these tools are required: candle,light
```

Any instructions on install this?

**Comment by jld3103** [comment]
The instructions should be clearer. Install them from https://wixtoolset.org/

**Comment by jinfagang** [comment]
@jld3103  I install wix, but it still claims this:

```
hover: To package windows-msi these tools are required: candle,light
```
Sorry, I think it's much more better if error messages download link along with candle and light, honestly I don't why what's this can when google it, I got only this"

![image](https://user-images.githubusercontent.com/21303438/95748627-da48d500-0ccc-11eb-8a37-69d70f27c16c.png)

And what's this? This is real candle used in windows:

![image](https://user-images.githubusercontent.com/21303438/95748769-1d0aad00-0ccd-11eb-97af-4f4737e2cfce.png)


Honestly I am totally lost which these weired names.

**Comment by jinfagang** [comment]
Solved it

**Comment by pchampio** [comment]
How did you solved the problem ?

**Comment by jinfagang** [comment]
@pchampio downloaded from web

**Comment by ablockhead** [comment]
I have the same problem. Where can I download it?

**Comment by jld3103** [comment]
Please read the conversatio above
