### ISSUE TITLE
Allow Icons conversion without docker for Bundling for darwin and linux

### ISSUE THREAD

**Issue by gedw99** [go-flutter-desktop/go-flutter#521]
Currently the packaging for darwin and linux uses a nodejs thing.

````
requiredTools: map[string][]string{
			"linux":  {"png2icns"},
			"darwin": {"png2icons"},
		},
````

We can use golang code at https://github.com/scott-x/icns to replace it.
For Windows, i have not had a change to look. It seems to need candle and light which are only for Windows. 

The changes in https://github.com/go-flutter-desktop/hover/blob/master/cmd/packaging/darwin-bundle.go would be as follows. I left the old code there that calls docker but commented out.

This code seems to work for me.

````

package packaging

import (
	"fmt"
	"image"
	"log"
	"os"
	"path/filepath"
	"runtime"

	"github.com/JackMordaunt/icns"
)

// DarwinBundleTask packaging for darwin as bundle
var DarwinBundleTask = &packagingTask{
	packagingFormatName: "darwin-bundle",
	templateFiles: map[string]string{
		"darwin-bundle/Info.plist.tmpl": "{{.applicationName}} {{.version}}.app/Contents/Info.plist.tmpl",
	},
	executableFiles:             []string{},
	flutterBuildOutputDirectory: "{{.applicationName}} {{.version}}.app/Contents/MacOS",
	packagingFunction: func(tmpPath, applicationName, packageName, executableName, version, release string) (string, error) {
		outputFileName := fmt.Sprintf("%s %s.app", applicationName, version)
		err := os.MkdirAll(filepath.Join(tmpPath, outputFileName, "Contents", "Resources"), 0755)
		if err != nil {
			return "", err
		}

		iconPath := ""
		icnsPath := ""
		switch os := runtime.GOOS; os {
		case "darwin":
			iconPath = filepath.Join(outputFileName, "Contents", "MacOS", "assets", "icon.png")
			icnsPath = filepath.Join(outputFileName, "Contents", "Resources", "icon")
		case "linux":
			iconPath = filepath.Join(outputFileName, "Contents", "Resources", "icon.icns")
			icnsPath = filepath.Join(outputFileName, "Contents", "MacOS", "assets", "icon.png")
		}

		pngf, err := os.Open(iconPath)
		if err != nil {
			log.Fatalf("opening source image: %v", err)
		}
		defer pngf.Close()

		srcImg, _, err := image.Decode(pngf)
		if err != nil {
			msg := fmt.Sprintf("decoding source image: %v", err)
			log.Fatalf(msg)
			return msg, err

		}

		dest, err := os.Create(icnsPath)
		if err != nil {
			msg := fmt.Sprintf("opening destination file: %v", err)
			log.Fatalf(msg)
			return msg, err
		}
		defer dest.Close()

		if err := icns.Encode(dest, srcImg); err != nil {
			msg := fmt.Sprintf("encoding icns: %v", err)
			log.Fatalf(msg)
			return msg, err
		}

		return outputFileName, nil
		/*
				var cmdPng2icns *exec.Cmd
				switch os := runtime.GOOS; os {
				case "darwin":
					// https://www.npmjs.com/package/png2icons
					// call signature: png2icons infile outfile format
					cmdPng2icns = exec.Command("png2icons", filepath.Join(outputFileName, "Contents", "MacOS", "assets", "icon.png"), filepath.Join(outputFileName, "Contents", "Resources", "icon"), "-icns")
				case "linux":
					cmdPng2icns = exec.Command("png2icns", filepath.Join(outputFileName, "Contents", "Resources", "icon.icns"), filepath.Join(outputFileName, "Contents", "MacOS", "assets", "icon.png"))
				}
				cmdPng2icns.Dir = tmpPath
				cmdPng2icns.Stdout = os.Stdout
				cmdPng2icns.Stderr = os.Stderr
				err = cmdPng2icns.Run()
				if err != nil {
					return "", err
				}

			return outputFileName, nil
		*/
	},
	/*
		requiredTools: map[string][]string{
			"linux":  {"png2icns"},
			"darwin": {"png2icons"},
		},
	*/

	// None required
	requiredTools: map[string][]string{},
}

````

**Comment by gedw99** [comment]
I see that for Windows its here: https://github.com/wixtoolset/wix3/releases/tag/wix3112rtm
In the wix311-binaries.zip is candle and light.

So i was thinking that we can add a function to hover to check if its on your disk and if not pull it in.

This would i think make all desktop builds work without docker, unless i have missed something

**Comment by jld3103** [comment]
Sounds like a good idea to convert the png to icns using go, but you linked https://github.com/scott-x/icns in the comment and used https://github.com/JackMordaunt/icns in the code. I guess you meant to link to the later.
Also pulling the wix binaries would be a possibility, but I'm unsure if that should really be done. The other thing is that they only provide windows binaries so it won't work on MacOS and Linux natively, but I tested it on wine and that works.

Can you please open a separate issue for the wix thing? Both issues in one gets messy

**Comment by gedw99** [comment]
@jld3103 

Yes i made a mistake with https://github.com/scott-x/icns. thanks for catching it :)

Also, i hit a problem with **packaging.go** (https://github.com/go-flutter-desktop/hover/blob/master/cmd/packaging/packaging.go#L73)  not respecting the fact that my code did not have any required tools. You might know why better than me.

``` 
// None required 
	requiredTools: map[string][]string{},
``` 


Regarding the wix binaries. Yes i will open a different issue.

**Comment by jld3103** [comment]
You need to put an empty slice for all supported OS like this:
```go
requiredTools: map[string][]string{
  "linux": []string{},
},
```

**Comment by jld3103** [comment]
I took your code and changed it a little an created that PR. It now also works on windows

**Comment by gedw99** [comment]
I think this can be closed . It’s working for me and is now in the hover tip.

Reopen if needed ...
