### ISSUE TITLE
Hover: Is it possible to add docker build dependencies without forking Hover?

### ISSUE THREAD

**Issue by JanezStupar** [go-flutter-desktop/go-flutter#524]
The project I am working for requires additional build dependencies for a plugin. What I have gathered so far, to install say `GTK-2` into docker image I would have to fork the Hover project to edit the dockerfile to add the required dependency.

## Describe the feature you'd like

Having an ability to specify a local dockerfile or some other way to configure build dependencies.

**Comment by jld3103** [comment]
Currently there is no other way than downloading the hover source, changing the Dockerfile and then building the docker image. In previous versions the Dockerfile was added to your project so you could edit it, but that brought some problems.

**Comment by jld3103** [comment]
How are you using hover? If you use it in a CI/CD you can use the hover docker image as base and install everything on there

**Comment by JanezStupar** [comment]
@jld3103 I am currently using it manually via my development machine, but I am going to be using it as a part of my CI setup once I get that far.

**Comment by jld3103** [comment]
Can this be closed? There is nothing to do about it other than what I already said

**Comment by jld3103** [comment]
I'll just close this, because there was no answer in over a month, but please reopen if needed.

**Comment by JanezStupar** [comment]
@jld3103 yes the issue can be closed. I got the information I needed and I have no further requests or suggestions. Sorry for not responding sooner.
