### ISSUE TITLE
Cross-compilation not working using docker

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [go-flutter-desktop/go-flutter#526]
## Hover doctor

```
$ hover doctor
hover: Hover version v0.44.0 running on darwin
hover: Sharing flutter version
Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (6 days ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)
hover: Flutter engine commit: https://github.com/flutter/engine/commit/1d12d82d9cb54876f58044aa52198d53ec841c3d
hover: Finding out the C compiler version
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
hover: Sharing the content of go.mod
module apptest/go

go 1.15

require (
        github.com/JanezStupar/flutter_systray/go v0.3.1
        github.com/go-flutter-desktop/go-flutter v0.42.0
        github.com/pkg/errors v0.9.1
)
hover: Sharing the content of hover.yaml
application-name: ""
executable-name: ""
package-name: ""
license: ""
target: lib/main.dart
branch: ""
cache-path: ""
opengl: ""
engine-version: ""
hover: Sharing the content of go/cmd
go/cmd/main.go  go/cmd/options.go
```

## Error output

I could be wrong but I think that hover supports cross-compilation using docker?

```log
$ hover build windows-msi --docker
hover: AOT builds currently only work on their host OS
```

**Comment by jld3103** [comment]
We recently switched to AOT builds which are currently only possible to build on the host OS. It is possible using wine/darling, but not yet. You need to add `--debug` to get it working like previously. Then you get the same as before

**Comment by JanezStupar** [comment]
@jld3103 doesn't `--debug` also add the terminal window with outputs?

**Comment by jld3103** [comment]
I'm not using windows, but I remember that there was something like that.

**Comment by jld3103** [comment]
Ok just looked at the code. This will be a small change

**Comment by jld3103** [comment]
I will also add a message that explains that users should use jit-release for cross-compilation builds.

**Comment by JanezStupar** [comment]
I find the terms acceptable! 

I love the docker build feature. And the performance is good enough. Of course the AOT with docker builds will be very dank when it lands, but you have just alleviated my worst fears ATM.

So, cheers!
