### ISSUE TITLE
Enlarged and blurry texts on Release and Release-Debug builds

### ISSUE THREAD

**Issue by edTheGuy00** [go-flutter-desktop/go-flutter#528]
I'm not sure if this is an issue with Flutter itself or Hover, The only issues I found are related to the web and Chrome [32274](https://github.com/flutter/flutter/issues/32274), [58159](https://github.com/flutter/flutter/issues/58159). So far it appears to be only on macOS, but I will double check on Windows

This is how my text looks like when running just `hover run`

<img width="435" alt="Screen Shot 2563-10-26 at 10 04 03" src="https://user-images.githubusercontent.com/16095735/97130805-035d7100-1775-11eb-8bbe-29148307acbe.png">

But this is how it comes out with  `hover build darwin-dmg` or `hover build darwin-dmg --debug`

<img width="438" alt="Screen Shot 2563-10-26 at 10 03 29" src="https://user-images.githubusercontent.com/16095735/97130787-f2acfb00-1774-11eb-8244-a0e07f8a2df6.png">

## Hover doctor

```
hover: Hover version v0.44.0 running on darwin
hover: Sharing flutter version
Flutter 1.22.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f30b7f4db9 (2 weeks ago) • 2020-10-08 10:06:30 -0700
Engine • revision 75bef9f6c8
Tools • Dart 2.10.1
hover: Flutter engine commit: https://github.com/flutter/engine/commit/75bef9f6c8ac2ed4e1e04cdfcd88b177d9f1850d
hover: Finding out the C compiler version
Apple clang version 12.0.0 (clang-1200.0.32.21)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by pchampio** [comment]
I have no idea of where it could come from.
Maybe manually set the `flutter.ForcePixelRatio(2.0)` option ?
https://github.com/go-flutter-desktop/go-flutter/wiki/Options

**Comment by edTheGuy00** [comment]
@pchampio Whatever value I set, the Release build is still noticeable larger and pixelated compared the Debug version. Might it be related with this PR? https://github.com/go-flutter-desktop/go-flutter/pull/458

**Comment by pchampio** [comment]
@edTheGuy00 not its not related, `ForcePixelRatio` overwrite the logic in #458
> the Release build is still noticeable larger and pixelated compared the Debug version.

Wait, this is not the same as 
> But this is how (larger and pixelated) it comes out with hover build darwin-dmg or hover build darwin-dmg --debug
Screen Shot 2563-10-26 at 10 03 29

Do you have the issue with: `hover build darwin-dmg --debug` ??

**Comment by edTheGuy00** [comment]
@pchampio both `hover build darwin-dmg` and `hover build darwin-dmg --debug` have the same result.

The other thing I noticed is that even the Application Name text on the Title Bar comes out pixelated

`hover run`
<img width="66" alt="Screen Shot 2563-10-29 at 17 38 59" src="https://user-images.githubusercontent.com/16095735/97558545-d6c48600-1a0e-11eb-8dfd-f4cb8f706447.png">

 `hover build darwin-dmg` and `hover build darwin-dmg --debug` 
<img width="66" alt="Screen Shot 2563-10-29 at 17 41 21" src="https://user-images.githubusercontent.com/16095735/97558583-e643cf00-1a0e-11eb-8494-723eeaeb1667.png">

**Comment by pchampio** [comment]
Using `hover build darwin  --debug` (No dmg packing!) can you and execute the program using `./go/build/outputs/darwin/{your_app}` and check if you have the same result ?

**Comment by edTheGuy00** [comment]
> Using `hover build darwin --debug` (No dmg packing!) can you and execute the program using `./go/build/outputs/darwin/{your_app}` and check if you have the same result ?

Yea, this works, it looks normal (not enlarged and pixelated)

**Comment by pchampio** [comment]
Then the issue comes from the dmg packaging.
@jld3103 do you have any idea ?

**Comment by jld3103** [comment]
Could this be the same? https://github.com/IJHack/QtPass/issues/355#issuecomment-374162323

**Comment by jld3103** [comment]
To try if it fixes it put
```
        <key>NSPrincipalClass</key>
        <string>NSApplication</string>
```
into the `Info.plist` dict.

**Comment by edTheGuy00** [comment]
@pchampio @jld3103  Ok, adding

```
        <key>NSPrincipalClass</key>
        <string>NSApplication</string>
```

Fixes the issue.

**Comment by jld3103** [comment]
Great. I'll add it to the standard template
