### ISSUE TITLE
libapp.so Not added into Windows release installation.

### ISSUE THREAD

**Issue by edTheGuy00** [go-flutter-desktop/go-flutter#533]
When Building a windows MSI file with `hover build windows-msi` The installed application will not run. After digging around, I found that  `libapp.so`  is missing from `C:\Program Files (x86)\MY_APP`. 

If I run  `hover build windows` and manually copy `libapp.so` file from `windows-release` directory into `C:\Program Files (x86)\MY_APP\libapp.so` then everything run fine.

**Comment by edTheGuy00** [comment]
Ok I figured it out.

I added 

```
<Component Id="libapp.so" Guid="*">
         <File Id="libapp.so" Source="build{{.pathSeparator}}libapp.so" KeyPath="yes"/>
</Component>
```

and 

```
<ComponentRef Id="libapp.so"/>
```

into `packaging/windows-msi/{{.packageName}}.wxs.tmpl` file. Should this be added to the [standard template](https://github.com/go-flutter-desktop/hover/blob/master/assets/packaging/windows-msi/app.wxs.tmpl)?

**Comment by jld3103** [comment]
Yes that should be added

**Comment by jld3103** [comment]
The code can be improved as a whole so that every file gets automatically included. Currently some files are manually included like `libapp.so` should be.

**Comment by pchampio** [comment]
> The code can be improved as a whole so that every file gets automatically included.

Yea, we have to take into account that some component are dependent on the compile mode.
`libapp.so` is only present when complied for release.
Wild-card inclusion is a solution.

**Comment by jld3103** [comment]
I think wildcard inclusion is not possible, but the current strategy is to generate all entries on building.
