### ISSUE TITLE
How can I intercept key action ?

### ISSUE THREAD

**Issue by kokocooler2020** [go-flutter-desktop/go-flutter#540]
I need to intercept the esc key, but I don’t know how to intercept it. 

If I can’t intercept it, I will go back to the previous page when I click esc. This is not the behavior I need.

Any body can help please?

**Comment by pchampio** [comment]
On esc key we call the method `popRoute` on the system channel `flutter/navigation`:
https://github.com/go-flutter-desktop/go-flutter/blob/67ff5ca6b2287f2e0ad554b64d24b7795b1939d1/text-input.go#L159-L165

**Comment by pchampio** [comment]
Maybe you can help us an propose a PR to add a go-flutter option

List of options: https://github.com/go-flutter-desktop/go-flutter/wiki/Options
Similar to: https://github.com/go-flutter-desktop/go-flutter/pull/144/files
Work on go-flutter source code: https://github.com/go-flutter-desktop/go-flutter/wiki/Setting-up-hover-to-use-a-home-made-version-of-'go-flutter'

**Comment by jslater89** [comment]
I think I'm going to take a crack at this—useful for a project I'm working on that'll want an escape menu.

**Comment by pchampio** [comment]
Closed in #632
