### ISSUE TITLE
library not loaded /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib on Mac 10.15.2

### ISSUE THREAD

**Issue by jlcool** [go-flutter-desktop/go-flutter#541]
library not loaded /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib on Mac 10.15.2

**Comment by pchampio** [comment]
Can you please provide more information ? (as requested by the issue template)

**Comment by pchampio** [comment]
Similar to: https://github.com/kelaberetiv/TagUI/issues/86
https://stackoverflow.com/questions/63307913/openssl1-1-not-used-dyld-library-not-loaded-usr-local-opt-openssl-lib-libss#63314761
I've google your issue.

**Comment by pchampio** [comment]
https://stackoverflow.com/questions/59006602/dyld-library-not-loaded-usr-local-opt-openssl-lib-libssl-1-0-0-dylib?page=1&tab=votes#tab-top

**Comment by pchampio** [comment]
https://gist.github.com/aklap/e885721ef15c8668ed0a1dd64d2ea1a7

**Comment by jlcool** [comment]
I'm sorry, this problem occurs on the user side. Do I have to ask the user to execute the command
