### ISSUE TITLE
After packaged into windows desktop application, variant characters appear. How to solve this problem?

### ISSUE THREAD

**Issue by ablockhead** [go-flutter-desktop/go-flutter#544]
## Hover doctor

```
$ hover doctor
hover: Running on linux
hover: Docker installed: true
hover: Sharing flutter version
[...]
```

## Error output

Using `hover build [...] --XXX` to build my application, I get the following
error:

```log
hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
hover: Compiling 'go-flutter' and plugins
[...]
```

**Comment by jld3103** [comment]
Could you post the full log of `hover doctor`? Also some screenshots and the logs when running the app standalone and packaged woule help.

**Comment by ablockhead** [comment]
![62ae22d98dcc3c48f1f79c594287bba](https://user-images.githubusercontent.com/37892636/101624795-72590580-3a55-11eb-857e-d8032a2222e4.png)
![aa15b5d4ce5de2d5153231fd72b89ef](https://user-images.githubusercontent.com/37892636/101624800-7553f600-3a55-11eb-92d6-f27b8b5dc332.png)
![65521f33897d4dca84a9596cf44010e](https://user-images.githubusercontent.com/37892636/101624813-7a18aa00-3a55-11eb-89e2-f845a215df90.png)

**Comment by ablockhead** [comment]
> 您可以发布完整的日志`hover doctor`吗？此外，在独立运行该应用程序和打包的应用程序时，还提供了一些屏幕截图和日志。
The screenshots of hover doctor and hover run have been sent. Please have a look

**Comment by ablockhead** [comment]
![4a4cf194e53b1833312be86e114e903](https://user-images.githubusercontent.com/37892636/101625758-dcbe7580-3a56-11eb-8a2b-07df89a21657.png)

**Comment by ablockhead** [comment]
![Uploading 4a4cf194e53b1833312be86e114e903.png…]()

**Comment by ablockhead** [comment]
![Uploading 11.png…]()

**Comment by ablockhead** [comment]
![11](https://user-images.githubusercontent.com/37892636/101625832-fc559e00-3a56-11eb-8c9b-b6eb49f6b3ba.png)

**Comment by ablockhead** [comment]
![11](https://user-images.githubusercontent.com/37892636/101626022-45a5ed80-3a57-11eb-9f11-e23bf70f2aa0.png)
