### ISSUE TITLE
App 'order' exited with error: exit status 3221225477

### ISSUE THREAD

**Issue by ablockhead** [go-flutter-desktop/go-flutter#545]
Run hover run under windows and directly report an error to exit. The following is the procedure of hover run

hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
Running "flutter pub get" in order_app...                          442ms
Font subsetting is not supported in debug mode. The --tree-shake-icons flag will be
ignored.
hover: Compiling 'go-flutter' and plugins
hover: Successfully compiled executable binary for windows
hover: Build finished, starting app...
hover: Running order in debug_unopt mode
hover: App 'order' exited with error: exit status 3221225477

**Comment by pchampio** [comment]
Are you using a virtual machine ?

**Comment by pchampio** [comment]
Without additional information, we are unfortunately not sure how to resolve
this issue. We are therefore reluctantly going to close this bug for now. Please
don't hesitate to comment on the bug if you have any more information for us; we
will reopen it right away!
Thanks for your contribution.

Duplicate btw
