### ISSUE TITLE
[Help request] Where is hover installed?

### ISSUE THREAD

**Issue by matheus208** [go-flutter-desktop/go-flutter#557]
## Is your feature request related to a problem? 

No.

[Keep in mind I'm new to Dart/Flutter AND Go, I have never installed any go packages before.]

This is what is written on the instructions:

>`GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover`
> Make sure the hover binary is on your PATH

Well, after installing it, it is not on my PATH, and I don't know where `go` installed it so I can't do it myself. 

I'm on Mac

## Describe the feature you'd like

An extra step on the README.md instructions explaining what to do in case `hover` is not added to the PATH environment variable (I can open the PR myself if someone helps me :).

**Comment by jld3103** [comment]
I guess you are on Windows?

**Comment by matheus208** [comment]
Mac!

**Comment by jld3103** [comment]
On linux and mac there is `~/go/bin` which should translate to the same directory location on windows.

**Comment by matheus208** [comment]
Thank you! I was looking for the documentation on `go get` and didn't see the defaults were`$GOPATH/bin` or `$HOME/go/bin`, everything is sorted now.

Do you think it's worth me opening a PR linking to that documentation?

**Comment by jld3103** [comment]
Yes totally! Please also add some other things that you find hard or need information on
