### ISSUE TITLE
How to build window app.

### ISSUE THREAD

**Issue by BearnLee** [go-flutter-desktop/go-flutter#560]
Please help me.
how to build window app? The Flutter channel is beta and 'go' version is the latest.
![222](https://user-images.githubusercontent.com/15085401/105006176-3f049000-5a71-11eb-9e7a-02f44bf21439.png)

**Comment by jld3103** [comment]
You need to install hover with `GO111MODULE=on`. See https://github.com/go-flutter-desktop/hover#install on how to do it.
