### ISSUE TITLE
Secure storage plugin for storing user data in the TPM chip on all desktops.

### ISSUE THREAD

**Issue by joe-getcouragenow** [go-flutter-desktop/go-flutter#565]
I was doing some research on this and think i have a decent solution, but not sure i have the time to work it up, so am shamelessly putting it here as others might have time.

This all started because we needed a good way for users to login, and to store their login password, so when they reopen the app, it will pull the password out from the keyring. SO it does what Chrome does and stores you login details to a web site. 

The Flutter version is this: https://pub.dev/packages/flutter_secure_storage
- I wonder if Google has made a proper federated plugin for this functionality ? 

The golang version is this: github.com/zalando/go-keyring
- well supported and in production i am guessing.
A nice test harness CLI is here that exercise it: github.com/martinohmann/keyring
This works on all desktops that i tested and its pretty clean and simple.

**Comment by pchampio** [comment]
Thank for sharing!
I’ve tagged the issue correctly for better archiving.
