### ISSUE TITLE
Customization the file name of libapp.so

### ISSUE THREAD

**Issue by leedstyh** [go-flutter-desktop/go-flutter#571]
## Is your feature request related to a problem?

I need customize the name of `libapp.so` in `hover.yaml`

## Describe the feature you'd like
Put some sub app into one directory and share the same flutter engine. These sub apps can be opened by my main app.

**Comment by jld3103** [comment]
Would your use case be completely working if you were able to only set the name?

**Comment by leedstyh** [comment]
Hi @jld3103 , thanks for your reply.

I wanna use this as a temporary solution for multi window, since https://github.com/go-flutter-desktop/go-flutter/issues/123 is not fixed.

What I do right now is modifying these two lines: https://github.com/go-flutter-desktop/hover/blob/master/cmd/build.go#L499 and https://github.com/go-flutter-desktop/go-flutter/blob/master/option.go#L71 . Change `libapp.so` to say `libapp1.so` for app1 and build my customized hover say hover1. 

This way I can build some apps say app1, app2... I put them in the same directory. In the main app I use cmd like `Process.run("app1.exe", [])` to open sub apps.

I checked the built files, and  only `app1.exe` and `libapp.so` make the difference.

And this works fine now for me, but since I have 10 sub apps to build, manually maintaining modifications is a nightmare. 

So I think the feature naming `libapp.so` in the hover.yaml can save my life.

**Comment by pchampio** [comment]
It feels like what you are doing is a workaround. And the enhancement you propose is serving only purposes for this workaround.
I would encourage you to do the following:
 - Maintain your own version of go-flutter and hover that solves multi window (not mainstream manner)
 - Change this line https://github.com/go-flutter-desktop/go-flutter/blob/master/option.go#L71 to something that uses `venv`, example here: https://github.com/go-flutter-desktop/go-flutter/blob/47c327c03984e00b5bd571fcdb68faff958d451b/application.go#L294-L300   
 - Change this line https://github.com/go-flutter-desktop/hover/blob/master/cmd/build.go#L499 to something similar.
 This way, you could use: `env libapp=libappmain.so hover build XXX` and in dart: `Process.run("app1.exe", [])` with the `environment` optional argument.

**Comment by leedstyh** [comment]
Thanks env works nice too
