### ISSUE TITLE
Pass cmd line args to dart

### ISSUE THREAD

**Issue by leedstyh** [go-flutter-desktop/go-flutter#576]
Any way to pass cmd line args to dart?

If I `hover build windows` and get `app.exe`, then run it as `app.exe hello`. I get `hello` in dart code like this:

```
void main(List<String> args) {
    print(args); // print ["hello"]
}
```

**Comment by pchampio** [comment]
I'm not planing to add this feature.
Please use venv

**Comment by leedstyh** [comment]
Ok, thanks @pchampio and sorry to bother!
