### ISSUE TITLE
Can not show emoji when using any Chinese font

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#580]
![image](https://user-images.githubusercontent.com/21303438/111856440-a5206d00-8965-11eb-84c8-f95230a6f45c.png)

this issue exist for a long time but there is noone really investigate it. What I want is showing Chinese and emoji at the same time. Currently not able to do this.

Anyone would simple have a test and give a screenshot showing Chinese and emoji at the same time?

**Only on LINUX, windows is OK!!!**

**Comment by jinfagang** [comment]
But linux terminal can show emoji:

![image](https://user-images.githubusercontent.com/21303438/111856472-ef095300-8965-11eb-964e-c5b975b3fa80.png)

So I think it's not about my system font doesn't have emoji codingset.

**Comment by jld3103** [comment]
From what I understood is that there already are issues open about this topic and the solution seems to be to merge a cjk/chinese and emoji font.

**Comment by pchampio** [comment]
duplicated: https://github.com/go-flutter-desktop/go-flutter/issues/481

**Comment by jinfagang** [comment]
@pchampio @jld3103  Please guide to solve it, I don't know what does merge cjk/chinese mean, is there any exist project can do this? I can reference

**Comment by jinfagang** [comment]
@pchampio  I narrowed down the problem to: **only happened on Ubuntu when showing Chinese and emoji at the same time**

**Comment by jinfagang** [comment]
Windows is OK, English and emoji is OK>

**Comment by jld3103** [comment]
https://superuser.com/questions/490922/merging-two-fonts

**Comment by jinfagang** [comment]
@jld3103 Can u give me a emoji combine Chinese font file?

**Comment by jld3103** [comment]
I can't help you any further. I sent you how to do it

**Comment by jinfagang** [comment]
@jld3103  I just followed this tutorial, this generate font can not using at all (emoji still not shown).

I am here for a solution, not for your therotically infer, pls make it practical by just practice.
