### ISSUE TITLE
start to packaging linux APP.... hover: linux-appimage is already initialized for packaging. hover: Using engine from cache hover: To package linux-appimage these tools are required: appimagetool hover: Install appimagetool from your package manager or from https://github.com/AppImage/AppImageKit#appimagetool-usage hover: To still package linux-appimage without the required tools installed you need to run hover with the `--docker` flag.

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#581]
start to packaging linux APP....
hover: linux-appimage is already initialized for packaging.
hover: Using engine from cache
hover: To package linux-appimage these tools are required: appimagetool
hover: Install appimagetool from your package manager or from https://github.com/AppImage/AppImageKit#appimagetool-usage
hover: To still package linux-appimage without the required tools installed you need to run hover with the `--docker` flag.

I have alreayd appimagetool installed

**Comment by jld3103** [comment]
Then it's not in your path. Please check that.
