### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by leielyq** [go-flutter-desktop/go-flutter#582]
PS D:\work\examination> hover run
hover: Downloading engine for platform windows-debug_unopt at version 92ae191c17a53144bf4d62f3863c110be08e3fd3...
Download completed in 5.62s
Download completed in 2.31s

windows-debug_unopt at version 92ae191c17a53144bf4d62f3863c110be08e3fd3...

How to update?

**Comment by pchampio** [comment]
`flutter channel beta`
`flutter upgrade`
`hover bumpversion`

**Comment by leielyq** [comment]
@pchampio 


 hover bumpversion
hover: Using engine from cache
go get github.com/go-flutter-desktop/go-flutter@latest: git ls-remote -q https://github.com/go-flutter-desktop/go-flutter in D:\SDK\Go\Path\pkg\mod\cache\vcs\36c8c1c2d8d23519cd4615ae43323bfee7cfa7720be81cabbab32c7f3855b88e: exit status 128:
        fatal: unable to access 'https://github.com/go-flutter-desktop/go-flutter/': SOCKS5 read timeout
hover: Updating go-flutter to @latest version failed: exit status 1

**Comment by leielyq** [comment]
sad

**Comment by leielyq** [comment]
hover bumpversion
hover: Using engine from cache
go get: github.com/go-flutter-desktop/go-flutter@v0.43.0 requires
        github.com/Xuanwo/go-locale@v1.0.0 requires
        golang.org/x/sys@v0.0.0-20200802091954-4b90ce9b60b3: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in D:\SDK\Go\Path\pkg\mod\cache\vcs\da0444fc0003f84a590bd6521553c0531086778bca13ec63ace9e0dd258f4b51: exit status 128:
        fatal: early EOF
        fatal: The remote end hung up unexpectedly
        fatal: index-pack failed
        error: RPC failed; curl 18 transfer closed with outstanding read data remaining
hover: Updating go-flutter to @latest version failed: exit status 1

**Comment by pchampio** [comment]
`go env -w GOPROXY=https://goproxy.cn,direct`

**Comment by leielyq** [comment]
thanks
