### ISSUE TITLE
Upload the go-flutter to Pub.dev

### ISSUE THREAD

**Issue by ChristianKleineidam** [go-flutter-desktop/go-flutter#588]
When I search for go-flutter on Pub.dev I currently don't find this package. This makes it harder to discover that this package exist. More importantly, it means that other packages on Pub.dev can't use it as a dependency.

**Comment by jld3103** [comment]
go-flutter doesn't contain any dart code so what would you upload?

**Comment by ChristianKleineidam** [comment]
I understood go-flutter to provide an API to call go code from dart? Is that not a feature that it has?

**Comment by jld3103** [comment]
No go-flutter is a custom flutter embedder for running a flutter app on desktop. To call go code you use the MethodChannel API from flutter: https://flutter.dev/docs/development/platform-integration/platform-channels. go-flutter itself is not an API.

**Comment by pchampio** [comment]
Hello @ChristianKleineidam you will find more information in our readme and here: https://github.com/go-flutter-desktop/go-flutter/issues/191
