### ISSUE TITLE
should be an option to programmly close Application on  golang side.

### ISSUE THREAD

**Issue by HaoweiCh** [go-flutter-desktop/go-flutter#589]
## Hover doctor

```
$ hover doctor
hover: Running on linux
hover: Docker installed: true
hover: Sharing flutter version
[...]
```

## Error output

Using `hover build [...] --XXX` to build my application, I get the following
error:

```log
hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
hover: Compiling 'go-flutter' and plugins
[...]
```

there is no option to programmly close Application on  golang side.

**Comment by pchampio** [comment]
Check this example out: https://github.com/go-flutter-desktop/examples/tree/master/draggable_borderless
