### ISSUE TITLE
Please upgrade go-sqflit plugin?

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#591]
```
go-flutter: handler for method 'batch' on channel 'com.tekartik.sqflite' returned an error: invalid args
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, invalid args, null, null)
```

The basic batch can not work.....

**Comment by jld3103** [comment]
sqflite is not an official flutter plugin and we don't maintain it. Please file a bug report at https://github.com/boltomli/go-flutter-plugin-sqlite or even better fix it yourself and create a PR on that repo.

**Comment by jinfagang** [comment]
@renovate-bot @StefanLobbenmeier @jld3103  I noticed that original plugin maintainer was go-flutter-desktop as well.

I also posted an issue there, can u guys help upgrade this plugin togather? this behavior make desktop unable to run some SQL operations. Please pay some attention to our user demands.

**Comment by StefanLobbenmeier** [comment]
Why did you @ me? I haven’t really done any development here.

But I agree with @jld3103 - please don’t raise plug-in specific issues here. Raise them in the plug-in repository instead. If the maintainer of that repository does not answer anymore (the last commits I could see are from 2019) I would suggest you to fork the repo and fix it yourself.

**Comment by jld3103** [comment]
> Why did you @ me? I haven’t really done any development here.

Same not sure why

> But I agree with @jld3103 - please don’t raise plug-in specific issues here. Raise them in the plug-in repository instead. If the maintainer of that repository does not answer anymore (the last commits I could see are from 2019) I would suggest you to fork the repo and fix it yourself.

Exactly

**Comment by jinfagang** [comment]
@jld3103 @StefanLobbenmeier Please response to my question..

Sorry just github indicates my with your username

**Comment by jinfagang** [comment]
@jld3103 I belive this guys is belongs to your team?

![image](https://user-images.githubusercontent.com/21303438/117115907-4d787c80-adc0-11eb-80af-fe0a889b4a75.png)

**Comment by jinfagang** [comment]
@jld3103 I just want this plugin to be useful to community, please focus on my question rather than focus on whether or where should I post the issue.....

**Comment by jld3103** [comment]
I don't have any knowledge about that plugin or anything that has to do with it. I can give you no instructions or advice or any help in any form. I'd need to go through the same process as you, so you are better of fixing it yourself. I currently have no intention to work on this, so please don't bother me anymore.

**Comment by davidmartos96** [comment]
@jinfagang As an everyday user of Sqlite on Flutter desktop I'd recommend you to switch and use `sqflite_common_ffi` instead of the platform channel implementation in Go. It is maintained, up to date, and it has the same Sqflite API, and it can be used in Flutter official desktop embedding if some day you need to switch that as well.
The package is maintained by the author of sqflite.
A similar option is to use moor + FFI, although that doesn't have the same API from sqflite, so you'd need to change some things. 

https://pub.dev/packages/sqflite_common_ffi

**Comment by pchampio** [comment]
@jinfagang too much agressivity in your posts. (and this isn't the first time, some of your other issues are also writing in the same manner)
Please read the following articles and be more cool/respectful in your comments:
 - https://www.techrepublic.com/article/why-open-source-developers-are-burning-out-no-respect/
 - http://antirez.com/news/129
 - And just google..
 
If this attitude on your part continues, I will keep ignoring your messages.
I feel personally attacked with every message you send.

**Comment by jinfagang** [comment]
@pchampio Sorry. I just feel a lot of ignorance from this project as well. If I bring some mood to yours then I apologies. As an user of go-flutter, I sincery hope it becomes better. thank you for your guys efforts.
