### ISSUE TITLE
Flutter desktop application not working on 32 bit system

### ISSUE THREAD

**Issue by matrixhacker0001** [go-flutter-desktop/go-flutter#603]
We created a desktop application on flutter desktop. But we are not able to run it on 32 bit OS. We also gone through some posts which says it not supports 32 bit. Is it currently supportable or any other option to run it on 32 bit OS.
Please help.

**Comment by jld3103** [comment]
I think technically you can run the debug apps on 32 bit. You just need to change the arch that the go binary is built for in hover. For release apps we would need 32 bit engines.
See https://github.com/go-flutter-desktop/hover/blob/master/cmd/build.go#L737

**Comment by devfemibadmus** [comment]
@provokateurin same problem bro i search through and read doc but still not gonna work on  32 bit system

**Comment by devfemibadmus** [comment]
Okay found out flutter doesnt support 32bit closed() ref: https://github.com/flutter/flutter/issues/37777
