### ISSUE TITLE
Hover fails durring Windows build with the --docker flag due to missing tag

### ISSUE THREAD

**Issue by danielcasler** [go-flutter-desktop/go-flutter#616]
Installed the latest. Everything built nicely for Ubuntu. Tried to do a Windows build with the --docker flag.

The build process is failing as follows:

`goflutter/hover:v0.46.6 hover-safe.sh build windows --skip-engine-download --version-number 1.0.0+1
docker container: Unable to find image 'goflutter/hover:v0.46.6' locally
docker container: docker: Error response from daemon: manifest for goflutter/hover:v0.46.6 not found: manifest unknown: manifest unknown.
docker container: See 'docker run --help'.`

There are no tags for 46.6, only 46.5 and latest. Not sure if this can be changed to use latest?

**Comment by jld3103** [comment]
For some reason the tag hasn't been built. I also can't see the build on docker hub.

**Comment by jld3103** [comment]
Ohh so docker hub disabled automatic builds for the tier we currently have. @GeertJohan @pchampio we should create a github action to build and push the image.

**Comment by zeshuaro** [comment]
Any updates on this? I have the same issue and had to rollback to a previous version of hover in order to run this.

**Comment by pchampio** [comment]
@jld3103 I'm sorry, I don't have time to work on this at the moment.
If you don't have the time @jld3103, you can still locally compile hover with:
```
git clone https://github.com/go-flutter-desktop/hover
cd hover
./install-with-docker-image.sh
```

**Comment by jld3103** [comment]
I don't really have time either. The local compile should just work, but people are free to contribute a github action to solve this problem!

**Comment by ShiinaOrez** [comment]
v0.47.0 also missed on docker hub. And install `install-with-docker-image.sh` use `apt-get`, it dose not works on macOS. So who can build v0.47.0 image to docker hub?  T o T

**Comment by ShiinaOrez** [comment]
Solved.
1. `v0.47.0` not exist, but `latest` exist.
2. my local hover version is 0.47.0, so I clone newest source code and `go build`, then copy `hover` to my go-flutter project dir and run `./hover build xxx --docker`, it will use `latest` image but not `v0.47.0`, done.

**Comment by jld3103** [comment]
`install-with-docker-image.sh` is just a script for building a docker image. if you got a working docker, then it will just build.
