### ISSUE TITLE
GO Fatal whilst running

### ISSUE THREAD

**Issue by Syleron** [go-flutter-desktop/go-flutter#62]
Windows 10
###### `$ flutter --version`

```
Flutter 1.0.0 â¢ channel stable â¢ https://github.com/flutter/flutter.git
Framework â¢ revision 5391447fae (7 weeks ago) â¢ 2018-11-29 19:41:26 -0800
Engine â¢ revision 7375a0f414
Tools â¢ Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

## Golang errors (Optional)

Get this error whilst the program is running

```
Check failed: loop != nullptr. MessageLoop::EnsureInitializedForCurrentThread was not called on this thread prior to message loop use.
exit status 3221226505
```

###### Download [Link](https://github.com/Drakirus/go-flutter-desktop-embedder/releases)
 - Yes

## Steps to Reproduce

There is no clear way for me to replicate without providing the executable to my project.

**Comment by Drakirus** [comment]
Sorry for the late reply.
Can you share the source that replecate the issue?

**Comment by Syleron** [comment]
@Drakirus I'd rather not share my entire personal project. I'm using the simpleDemo main.go and nothing more. Would you be able to join in on a discord call?

**Comment by Drakirus** [comment]
This goes against my working methods, no for discord, sorry.
Did you implement a personal plugin?

**Comment by Syleron** [comment]
@Drakirus sure, np. I believe it may be the used of flutter Redux, however, I'm unsure to be exact.

**Comment by Drakirus** [comment]
Try to delete those lines: [main.go, `ownPlugin`](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/91996e7a2f605a297aa3e7b4c1bf9020e880f420/example/simpleDemo/main.go#L68-L95)

**Comment by Syleron** [comment]
```
package main

import (
	"image"
	_ "image/png"
	"log"
	"os"
	"path"
	"runtime"

	"github.com/Drakirus/go-flutter-desktop-embedder"
	"github.com/go-gl/glfw/v3.2/glfw"
)

func main() {
	var err error

	dir, _ := os.Getwd()

	options := []gutter.Option{
		gutter.ProjectAssetPath(dir + "/flutter_project/project/build/flutter_assets"),
		gutter.ApplicationICUDataPath(dir + "/icudtl.dat"),
		gutter.ApplicationWindowDimension(1224, 768),
		gutter.OptionWindowInitializer(setIcon),
		gutter.OptionPixelRatio(1.2),
		gutter.OptionVMArguments([]string{"--dart-non-checked-mode", "--observatory-port=50300"}),
	}

	if err = gutter.Run(options...); err != nil {
		log.Fatalln(err)
	}

}

func setIcon(window *glfw.Window) error {
	_, currentFilePath, _, _ := runtime.Caller(0)
	dir := path.Dir(currentFilePath)
	imgFile, err := os.Open(dir + "/assets/waves.png")
	if err != nil {
		return err
	}
	img, _, err := image.Decode(imgFile)
	if err != nil {
		return err
	}
	window.SetIcon([]image.Image{img})
	return nil
}
```

Is currently my main.go code

**Comment by Drakirus** [comment]
If you are using some flutter plugins, make sure they are 100% Dart. If they use some platform bindings, those are not implemented.

**Comment by GeertJohan** [comment]
@Syleron Is it possible to distil a minimal version of your code that still produces this error? Then I may be able to debug the problem.

**Comment by GeertJohan** [comment]
Without more information it's hard for us to reproduce the described behaviour. Also, a lot has changed in the way engine lookups work, and some bugs that may have caused this error were fixed. Please open a new issue if the problem still occurs with the latest version of go-flutter.
