### ISSUE TITLE
no handler found for channel bdmap_location_flutter_plugin

### ISSUE THREAD

**Issue by BearnLee-Li** [go-flutter-desktop/go-flutter#620]
Hey,dear!
I build my flutter project to windows app,there are some problems - no handler found for channel bdmap_location_flutter_plugin.
whith this problem,I can't use all map features.
can you help me to fix this?
this is the plugin site:
https://lbsyun.baidu.com/index.php?title=flutter/loc

Thx!

**Comment by jld3103** [comment]
This means the plugin is not implemented in go. Please look at the wiki on how to implement such a plugin.

**Comment by pchampio** [comment]
Some information: https://github.com/go-flutter-desktop/go-flutter/wiki/Plugin-info
