### ISSUE TITLE
'Ticker' for engine builds

### ISSUE THREAD

**Issue by jslater89** [go-flutter-desktop/go-flutter#639]
The engine builds CI will auto-disable 60 days after the last activity, so we should set up something to pop an empty commit in every week or so to keep it running.

I can probably set that up on one of my webservers, but I'm open to other ideas if something else is preferable.

**Comment by jld3103** [comment]
Would it be possible to add a pipeline that pushes a commit to the repo once a month? So the pipelines keep themselves alive.

**Comment by jslater89** [comment]
Seems to work. I'll leave myself a note to check in late February, just in case Github filters out empty commits coming from its runners as valid repository activity.
