### ISSUE TITLE
go-flutter: WARNING error creating the resource window: VersionUnavailable: NSGL: Failed to create OpenGL context

### ISSUE THREAD

**Issue by MisterZhouZhou** [go-flutter-desktop/go-flutter#646]
go version: 1.18

flutter: 2.18

macos: 0.15.7

**Comment by pchampio** [comment]
Looking at the other similar issues: https://github.com/go-flutter-desktop/go-flutter/search?q=VersionUnavailable&type=issues
are you able to fix this issue?

**Comment by pchampio** [comment]
should be fixed in `v0.50.0`
