### ISSUE TITLE
How to add an organization's name

### ISSUE THREAD

**Issue by qinjinze** [go-flutter-desktop/go-flutter#655]
hover: Missing/Empty `organization-name` field in go/hover.yaml. Please add it or otherwise you may publish your app with a wrong organization-name. Continuing with `` as a placeholder organization-name.
hover: Compiling 'go-flutter' and plugins

hover.yaml
application-name: "officefast" # Uncomment to modify this value.
#executable-name: "officefast" # Uncomment to modify this value. Only lowercase a-z, numbers, underscores and no spaces
#package-name: "officefast" # Uncomment to modify this value. Only lowercase a-z, numbers and no underscores or spaces
license: "" # MANDATORY: Fill in your SPDX license name: https://spdx.org/licenses
target: lib/main_desktop.dart
branch: "" # Change to "@latest" to download the latest go-flutter version on every build
# cache-path: "/home/YOURUSERNAME/.cache/" #  https://github.com/go-flutter-desktop/go-flutter/issues/184
# opengl: "none" # Uncomment this line if you have trouble with your OpenGL driver (https://github.com/go-flutter-desktop/go-flutter/issues/272)
docker: false
#engine-version: "v0.0.1" # change to a engine version commit ,engine for platform windows-release

**Comment by jld3103** [comment]
It's right in the error message in the first line.
