### ISSUE TITLE
General Question: how is this different from flutter's own desktop solution

### ISSUE THREAD

**Issue by laoshaw** [go-flutter-desktop/go-flutter#684]
is the only difference using golang instead of dart? Thanks.

**Comment by pchampio** [comment]
Dart is still the language that you have to use for ui building.
This project uses golang at the embedder/engine level.
For more information, read this: https://github.com/go-flutter-desktop/go-flutter/issues/191#issuecomment-511384007
https://hover.build/blog/one-year-in/
