### ISSUE TITLE
Can I use it on the arm64 Linux platform now

### ISSUE THREAD

**Issue by kero990** [go-flutter-desktop/go-flutter#689]
I tried using go Linux on an arm64 Linux, but after reading https://github.com/go-flutter-desktop/go-flutter/issues/486 and https://github.com/go-flutter-desktop/go-flutter/issues/363, I couldn't find the necessary information, and they were all from 2020. I don't know where the latest information about arm64 Linux is.

And now, Flutter fully supports native running on arm64, and there is no difference between using it on x86. So what is the situation with go-flutter and can it support arm64 Linux?

Also, can I use cross compilation to compile go-flutter across architectures? I don't seem to have seen the system architecture selection parameters mentioned at the beginning.

Now, when I try to compile locally on arm64, an error is reported
`gcc: error: unrecognized command line option '-m64'`

Since the prompt - m64 indicates that the go-flutter is still set to x86-x64 instead of the native arm64
I don't seem to see the system architecture selection parameters mentioned at the beginning of # 363 in the `--help` section. Can I configure them to arm64

**Comment by pchampio** [comment]
https://github.com/flutter/flutter/issues/74929#issuecomment-1452709497
