### ISSUE TITLE
Allow Scrolling

### ISSUE THREAD

**Issue by TotallyGamerJet** [go-flutter-desktop/go-flutter#7]
I think it would be cool if you could scroll with a mouse instead of having to drag! That's all, great project.

**Comment by Drakirus** [comment]
The flutter engine does not support scrolling through the 
They are working on it: https://github.com/flutter/engine/pull/6228

**Comment by GeertJohan** [comment]
Enum and field in embedder.h support suggest support for scrolling.

https://github.com/flutter/engine/blob/4b01d795feec3ba8231a397a4ec2759954d8216e/shell/platform/embedder/embedder.h#L292
and
https://github.com/flutter/engine/blob/4b01d795feec3ba8231a397a4ec2759954d8216e/shell/platform/embedder/embedder.h#L307

GLFW  would be https://godoc.org/github.com/go-gl/glfw/v3.2/glfw#ScrollCallback

**Comment by GeertJohan** [comment]
Unpinned, on hold until the embedder support lands in beta channel.

**Comment by GeertJohan** [comment]
Support for scrolling has just been merged in a633350fdf577e42af608c6020e99457b4b62f48
