### ISSUE TITLE
Move repository to go-flutter-desktop organisation

### ISSUE THREAD

**Issue by Drakirus** [go-flutter-desktop/go-flutter#72]
As I'm less and less maintaining this repository due to my studies, it would be better to move it to a ~~"[@flutter-desktop](https://github.com/flutter-desktop)"~~ "[@go-flutter-desktop](https://github.com/go-flutter-desktop)" organization.

Having 1,500+ stargazer only meant one thing: The community is in the needs.
Sadly I cannot invest enough time into the project, and it's time for me to admit that this side project of mine has gained too much interest that I can't assume.

Having an organization as the owner would allow Collaborator like @GeertJohan, to contribute without have to deal with me.

As per [Github documentation](https://help.github.com/articles/about-repository-transfers/), a transfer automatically redirects links, resources, and etc as opposed to a fork which does none of those things.

I am planning to transfer the repo in the next few days. If you have anything to say, please comment!

Pierre.

**Comment by GeertJohan** [comment]
Hi all, it's great to be part of this project! Thanks @Drakirus for the trust. Lets make this even more awesome than it already is!

We want the movement to be as little hindrance for existing users as possible, but at the same time rename some packages and exported functions/types that are currently causing confusion for developers. This involves breaking changes, but it's important to us that these breaking changes may be applied in existing projects whenever it's convenient for their maintainers.

The movement plan so far, open for debate:
- Move this repo to `flutter-desktop/go-flutter`
- Fork from `flutter-desktop/go-flutter` back to `Drakirus/go-flutter-desktop-embedder`, this way the existing repo stays compatible and unchanged for existing users. It doesn't get any more updates though.
- Add a commit to `Drakirus/go-flutter-desktop-embedder` which adds a deprecation warning to the README, and a `fmt.Println("Warning: go-flutter-desktop-embedder has been moved, please read <link to more info>")` into `(*flutter.EngineOpenGL).Run(..)`. This notifies users that just `go get -u` without visiting the repo page / README.
- Add a commit to `flutter-desktop/go-flutter` with the (breaking) renames of packages. Upgrading will be simple, but necessary. An upgrade guide will be provided.

Please let us know if you have any objections or feedback on this plan. Thanks!

**Comment by stuartmorgan** [comment]
> it would be better to move it to a "[@flutter-desktop](https://github.com/flutter-desktop)" organization.

Have you considered a less generic name? With the in-progress migration of flutter-desktop-embedding's implementations to flutter/engine, there are now desktop implementations that are part of the Flutter project. Creating an organization called "flutter-desktop" that's not part of Flutter and unrelated to Flutter's desktop implementations seems potentially very confusing.

(It also seems a bit odd to not include "go" in the name unless you expect it to take over ownership of other projects. E.g., flutter-rs seems to be much the same as this project except in Rust rather than Go.)

**Comment by Drakirus** [comment]
Our plan was to move the repo to `flutter-desktop/go-flutter`.
Having a "[@flutter-desktop](https://github.com/flutter-desktop)" organization might confuse some people.
I hadn't thought about it.

@stuartmorgan is `go-flutter-desktop/flutter` a better name ?
I don't want to include "go" in the organization AND repo name.

Thanks for the feedback!

**Comment by GeertJohan** [comment]
The repo name `flutter` might be confusing as well, looks as if it is a fork of the flutter/flutter repo.

**Comment by GeertJohan** [comment]
@stuartmorgan I wasn't aware of flutter-desktop-embedding being merged into flutter/engine? I thought the engine project was embedder-agnostic? How will that work?

**Comment by stuartmorgan** [comment]
> @stuartmorgan is `go-flutter-desktop/flutter` a better name ?

I think `go-flutter-desktop` as an organization name is much less likely to cause confusion, certainly.

> I thought the engine project was embedder-agnostic?

The embedding API is embedder agnostic, not the project. The repository is where the Android and iOS Flutter shells lived already, so is definitely not implementation agnostic.

> How will that work?

The embedding API and the shell will be different targets. I don't want to hijack this thread though, so if you are interested in more details the FDE mailing list is probably a better place.

**Comment by GeertJohan** [comment]
@stuartmorgan Just read up on the mailinglist. Congratulations with the promotion of FDE into flutter/engine! And thanks for the feedback, we'll go with `go-flutter-desktop`.

**Comment by Drakirus** [comment]
Crazy stuff is happening fast! 
Thanks for the feedback and the hard work you've put into FDE, this experiment would not have existed without you.

**Comment by GeertJohan** [comment]
The move has been completed.
https://github.com/go-flutter-desktop/go-flutter/wiki/Package-has-moved-to-an-organization
