### ISSUE TITLE
Flutter (Channel beta), v1.2.1 is released!

### ISSUE THREAD

**Issue by Drakirus** [go-flutter-desktop/go-flutter#78]
The [Changelog](https://github.com/flutter/flutter/wiki/Changelog) contains 2 Embedder API changes:

 [#7497](https://github.com/flutter/engine/pull/7497) Embedder API: `main_path` and `packages_path` in `FlutterProjectArgs` have been renamed to indicate that they should no longer be provided.
 [#7567](https://github.com/flutter/engine/pull/7567)  Embedder API: The `FlutterResult` type has been renamed to `FlutterEngineResult`.

**Comment by Drakirus** [comment]
Good news, none of the above changes breaks `go-flutter`.

**Comment by Drakirus** [comment]
The following message appear when the `go-flutter` embedder is started:
```
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
```

**Comment by GeertJohan** [comment]
We should probably decide which channel we stick to. I'm usually using the dev channel, which was already at 1.2.2, but that channel is not stable at all.. Perhaps it's good to stick to beta and track upcoming features in feature-branches until they land in beta, at which point the feature is merged to master.

**Comment by Drakirus** [comment]
Tracking Beta is good enough.

**Comment by GeertJohan** [comment]
As part of solving this issue, the `flutter_embedder.h` file should be updated to the upstream version linked to v1.2.1.

**Comment by GeertJohan** [comment]
I've already pushed version compatibility information directly to master, PR #81 to update embedder definitions.
