### ISSUE TITLE
embedder.go:140:15: identifier "_Ctype_FlutterPointerPhase" may conflict with identifiers generated by cgo

### ISSUE THREAD

**Issue by kameleon83** [go-flutter-desktop/go-flutter#79]
go get -u -v github.com/go-flutter-desktop/go-flutter    

github.com/go-flutter-desktop/go-flutter (download)
github.com/go-gl/glfw (download)
github.com/go-flutter-desktop/go-flutter/embedder
# github.com/go-flutter-desktop/go-flutter/embedder
../../../github.com/go-flutter-desktop/go-flutter/embedder/embedder.go:140:15: identifier "_Ctype_FlutterPointerPhase" may conflict with identifiers generated by cgo

#### flutter --version
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (il y a 2 semaines) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

**Comment by gedw99** [comment]
I also got the same error

**Comment by Drakirus** [comment]
Same error here.
```sh
$ go version
go version go1.12 linux/amd64
```
It's a new compiler error.

Replacing `_Ctype_FlutterPointerPhase` to `C.FlutterPointerPhase` fixes the issue.

**Comment by dcboy95** [comment]
I am still getting this error running

```
go version
go version go1.12.1 darwin/amd64
```

**Comment by Drakirus** [comment]
Just to clear things up, are you using go-flutter-desktop/go-flutter or Drakirus/go-flutter-desktop-embedder?

https://github.com/go-flutter-desktop/go-flutter/wiki/Package-has-moved-to-an-organization
