### ISSUE TITLE
Improve performance by providing a resource context

### ISSUE THREAD

**Issue by GeertJohan** [go-flutter-desktop/go-flutter#82]
Flutter prints this error. The feature is actually an optional feature, but highly recommended.

`[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(89)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.`

**Comment by Drakirus** [comment]
The warning is related to the texture API.
Since the current embedder doesn't make use of this API, I don't think the performance are impacted.
