### ISSUE TITLE
Wrong PixelRatio calculation (based on DPI scaling)

### ISSUE THREAD

**Issue by ghost** [go-flutter-desktop/go-flutter#84]
Hello, I have a monitor that is uhd, and the dpi that comes configured with the app is very low, is there any way to change it?

![Screenshot from 2019-03-09 17-07-30](https://user-images.githubusercontent.com/43121549/54076826-76f3f700-428e-11e9-883b-aa87f7b6f493.png)

**Comment by GeertJohan** [comment]
@m3k4itr41n 
Are you using the prebuilt release of that app? I think it was built using a version of go-flutter that didn't have proper DPI scaling support.

If you follow the guide to compile locally, you'll get the app in a proper resolution. Please let me know if that works.

I'll leave this ticket open as a reminder to setup CI/CD for the example app releases.

**Comment by m3k4itr41n** [comment]
>Are you using the prebuilt release of that app?

yes

>If you follow the guide to compile locally, you'll get the app in a proper resolution. Please let me know if that works.

nope, it seems that it did not work


I think this is related to this error, right?
```
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(89)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(89)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
calculated pixelRatio limited to a minimum of 1.0
flutter: Observatory listening on http://127.0.0.1:50300/
Reading (A number): 
```

![Screenshot from 2019-03-15 21-51-22](https://user-images.githubusercontent.com/43121549/54468556-98f8e800-476c-11e9-9c06-82a9b3a49f18.png)

**Comment by GeertJohan** [comment]
Are you using a multi-monitor setup? Or are you somehow scaling the virtual screen vs physical screen in X11?

**Comment by m3k4itr41n** [comment]
@GeertJohan I am using only one monitor.

I just changed 2 settings so that it scales well:
- add an environment variable for qt (I very much doubt that you do anything in this project)
- the gnome configuration

![Screenshot from 2019-03-16 19-57-35](https://user-images.githubusercontent.com/43121549/54482683-42e87b00-4826-11e9-8b31-4cb9d7efe69e.png)

**Comment by GeertJohan** [comment]
We'll need some debugging values to see why the ratio was calculated so low.. 

Meanwhile you may be able to add OptionPixelRatio to the options given to `Run(..)`, it forces the amount physical pixels per flutter displaypixel to a given value. Probably a value between 1.4 and 2.0 would work for you. Higher = larger UI. Ofcourse this isn't a permanent solution. I'll work on debug options after #86 is merged.

**Comment by m3k4itr41n** [comment]
@m3k4itr41n Now it looks perfect after changing that, thanks.

![Screenshot from 2019-03-17 18-18-00](https://user-images.githubusercontent.com/43121549/54498122-a4b9eb00-48e1-11e9-95c2-6c07854b0409.png)

But now there is another problem, there are times that it crashes (after a while it is working):
```
[FATAL:flutter/fml/message_loop.cc(23)] Check failed: loop != nullptr. MessageLoop::EnsureInitializedForCurrentThread was not called on this thread prior to message loop use.
SIGABRT: abort
PC=0x7f524de9753f m=4 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f524de9753f
stack: frame={sp:0x7f524aabba40, fp:0x0} stack=[0x7f524a2bc288,0x7f524aabbe88)
00007f524aabb940:  00007f524aabbb90  00007f524aabbb92 
00007f524aabb950:  00007f524aabbba6  00007f524aabbb90 
00007f524aabb960:  00007f524aabbba6  0000000000000000 
00007f524aabb970:  0000000000000000  0000000000000000 
00007f524aabb980:  0000000000000000  0000000000000000 
00007f524aabb990:  0000008000000000  0000000000000000 
00007f524aabb9a0:  0000000000000000  0000000000000000 
00007f524aabb9b0:  0000000000000000  0000000000000000 
00007f524aabb9c0:  ffffffffffffffff  0000000000000000 
00007f524aabb9d0:  0000000000000000  0000000000000000 
00007f524aabb9e0:  00000000ffffffff  0000000000000000 
00007f524aabb9f0:  0000000000000060  0000000000000000 
00007f524aabba00:  0000000000000007  0000000000000070 
00007f524aabba10:  0000000000000007  00007f52400008f8 
00007f524aabba20:  000000000000005f  0000000000000090 
00007f524aabba30:  00000000000000c0  0000000000000000 
00007f524aabba40: <0000000000000000  00000000000000d0 
00007f524aabba50:  000000000000000d  00007f5240000928 
00007f524aabba60:  00000000000000bf  00000000000000f0 
00007f524aabba70:  ffffffffffffffa0  0000000000000003 
00007f524aabba80:  000000330000000d  0000000000000000 
00007f524aabba90:  0000000000000000  00007f524df4d044 
00007f524aabbaa0:  0000000000000000  00000000000000af 
00007f524aabbab0:  00000000000000af  00007f5240000ca0 
00007f524aabbac0:  fffffffe7fffffff  ffffffffffffffff 
00007f524aabbad0:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbae0:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbaf0:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbb00:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbb10:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbb20:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbb30:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f524de9753f
stack: frame={sp:0x7f524aabba40, fp:0x0} stack=[0x7f524a2bc288,0x7f524aabbe88)
00007f524aabb940:  00007f524aabbb90  00007f524aabbb92 
00007f524aabb950:  00007f524aabbba6  00007f524aabbb90 
00007f524aabb960:  00007f524aabbba6  0000000000000000 
00007f524aabb970:  0000000000000000  0000000000000000 
00007f524aabb980:  0000000000000000  0000000000000000 
00007f524aabb990:  0000008000000000  0000000000000000 
00007f524aabb9a0:  0000000000000000  0000000000000000 
00007f524aabb9b0:  0000000000000000  0000000000000000 
00007f524aabb9c0:  ffffffffffffffff  0000000000000000 
00007f524aabb9d0:  0000000000000000  0000000000000000 
00007f524aabb9e0:  00000000ffffffff  0000000000000000 
00007f524aabb9f0:  0000000000000060  0000000000000000 
00007f524aabba00:  0000000000000007  0000000000000070 
00007f524aabba10:  0000000000000007  00007f52400008f8 
00007f524aabba20:  000000000000005f  0000000000000090 
00007f524aabba30:  00000000000000c0  0000000000000000 
00007f524aabba40: <0000000000000000  00000000000000d0 
00007f524aabba50:  000000000000000d  00007f5240000928 
00007f524aabba60:  00000000000000bf  00000000000000f0 
00007f524aabba70:  ffffffffffffffa0  0000000000000003 
00007f524aabba80:  000000330000000d  0000000000000000 
00007f524aabba90:  0000000000000000  00007f524df4d044 
00007f524aabbaa0:  0000000000000000  00000000000000af 
00007f524aabbab0:  00000000000000af  00007f5240000ca0 
00007f524aabbac0:  fffffffe7fffffff  ffffffffffffffff 
00007f524aabbad0:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbae0:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbaf0:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbb00:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbb10:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbb20:  ffffffffffffffff  ffffffffffffffff 
00007f524aabbb30:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [syscall]:
runtime.cgocall(0x4f4630, 0xc0000cdd20, 0x0)
	/usr/lib/golang/src/runtime/cgocall.go:128 +0x5e fp=0xc0000cdcf0 sp=0xc0000cdcb8 pc=0x40d86e
github.com/go-flutter-desktop/go-flutter/embedder._Cfunc___FlutterEngineFlushPendingTasksNow(0x0)
	_cgo_gotypes.go:263 +0x49 fp=0xc0000cdd20 sp=0xc0000cdcf0 pc=0x4eb1c9
github.com/go-flutter-desktop/go-flutter/embedder.FlutterEngineFlushPendingTasksNow()
	/home/sky/go/src/github.com/go-flutter-desktop/go-flutter/embedder/embedder.go:234 +0x22 fp=0xc0000cdd38 sp=0xc0000cdd20 pc=0x4ec322
github.com/go-flutter-desktop/go-flutter.Run(0xc0000dc000, 0x9, 0xe, 0x0, 0x0)
	/home/sky/go/src/github.com/go-flutter-desktop/go-flutter/flutter.go:68 +0x30c fp=0xc0000cdec0 sp=0xc0000cdd38 pc=0x4ef24c
main.main()
	/userspace/.i/.projects/b0x/desktop/main.go:66 +0x28a fp=0xc0000cdf98 sp=0xc0000cdec0 pc=0x4f3c0a
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:201 +0x207 fp=0xc0000cdfe0 sp=0xc0000cdf98 pc=0x4357d7
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000cdfe8 sp=0xc0000cdfe0 pc=0x45e461

goroutine 17 [syscall, locked to thread]:
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwSwapBuffers(0x13bd9a0)
	_cgo_gotypes.go:1965 +0x41
github.com/go-gl/glfw/v3.2/glfw.(*Window).SwapBuffers.func1(0x13bd9a0)
	/home/sky/go/src/github.com/go-gl/glfw/v3.2/glfw/context.go:40 +0x56
github.com/go-gl/glfw/v3.2/glfw.(*Window).SwapBuffers(0xc00006ed60)
	/home/sky/go/src/github.com/go-gl/glfw/v3.2/glfw/context.go:40 +0x2e
github.com/go-flutter-desktop/go-flutter.runFlutter.func3(0x13bd9a0, 0xc0000c0300)
	/home/sky/go/src/github.com/go-flutter-desktop/go-flutter/flutter.go:283 +0x79
github.com/go-flutter-desktop/go-flutter/embedder.proxy_present(0x13bd9a0, 0x5554f8)
	/home/sky/go/src/github.com/go-flutter-desktop/go-flutter/embedder/embedder_proxy_glfw.go:61 +0xa8
github.com/go-flutter-desktop/go-flutter/embedder._cgoexpwrap_e732fb4ddc9b_proxy_present(0x13bd9a0, 0x7f524eee8ddd)
	_cgo_gotypes.go:376 +0x2b

rax    0x0
rbx    0x6
rcx    0x7f524de9753f
rdx    0x0
rdi    0x2
rsi    0x7f524aabba40
rbp    0xa
rsp    0x7f524aabba40
r8     0x0
r9     0x7f524aabba40
r10    0x8
r11    0x246
r12    0xc0000ce000
r13    0x7f524b2bca7f
r14    0x7f524aabbcd8
r15    0x7f5240000ca0
rip    0x7f524de9753f
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by Drakirus** [comment]
The DPI issue seems to be resolved. Closing the issue. 

A new version is around the corner, once #86 gets merged, please report us any new issues.

**Comment by GeertJohan** [comment]
Actually, the DPI issue was patched with duct tape.. I'd like to know why the calculated DPI is wrong..

@m3k4itr41n Could you please update to the latest version and remove the `OptionPixelRatio`, so it calculates based on screen dimensions again? It should give you the same warning ("calculated pixelRatio limited to a minimum of 1.0") but now with a bunch of numeric values added behind it. Please send me those logs. Also please send me the resolution of your screen and the size (width in milimeters) of your screen.

By the way, the "Check failed: loop != nullptr. MessageLoop::EnsureInitializedForCurrentThread" problem should be fixed in the latest version of go-flutter.

**Comment by Drakirus** [comment]
Pixel ratio issue should be solved by 2119e28

**Comment by GeertJohan** [comment]
@Drakirus 
No, that mistake was introduced when adding more debug info for this issue.

**Comment by b0o** [comment]
Hey @GeertJohan, I am seeing this issue as well. Here's the debug output:
```
go-flutter: calculated pixelRatio limited to a minimum of 1.0. metrics: {"dpi":101.6,"monitorWidthMm":480,"monitorWidthSc":1920,"mscpi":101.6,"pixelRatio":0.635,"ppsc":1,"windowWidthPx":3840,"windowWidthSc":3840}
```

I'm on a Linux system with a  multihead setup and two HiDPI displays which I configure with XRandR:

```sh
#!/bin/bash
# DisplayPort-0:   Disabled
# DisplayPort-1: * Ext R (Horizontal) ]
# DisplayPort-2:   Ext L (Vertical)
# HDMI-A-0:        Wacom (Horizontal)

xrandr --output DisplayPort-0 --off

xrandr --output DisplayPort-1 --scale 2x2 \
  --output      DisplayPort-2 --scale 2x2 \
  --output      HDMI-A-0      --scale 2x2

xrandr --output DisplayPort-2 --rotate left --left-of DisplayPort-1 \
  --output      DisplayPort-1 --above HDMI-A-0

xrandr --output DisplayPort-2 --pos 0x0    --mode 1920x1080 \
  --output      DisplayPort-1 --pos 2160x0 --mode 1920x1080 \
  --output      HDMI-A-0 --pos 2160x2160   --mode 1024x768
``` 

The hover example application was run on my `DisplayPort-1` monitor.

Various system/version info:

- Arch Linux:
  ```
  $ uname -srvo
  Linux 5.1.12-arch1-1-ARCH #1 SMP PREEMPT Wed Jun 19 09:16:00 UTC 2019 GNU/Linux
  ```
- Flutter:
  ```
  $ flutter --version
  Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
  Framework • revision 7a4c33425d (8 weeks ago) • 2019-04-29 11:05:24 -0700
  Engine • revision 52c7a1e849
  Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
  ```
- WM: `xmonad`
- hover: `v0.19.0`
- full debug output:
  ```
  maddy ♥ ~/git » cd go-flutter-examples/simple_demo
  maddy ♥ git/go-flutter-examples/simple_demo » hover run
  Using engine from cache
  go: finding github.com/go-gl/glfw latest
  [ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
  flutter: Observatory listening on http://127.0.0.1:50300/oLCiiNzUF8Y=/
  [ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
  go-flutter: calculated pixelRatio limited to a minimum of 1.0. metrics: {"dpi":101.6,"monitorWidthMm":480,"monitorWidthSc":1920,"mscpi":101.6,"pixelRatio":0.635,"ppsc":1,"windowWidthPx":3840,"windowWidthSc":3840}
  go-flutter: no method handler registered for method 'SystemChrome.setSystemUIOverlayStyle' on channel 'flutter/platform'
  Syncing files to device Flutter test device...                   1,067ms
  
  🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
  An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:50300/oLCiiNzUF8Y=/
  For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
  go-flutter: no method handler registered for method 'SystemSound.play' on channel 'flutter/platform'
  go-flutter: no method handler registered for method 'SystemSound.play' on channel 'flutter/platform'
  go-flutter: no method handler registered for method 'SystemSound.play' on channel 'flutter/platform'
  go-flutter: no method handler registered for method 'SystemSound.play' on channel 'flutter/platform'
  go-flutter: no method handler registered for method 'SystemSound.play' on channel 'flutter/platform'
  go-flutter: failed to pop route after escape key press: failed to decode envelope: unexpected end of JSON input
  go-flutter: closing application
  hover: app 'simple_demo' exited.
  hover: closing the flutter attach sub process..
  Lost connection to device.
  ```

Hope this is useful - if you want any more info, let me know 😃

**Comment by b0o** [comment]
> We'll need some debugging values to see why the ratio was calculated so low..
> 
> Meanwhile you may be able to add OptionPixelRatio to the options given to `Run(..)`, it forces the amount physical pixels per flutter displaypixel to a given value. Probably a value between 1.4 and 2.0 would work for you. Higher = larger UI. Ofcourse this isn't a permanent solution. I'll work on debug options after #86 is merged.

Also, I just tried this with the `stocks` and `pointer_demo` examples, and the UI scales as expected but then the mouse cursor location is not tracked properly. 

Prior to change (bad DPI, good cursor position):
![flutter-hover-dpi-scale-expected](https://user-images.githubusercontent.com/21299126/60223072-88a8dc80-9834-11e9-8728-407ffc7f3426.gif)

Post change (good DPI, bad cursor position):
![flutter-hover-dpi-scale-bug](https://user-images.githubusercontent.com/21299126/60223073-88a8dc80-9834-11e9-9cb0-395a5178b131.gif)

Change to `desktop/cmd/options.go`:
```go
package main

import (
	"github.com/go-flutter-desktop/go-flutter"
)

var options = []flutter.Option{
	flutter.WindowInitialDimensions(800, 1280),
	flutter.OptionPixelRatio(2.0),
}
```

**Comment by Drakirus** [comment]
Hey @b0o 
Thanks for sharing all this information.
It helped me your identify the second issue you described (the one about `flutter.ForcePixelRatio(2.0)`)

I've found a [fix](https://github.com/go-flutter-desktop/go-flutter/compare/hotfix/pixelsPerScreen?expand=1), and it is available for testing using:
```
hover run -b '@hotfix/pixelsPerScreen'
```
If it solves the second issue you described, I'll merge the branch.
Thanks 😃

**Comment by b0o** [comment]
@Drakirus

That hotfix does indeed fix the cursor position issue.

**Comment by Drakirus** [comment]
@b0o hotfix merged.
Keeping this issue open since the original issue isn't fixed.

**Comment by GeertJohan** [comment]
Thanks @Drakirus for fixing the cursor position bug. Indeed this issue is a separate problem.

Thanks @b0o for the great debug info. 
So, I actually encounter this problem as well, I have a 4k screen in my laptop and use `--scale 2x2` for a non-4k screen that's attached via HDMI. There's a difference in behavior depending on which the monitor is set as the primary monitor, because #74. 

I wonder if glfw should expose the "virtual pixels" vs "real pixels" difference in their screen coordinates.
I also use `xmonad` by the way, but so far I don't think that has anything to do with it.

Currently near my external monitor, will have to dive into this later.

**Comment by GeertJohan** [comment]
So here is a setup I have where the same issue occurs.
- My laptop has a 4K display (AU Optronics Corporation), on the left
- An external display is attached (LG Electronics 34UM95)
- To match DPI between the built-in screen and the external screen, I scale that display 2x2. It is rendered at 6880x2800, then downscaled by X11 to the actual 3440x1440 that the display has.
- go-flutter sees the external display as primary monitor, and calculates pixelRatio based on that.
- glfw returns the video mode of the external monitor as 3440x1440, not the size of the rendered display to which the framebuffer is written.
- The calculated pixelRatio is wrong because flutter should render for a 6880x2880 virtual display. `go-flutter: calculated pixelRatio limited to a minimum of 1.0. metrics: {"dpi":109.22,"monitorWidthMm":800,"monitorWidthSc":3440,"mscpi":109.22,"pixelRatio":0.682625,"ppsc":1,"windowWidthPx":798,"windowWidthSc":798}`

![dpi](https://user-images.githubusercontent.com/564501/61455287-64d44480-a963-11e9-97de-bd74a00581c2.png)

I wonder if this is changed in GLFW 3.3
Using GLFW 3.2, there is no way for go-flutter to "see" the rendered display resolution.

**Comment by pchampio** [comment]
`hover run -b '@go-glv3.3'` shoud fix the issue.
waiting for https://github.com/go-flutter-desktop/go-flutter/pull/298 to be merged!
