### ISSUE TITLE
unexpected signal during runtime execution  on Mac Mojave

### ISSUE THREAD

**Issue by rfsx0829** [go-flutter-desktop/go-flutter#87]
I successfully built main.go, but the generated binary does not work.

Here is the error message

$ go build main.go 
$ ./main 
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x40f0bd3]

runtime stack:
runtime.throw(0x414b1f1, 0x2a)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall]:
runtime.cgocall(0x40fca50, 0xc0000bbbd8, 0xc000000008)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/cgocall.go:128 +0x5e fp=0xc0000bbba8 sp=0xc0000bbb70 pc=0x400559e
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwDestroyWindow(0x5e1fac0)
        _cgo_gotypes.go:580 +0x41 fp=0xc0000bbbd8 sp=0xc0000bbba8 pc=0x40dfc01
github.com/go-gl/glfw/v3.2/glfw.(*Window).Destroy.func1(0x5e1fac0)
        /Users/zeng/go/src/github.com/go-gl/glfw/v3.2/glfw/window.go:302 +0x56 fp=0xc0000bbc10 sp=0xc0000bbbd8 pc=0x40e4e06
github.com/go-gl/glfw/v3.2/glfw.(*Window).Destroy(0xc0000cc000)
        /Users/zeng/go/src/github.com/go-gl/glfw/v3.2/glfw/window.go:302 +0x4b fp=0xc0000bbc30 sp=0xc0000bbc10 pc=0x40e3a2b
runtime.call32(0x0, 0x414cab8, 0xc0000a4030, 0x800000008)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:522 +0x3b fp=0xc0000bbc60 sp=0xc0000bbc30 pc=0x405448b
panic(0x4114ea0, 0x41620c0)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9 fp=0xc0000bbcf0 sp=0xc0000bbc60 pc=0x402b4a9
github.com/go-flutter-desktop/go-flutter.runFlutter(0xc0000cc000, 0x320, 0x258, 0xc0000b4180, 0x78, 0xc000086060, 0x59, 0x0, 0x414cc20, 0x0, ...)
        /go/src/github.com/go-flutter-desktop/go-flutter/flutter.go:319 +0x410 fp=0xc0000bbd48 sp=0xc0000bbcf0 pc=0x40eab30
github.com/go-flutter-desktop/go-flutter.Run(0xc0000ae180, 0x8, 0xc, 0x0, 0x0)
        /go/src/github.com/go-flutter-desktop/go-flutter/flutter.go:61 +0x2da fp=0xc0000bbed0 sp=0xc0000bbd48 pc=0x40e9e7a
main.main()
        /go/src/github.com/go-flutter-desktop/go-flutter/example/simpleDemo/main.go:64 +0x255 fp=0xc0000bbf98 sp=0xc0000bbed0 pc=0x40ee7c5
runtime.main()
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/proc.go:201 +0x207 fp=0xc0000bbfe0 sp=0xc0000bbf98 pc=0x402d2e7
runtime.goexit()
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000bbfe8 sp=0xc0000bbfe0 pc=0x4056181

**Comment by winner484** [comment]
go version 1.12
flutter 1.0.0

i got the same error on ubuntu.
    fengyu@fengyu-desktop:~/go-flutter/example/simpleDemo$ ./main
    fatal error: unexpected signal during runtime execution
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4fa803]

    runtime stack:
    runtime.throw(0x556983, 0x2a)

**Comment by Drakirus** [comment]
A new version is around the corner, once #86 gets merged, we'll check the issue.

**Comment by GeertJohan** [comment]
@rfsx0829 It looks like the function call to destroy was made from an invalid thread. Could you please try again with the latest version of go-flutter, it contains fixes concerning thread-safety, this will probably fix the problem. Please re-open this issue if the problem still occurs.
