### ISSUE TITLE
Mage based building & ci

### ISSUE THREAD

**Issue by ghost** [go-flutter-desktop/go-flutter#9]
Hopefully anyone reading this knows what golang mage is and the problems it solves for cross platform building - especially on desktops.

I think a mage script will really help the pace and regressions.

A great example of using it is elastic beats repo.

https://github.com/elastic/beats

For with does,Mac and Linux there is a make file that checks mage is installed and them mage all the way from there.
You can do exactly the same in CI on Travis, appveyor, etc etc.

I would start with the basics like beats does and then extend from there.

They also can build and sign golang apps for desktop and build installers for both platforms ! All from golang.

Give it a look ...

**Comment by gedw99** [comment]
I got a prototype working.
It inspects the current flutter installed and then pulls the correct flutter embedded binary based on the sha.

But for some reason I can't get the final cgo binding to work on my Mac when I follow the Mac sh script.

Maybe I should upload it to the fork and you can have a look to see what I am doing wrong.

I also want to add packaging and signing for Mac and Windows but first need help with cgo.

**Comment by Drakirus** [comment]
Feel free to create a new Issue with the related CGO errors logs.

**Comment by zephylac** [comment]
Maybe this issue is linked to #31 and #29. It is not mage file but it should work.

**Comment by gedw99** [comment]
@GeertJohan Sorry i have not had time to implement this. It is on my todo list still !!

**Comment by GeertJohan** [comment]
Cool. I'm also working on a tool; glutter, which uses go, flutter, maybe [xgo](https://github.com/karalabe/xgo) to initialize and build a flutter application for desktop. But it's always good to have multiple ways to do it.

**Comment by Drakirus** [comment]
The tool [`hover`](https://github.com/go-flutter-desktop/hover) exist, Mage build is irrelevant.
CI can be good, it could enable us to have pre-build version of go-flutter. CI is irrelevant in the same way flutter dosn't provide pre-build version of android flutter, users will add plugins...
