### ISSUE TITLE
Add support for scrolling

### ISSUE THREAD

**Issue by GeertJohan** [go-flutter-desktop/go-flutter#91]
Enum and field in embedder.h support suggest support for scrolling.

https://github.com/flutter/engine/blob/4b01d795feec3ba8231a397a4ec2759954d8216e/shell/platform/embedder/embedder.h#L292
and
https://github.com/flutter/engine/blob/4b01d795feec3ba8231a397a4ec2759954d8216e/shell/platform/embedder/embedder.h#L307

**Comment by Drakirus** [comment]
Related to #7

**Comment by GeertJohan** [comment]
Whoops, duplicate even!
