### ISSUE TITLE
linux app not work

### ISSUE THREAD

**Issue by winner484** [go-flutter-desktop/go-flutter#92]
###### `$ flutter --version`

```
Flutter 1.3.10 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 4feefa3c9a (2 days ago) • 2019-03-14 10:21:03 -0400
Engine • revision 8b1a299ed5
Tools • Dart 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)

```

###### Download [Link](https://github.com/go-flutter-desktop/go-flutter/releases)
 
 - Yes

## Steps to Reproduce

1. use IDEA build a default flutter app "untitled"
2. copy "untitled" to /go-flutter-0.4.0-alpha/example/simpleDemo/flutter_project
3. cd /utitled2   flutter build bundle
4. cd ../.. copy main.go .rename to main1.go.  modify main1.go path.
5. export CGO_LDFLAGS="-L${PWD}"
6. go build main1.go
7. get the main1 app .
8. open main1 but ERROR
```
    fengyu@fengyu-desktop:~/go-flutter-0.4.0-alpha/example/simpleDemo$ ./main1 
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
flutter: Observatory listening on http://127.0.0.1:50300/
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
calculated pixelRatio limited to a minimum of 1.0
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MyApp(dirty):
flutter: Unknown platform.
flutter: linux was not recognized as a target platform. Consider updating the list of TargetPlatforms to
flutter: include this platform.
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      defaultTargetPlatform (package:flutter/src/foundation/platform.dart:68:5)
flutter: #1      new ThemeData (package:flutter/src/material/theme_data.dart:214:18)
flutter: #2      MyApp.build (package:untitled2/main.dart:11:14)
flutter: #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3788:28)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3735:15)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
flutter: #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
flutter: #10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
flutter: #11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
flutter: #12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
flutter: #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2251:19)
flutter: #14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
flutter: #16     runApp (package:flutter/src/widgets/binding.dart:780:7)
flutter: #17     main (package:untitled2/main.dart:3:16)
flutter: #18     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:199:25)
flutter: #23     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:190:5)
flutter: #24     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:300:19)
flutter: #25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
flutter: (elided 4 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Unknown platform.
    flutter: Another exception was thrown: Unknown platform.
```

**Comment by winner484** [comment]
@GeertJohan Thank you very much! It works!
but i get new ERROR here. and the "StreamBuilder" or websocket not works will.
i build a very simple chat room, and it worked will in android virtual device. But this linux desk version not works will.
when i open the chat room app, the websocket server show that the chat room app connected, and push back one greet message. but the chat room app can not display the greet message.
here is the detail:

    fengyu@fengyu-desktop:~/go-flutter/example/simpleDemo$ ./main 
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
flutter: Observatory listening on http://127.0.0.1:50300/
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
    calculated pixelRatio limited to a minimum of 1.0

**Comment by winner484** [comment]
@GeertJohan even the prebuilt demo also shows the same error in terminal, but the gui app works will,and every word can be showed.

**Comment by GeertJohan** [comment]
The errors that you see should not cause an issue with your app. Probably there is a plugin that is not working correctly?
Please update to the latest version of go-flutter, it has a new plugin setup and will log more information when there is a missing plugin.

**Comment by winner484** [comment]
@GeertJohan Thank you! i already use the latest go-flutter version.but still can not work. 
Which version of flutter do you use? 
Android studio or IDEA?

**Comment by GeertJohan** [comment]
It should work with the beta channel, at version 1.3.8

**Comment by lucaszanella** [comment]
Hi @GeertJohan 

I have the same problem, then I switched to the beta channel but I can't find linux device. 

```
flutter config --enable-linux-desktop
Could not find an option named "enable-linux-desktop".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and
options.

```

Doesn't only master channel has linux support?

**Comment by Drakirus** [comment]
@lucaszanella Ah, this repo is about go-flutter, an alternative embedder to the official flutter project.
Sorry about the confusion.

To use this alternative embedder please use [hover](https://github.com/go-flutter-desktop/hover).
Make sure to read the repos README.
