### ISSUE TITLE
Flutter bootstrapper

### ISSUE THREAD

**Issue by gedw99** [go-flutter-desktop/go-flutter#94]
https://github.com/leoafarias/fvm

Nice.

thinking of making part of the Makefile automation.
good idea ?

**Comment by Drakirus** [comment]
Please use the [gitter](https://gitter.im/go-flutter-desktop/go-flutter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for those kinds of propositions.
