### ISSUE TITLE
'dyld: Library not loaded' and 'Reason: image not found'

### ISSUE THREAD

**Issue by wonderful89** [go-flutter-desktop/go-flutter#97]
## Envs

![image](https://user-images.githubusercontent.com/44089389/54796355-e4d6f000-4c8a-11e9-876b-f93f3bfdcf53.png)

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/44089389/54796414-24054100-4c8b-11e9-9d0d-de258eec679f.png)

```
➜  simpleDemo git:(master) ✗ flutter --version
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (5 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
➜  simpleDemo git:(master) ✗ go version
go version go1.12.1 darwin/amd64
➜  simpleDemo git:(master) ✗ go build main.go

```

## Golang errors (Optional)

```
➜  simpleDemo git:(master) ✗ go run main.go
dyld: Library not loaded: @rpath/FlutterEmbedder.framework/Versions/A/FlutterEmbedder
  Referenced from: /var/folders/lf/rw4cnct57k5c3l0wd6tydhmm0000gn/T/go-build400860304/b001/exe/main
  Reason: image not found
signal: abort trap
```

**Comment by GeertJohan** [comment]
Do you also get this error when just running the binary?
Right now, you first `go build main.go`, which outputs a binary (`main`), you should be able to just execute that binary (`./main`).

`go run` doesn't work, as stated at the bottom of the instructions.

**Comment by wonderful89** [comment]
Oh my god. It turned out to be like this. 

I understand. @GeertJohan , Thanks. I hurry up to close this issue.

**Comment by GeertJohan** [comment]
No problem @wonderful89 , glad to be of help :)
