### ISSUE TITLE
Packaging for Mac

### ISSUE THREAD

**Issue by ghost** [go-flutter-desktop/go-flutter#99]
I am using Hover. Its really great btw !

I noticed that on MAC, the exe opens a terminal and then opens the Flutter GUI.
I think most of this is because its not packaged as  Mac .app.
Here is a pure golang packager for Mac.
https://gist.github.com/mholt/11008646c95d787c30806d3f24b2c844
I am thinking that it might be cool to integrate into Hover itself.

I got the packaging working but not the symbolic links.
It seems that hover puts the flutter framework in:
Library/Caches/hover/engine/darwin/....

Not sure how what i should do ? Seems what we do now is not so smart.
https://github.com/go-flutter-desktop/hover/blob/master/internal/enginecache/cache.go#L320

**Comment by AppleEducate** [comment]
@gedw99 How would I use your GIST?

**Comment by gedw99** [comment]
here is example code.

```
mkdir -p ./pack

	go run ./mac/main.go \
		-assets $(PWD)/assets \
		-bin $(BINARY) \
		-icon $(PWD)/icon02.png  \
		-identifier "com.example."$(BINARY) \
		-name $(BINARY) \
		-o $(PWD)/pack
```

At the moment the symbolic links fails.
I think we should put this into hover or another repo here to work on it.

**Comment by AppleEducate** [comment]
Ok sweet thank you! I’m excited about desktop embedding, I have been using flutter for over a year

**Comment by gedw99** [comment]
me too.
Sorry i have not had time to work on the Mac packaging.
I suggested that it go into hover, but i think its early days.

**Comment by Sach97** [comment]
Hi @gedw99 the issue I see with this approach is that it only works on Mac because it depends on hdiutil. What about this [shell approach](https://github.com/Xeoncross/macappshell) ?

**Comment by gedw99** [comment]
hey @Sach97 
Had a look at pure shell. All the calls are for native MacOS stuff that is installed in a normal Mac so its ok by me.
I think its cool if we put the .sh into Hover.
This will mean none golang code but its probably best as for each Desktop the Packaging and Signing is very OS specific.

Also happy to see this being looked at for incorporation into Hover.
Will be a good start and can add Windows signing too with time.

**Comment by Drakirus** [comment]
Moved to #207.
